//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSKeychainSyncTextEntryController.h>


@class NSString, PSKeychainSyncManager, UIButton;

@interface KeychainSyncSMSVerificationController : PSKeychainSyncTextEntryController <UIAlertViewDelegate>
{
    UIButton *_footerButton;
    NSString *_phoneNumber;
    NSString *_dialingPrefix;
    NSString *_countryCode;
    PSKeychainSyncManager *_keychainSyncManager;
}

@property(nonatomic) __weak PSKeychainSyncManager *keychainSyncManager; // @synthesize keychainSyncManager=_keychainSyncManager;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(retain, nonatomic) NSString *dialingPrefix; // @synthesize dialingPrefix=_dialingPrefix;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
// - (void).cxx_destruct;
- (void)dismissAlerts;
- (void)showSupportVerification;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)specifiers;
- (id)init;

@end

