//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@interface NSArray (PKIconCache)
+ (void)pk_updateSpecifiers:(id)arg1 withIconsFromCache:(id)arg2 isInterfaceRTL:(BOOL)arg3;
+ (void)pk_updateSpecifiers:(id)arg1 withIconsFromCache:(id)arg2;
- (id)arrayByPerformingSpecifierUpdatesUsingBlock:(CDUnknownBlockType)arg1;
- (NSUInteger)indexOfSpecifierWithID:(id)arg1;
- (id)specifierForID:(id)arg1;
@end

