//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@interface NSMutableArray (PSSpecifierUpdates)
- (void)performSpecifierUpdatesUsingBlock:(CDUnknownBlockType)arg1;
- (void)ps_addGroup:(id)arg1 afterGroup:(id)arg2;
- (void)ps_addSpecifiers:(id)arg1 toGroup:(id)arg2;
- (void)ps_addSpecifier:(id)arg1 toGroup:(id)arg2;
- (void)ps_insertObjectsFromArray:(id)arg1 afterObject:(id)arg2;
- (void)ps_insertObject:(id)arg1 afterObject:(id)arg2;
- (void)ps_addPossibleObject:(id)arg1;
@end

