//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSTableCell.h>

#import <Preferences/PSPasscodeFieldDelegate-Protocol.h>

@class PSPasscodeField;
@protocol KeychainSyncPasscodeFieldDelegate;

@interface PasscodeFieldCell : PSTableCell <PSPasscodeFieldDelegate>
{
    PSPasscodeField *_passcodeField;
    BOOL _convertsNumeralsToASCII;
    BOOL _denyFirstResponder;
    id <KeychainSyncPasscodeFieldDelegate> _delegate;
}

@property(readonly, nonatomic) PSPasscodeField *passcodeField; // @synthesize passcodeField=_passcodeField;
@property(nonatomic) BOOL denyFirstResponder; // @synthesize denyFirstResponder=_denyFirstResponder;
@property(nonatomic) BOOL convertsNumeralsToASCII; // @synthesize convertsNumeralsToASCII=_convertsNumeralsToASCII;
@property(nonatomic) __weak id <KeychainSyncPasscodeFieldDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)layoutSubviews;
- (long long)keyboardType;
- (void)deleteBackward;
- (id)passcodeField:(id)arg1 shouldInsertText:(id)arg2;
- (BOOL)hasText;
- (id)passcodeText;
- (BOOL)becomeFirstResponder;
- (void)setPasscodeText:(id)arg1;
- (void)passcodeField:(id)arg1 enteredPasscode:(id)arg2;
- (void)_setSecureTextEntry:(BOOL)arg1;
- (void)cellTapped:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

