//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@interface ProblemReportingAboutController : UIViewController
{
}

- (void)donePressed;
- (id)initWithTitle:(id)arg1 content:(id)arg2;

@end

