//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface PSBrightnessController : NSObject
{
    id /* CDUnknownBlockType */ _isTracking;
    id /* CDUnknownBlockType */ _brightnessChangedExternally;
}

+ (id)sharedController;
@property(copy, nonatomic) id /* CDUnknownBlockType */ brightnessChangedExternally; // @synthesize brightnessChangedExternally=_brightnessChangedExternally;
@property(copy, nonatomic) id /* CDUnknownBlockType */ isTracking; // @synthesize isTracking=_isTracking;
// - (void).cxx_destruct;

@end

