//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class PSListController;

@interface PSBundleController : NSObject
{
    PSListController *_parent;
}

// - (void).cxx_destruct;
- (id)initWithParentListController:(id)arg1;
- (id)initWithParentListController:(id)arg1 properties:(id)arg2;
- (id)init;
- (id)specifiersWithSpecifier:(id)arg1;
- (void)unload;
- (void)load;

@end

