//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>


@class NSArray;

@interface PSCapacityBarData : NSObject <NSCopying>
{
    NSArray *_orderedCategories;
    NSArray *_adjustedCategories;
    BOOL _hideTinyCategories;
    int _sortStyle;
    long long _categoryLimit;
    long long _capacity;
    long long _bytesUsed;
    NSArray *_categories;
}

@property(retain, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property long long bytesUsed; // @synthesize bytesUsed=_bytesUsed;
@property long long capacity; // @synthesize capacity=_capacity;
@property int sortStyle; // @synthesize sortStyle=_sortStyle;
@property BOOL hideTinyCategories; // @synthesize hideTinyCategories=_hideTinyCategories;
@property long long categoryLimit; // @synthesize categoryLimit=_categoryLimit;
// - (void).cxx_destruct;
@property(readonly) NSArray *adjustedCategories;
@property(readonly) NSArray *orderedCategories;
// - (id)copyWithZone:(_NSZone )arg1;

@end

