//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSString, PSLegendColorView, UIColor, UILabel;

@interface PSCapacityBarLegendView : UIView
{
    PSLegendColorView *_legendColor;
    UILabel *_legendLabel;
}

// - (void).cxx_destruct;
@property(retain, nonatomic) UIColor *color;
@property(retain, nonatomic) NSString *text;
@property(retain, nonatomic) UIColor *textColor;
- (void)createConstraints;
- (id)initWithCapacityBarCategory:(id)arg1;

@end

