//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Preferences/CommerceRemoteUIDelegateDelegate-Protocol.h>

@class CommerceRemoteUIDelegate;
@protocol PSCloudStorageOffersManagerDelegate;

@interface PSCloudStorageOffersManager : NSObject <CommerceRemoteUIDelegateDelegate>
{
    CommerceRemoteUIDelegate *_commerceDelegate;
    BOOL _shouldOfferFamilySharePlansOnly;
    BOOL _shouldOfferDeviceOffers;
    BOOL _skipRetryWithoutToken;
    BOOL _skipCompletionAlert;
    BOOL _supportsModernAlerts;
    id <PSCloudStorageOffersManagerDelegate> _delegate;
    NSUInteger _requiredStorageThreshold;
}

@property(nonatomic) BOOL supportsModernAlerts; // @synthesize supportsModernAlerts=_supportsModernAlerts;
@property(nonatomic) BOOL skipCompletionAlert; // @synthesize skipCompletionAlert=_skipCompletionAlert;
@property(nonatomic) BOOL skipRetryWithoutToken; // @synthesize skipRetryWithoutToken=_skipRetryWithoutToken;
@property(nonatomic) BOOL shouldOfferDeviceOffers; // @synthesize shouldOfferDeviceOffers=_shouldOfferDeviceOffers;
@property(nonatomic) BOOL shouldOfferFamilySharePlansOnly; // @synthesize shouldOfferFamilySharePlansOnly=_shouldOfferFamilySharePlansOnly;
@property(nonatomic) NSUInteger requiredStorageThreshold; // @synthesize requiredStorageThreshold=_requiredStorageThreshold;
@property(nonatomic) __weak id <PSCloudStorageOffersManagerDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)commerceDelegate:(id)arg1 didCompleteWithError:(id)arg2;
- (void)commerceDelegateDidCancel:(id)arg1;
- (void)commerceDelegate:(id)arg1 loadDidFailWithError:(id)arg2;
- (void)commerceDelegate:(id)arg1 willPresentObjectModel:(id)arg2 page:(id)arg3;
- (void)dealloc;
- (void)cancelLoad;
- (void)beginFlowWithNavigationController:(id)arg1 purchaseToken:(id)arg2 buyParameters:(id)arg3 requestHeaders:(id)arg4 modally:(BOOL)arg5;
- (void)beginFlowWithNavigationController:(id)arg1 modally:(BOOL)arg2;
- (void)_setupFlowWithNavigationController:(id)arg1 modally:(BOOL)arg2;

@end

