//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSTableCell.h>

@class UIControl;

@interface PSControlTableCell : PSTableCell
{
    UIControl *_control;
}

// - (void).cxx_destruct;
- (void)controlChanged:(id)arg1;
- (id)controlValue;
@property(retain, nonatomic) UIControl *control;
- (void)dealloc;
- (id)valueLabel;
- (BOOL)canReload;
- (id)newControl;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

