//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class PSSpecifier, UIDatePicker;

@protocol PSDateTimePickerCellDelegate
- (void)datePickerChanged:(id)arg1;

@optional
- (UIDatePicker *)datePickerForSpecifier:(PSSpecifier *)arg1;
@end

