//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSViewController.h>

@class PSEditingPane;

@interface PSDetailController : PSViewController
{
    PSEditingPane *_pane;
}

// - (void).cxx_destruct;
- (void)statusBarWillAnimateByHeight:(double)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)suspend;
- (void)saveChanges;
- (id)title;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadPane;
@property(nonatomic) __weak PSEditingPane *pane;
- (void)viewDidLayoutSubviews;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (CGRect)paneFrame;
- (void)dealloc;
- (void)viewDidUnload;
- (void)loadView;

@end

