//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSListController.h>

@interface PSEditableListController : PSListController
{
    BOOL _editable;
    BOOL _editingDisabled;
}

- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)didLock;
- (void)suspend;
- (BOOL)performDeletionActionForSpecifier:(id)arg1;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)setEditable:(BOOL)arg1;
- (void)_setEditable:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)editable;
- (void)editDoneTapped;
- (void)showController:(id)arg1 animate:(BOOL)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setEditButtonEnabled:(BOOL)arg1;
- (void)setEditingButtonHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_updateNavigationBar;
- (id)_editButtonBarItem;
- (id)init;

@end

