//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Preferences/KeychainSyncViewControllerDelegate-Protocol.h>

@class KeychainSyncAdvancedSecurityCodeController, KeychainSyncDevicePINController, KeychainSyncPhoneNumberController, KeychainSyncSMSVerificationController, NSString, NSTimer, PSKeychainSyncSecurityCodeController, PSRootController, PSSetupController, UIView, UIViewController;

@interface PSKeychainSyncManager : NSObject <KeychainSyncViewControllerDelegate>
{
    BOOL _joiningCircle;
    BOOL _joiningCircleAfterRecovery;
    int _circleNotificationToken;
    int _flow;
    KeychainSyncDevicePINController *_devicePinController;
    PSKeychainSyncSecurityCodeController *_simpleSecurityCodeController;
    PSKeychainSyncSecurityCodeController *_complexSecurityCodeController;
    KeychainSyncAdvancedSecurityCodeController *_advancedSecurityCodeChoiceController;
    PSKeychainSyncSecurityCodeController *_securityCodeRecoveryController;
    KeychainSyncPhoneNumberController *_phoneNumberController;
    KeychainSyncSMSVerificationController *_smsValidationController;
    UIView *_spinningView;
    unsigned int _spinnerCount;
    NSTimer *_credentialExpirationTimer;
    NSTimer *_joinAfterRecoveryTimeoutTimer;
    BOOL _circleWasReset;
    int _stagedSecurityCodeType;
    NSString *_appleIDUsername;
    NSString *_appleIDRawPassword;
    NSString *_appleIDPasswordOrEquivalentToken;
    id /* CDUnknownBlockType */ _completion;
    id /* CDUnknownBlockType */ _passwordPromptCompletion;
    id /* CDUnknownBlockType */ _changeSecurityCodeCompletion;
    id /* CDUnknownBlockType */ _resetCompletion;
    id /* CDUnknownBlockType */ _circleJoinCompletion;
    UIViewController *_resetPromptControllerHost;
    UIViewController *_hostViewController;
    PSSetupController *_settingsSetupController;
    PSRootController *_buddyNavigationController;
    NSString *_securityCodeRecoveryAttempt;
    NSString *_stagedSecurityCode;
}

+ (void)getStatusWithCompletion:(CDUnknownBlockType)arg1;
+ (id)sharedManager;
@property(nonatomic) BOOL circleWasReset; // @synthesize circleWasReset=_circleWasReset;
@property(readonly, nonatomic) int stagedSecurityCodeType; // @synthesize stagedSecurityCodeType=_stagedSecurityCodeType;
@property(readonly, nonatomic) NSString *stagedSecurityCode; // @synthesize stagedSecurityCode=_stagedSecurityCode;
@property(retain, nonatomic) NSString *securityCodeRecoveryAttempt; // @synthesize securityCodeRecoveryAttempt=_securityCodeRecoveryAttempt;
@property(retain, nonatomic) PSRootController *buddyNavigationController; // @synthesize buddyNavigationController=_buddyNavigationController;
@property(retain, nonatomic) PSSetupController *settingsSetupController; // @synthesize settingsSetupController=_settingsSetupController;
@property(nonatomic) __weak UIViewController *hostViewController; // @synthesize hostViewController=_hostViewController;
@property(retain, nonatomic) UIViewController *resetPromptControllerHost; // @synthesize resetPromptControllerHost=_resetPromptControllerHost;
@property(copy, nonatomic) id /* CDUnknownBlockType */ circleJoinCompletion; // @synthesize circleJoinCompletion=_circleJoinCompletion;
@property(copy, nonatomic) id /* CDUnknownBlockType */ resetCompletion; // @synthesize resetCompletion=_resetCompletion;
@property(copy, nonatomic) id /* CDUnknownBlockType */ changeSecurityCodeCompletion; // @synthesize changeSecurityCodeCompletion=_changeSecurityCodeCompletion;
@property(copy, nonatomic) id /* CDUnknownBlockType */ passwordPromptCompletion; // @synthesize passwordPromptCompletion=_passwordPromptCompletion;
@property(copy, nonatomic) id /* CDUnknownBlockType */ completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) NSString *appleIDPasswordOrEquivalentToken; // @synthesize appleIDPasswordOrEquivalentToken=_appleIDPasswordOrEquivalentToken;
@property(copy, nonatomic) NSString *appleIDRawPassword; // @synthesize appleIDRawPassword=_appleIDRawPassword;
@property(copy, nonatomic) NSString *appleIDUsername; // @synthesize appleIDUsername=_appleIDUsername;
// - (void).cxx_destruct;
- (void)pinChoiceAlertDidChooseToUseDevicePasscode:(BOOL)arg1;
- (void)keychainSyncPhoneNumberController:(id)arg1 didCompleteWithPhoneNumber:(id)arg2 countryInfo:(id)arg3;
- (void)joinCircleAndEnableSecureBackupWithPhoneNumber:(id)arg1 countryInfo:(id)arg2;
- (void)_enableSecureBackupWithPhoneNumber:(id)arg1 countryInfo:(id)arg2;
- (void)keychainSyncController:(id)arg1 didFinishWithResult:(id)arg2 error:(id)arg3;
- (void)_autoVetSMSValidationWithToken:(id)arg1;
- (void)keychainSyncControllerCancel:(id)arg1;
- (void)_preSetupCancelledWithCurrentStatus;
- (void)_finishedWithStatus:(int)arg1 error:(id)arg2;
- (void)_callCompletionWithStatus:(int)arg1 error:(id)arg2;
- (void)handleCircleChangedNotification;
- (void)_stopCircleJoinAfterRecoveryTimer;
- (void)_startCircleJoinAfterRecoveryTimer;
- (void)_circleJoinAfterRecoveryTimerFired:(id)arg1;
- (void)_recoverWithSecurityCode:(id)arg1 verificationCode:(id)arg2;
- (void)joinCircleWithCompletion:(CDUnknownBlockType)arg1;
- (void)joinCircleAfterRecovery:(BOOL)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)_defaultKeychainViewSet;
- (void)dismissAppleSupportPane:(id)arg1;
- (void)showContactAppleSupportPane;
- (void)showNetworkReachabilityError;
- (void)showAlert:(id)arg1;
- (id)viewControllerForPresentingAlerts;
- (void)showController:(id)arg1;
- (void)_cleanup;
- (void)_peerApprovalFromRecoveryFlow;
- (void)_resetFromRecoveryFlow;
- (BOOL)_resetCircleAndDisableBackupWithError:(id )arg1;
- (void)showResetAcknowledgementIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)_showInvalidPhoneNumberAlertWithDigits:(id)arg1 countryInfo:(id)arg2;
- (void)_showGenericFlowErrorAlert;
- (void)_showGenericFlowErrorAlertWithDismissalHandler:(CDUnknownBlockType)arg1;
- (void)promptForDevicePasscodeChangeToPasscode:(id)arg1 overController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_changeToNewSecurityCode:(id)arg1 type:(int)arg2 smsTarget:(id)arg3 smsTargetCountryInfo:(id)arg4;
- (BOOL)_changeSecurityCode:(id)arg1 type:(int)arg2 smsTarget:(id)arg3 smsTargetCountryInfo:(id)arg4 username:(id)arg5 passwordOrEquivalentToken:(id)arg6 error:(id )arg7;
- (void)stopNavigationSpinner;
- (void)startNavigationSpinnerInViewController:(id)arg1;
- (id)preferencesApp;
- (void)setStagedSecurityCode:(id)arg1 type:(int)arg2;
- (void)showPinChoiceAlert;
- (void)_registerForCircleChangeNotificationsWithCompletion:(CDUnknownBlockType)arg1;
- (void)_registerForCircleChangeNotifications;
- (void)makeSettingsSetupControllerWithSpecifier:(id)arg1 parent:(id)arg2 initialController:(id)arg3;
- (BOOL)_errorRequiresPasswordPrompt:(id)arg1;
- (void)promptForPasswordIfCredentialsNotCachedOverController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)promptForPasswordIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)promptForPasswordIfNeededOverController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)promptForPasswordIfNeededForWritingOverController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)promptForPasswordOverController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (BOOL)_registerUserCredentialsName:(id)arg1 rawPassword:(id)arg2 error:(id )arg3;
- (void)setAppleIDRawPassword:(id)arg1 equivalentToken:(id)arg2;
- (void)_cleanupAppleIDCredentials;
- (id)navigationController;
@property(readonly, nonatomic, getter=isRunningInBuddy) BOOL runningInBuddy;
- (void)dealloc;
- (void)_deleteSafariAutoFillPasswords;
- (void)_disableKeychainSyncOverController:(id)arg1 deletingSafariPasswords:(BOOL)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)_disableCDPKeychainSyncOverController:(id)arg1 deletingSafariPasswords:(BOOL)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)_promptUserToDeleteSafariSavedContentWithCompletion:(CDUnknownBlockType)arg1;
- (void)disableKeychainSyncOverController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)showResetAndJoinFlowOverController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_showResetFlowOverController:(id)arg1 withEnableBackupText:(BOOL)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)showEnableFlowWithNavigationController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showChangeSecurityCodeFlowWithSpecifier:(id)arg1 overController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showRecoveryFlowWithNavigationController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showRecoveryFlowWithSpecifier:(id)arg1 overController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showEnableEscrowFlowWithSpecifier:(id)arg1 overController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showEnableSyncFlowWithSpecifier:(id)arg1 overController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

@end

