//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PSLanguage : NSObject
{
    NSString *_languageCode;
    NSString *_languageName;
    NSString *_localizedLanguageName;
}

+ (id)languageWithCode:(id)arg1 name:(id)arg2 localizedName:(id)arg3;
@property(retain, nonatomic) NSString *localizedLanguageName; // @synthesize localizedLanguageName=_localizedLanguageName;
@property(retain, nonatomic) NSString *languageName; // @synthesize languageName=_languageName;
@property(retain, nonatomic) NSString *languageCode; // @synthesize languageCode=_languageCode;
// - (void).cxx_destruct;
- (BOOL)displayNamesAreEqual;

@end

