//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//



@class NSArray, NSMutableArray, NSMutableString, UIColor;
@protocol PSPasscodeFieldDelegate;

@interface PSPasscodeField : UIView <UIKeyInput>
{
    NSMutableArray *_dotOutlineViews;
    NSMutableArray *_dotFullViews;
    NSMutableArray *_dashViews;
    NSMutableArray *_digitViews;
    NSMutableString *_stringValue;
    BOOL _securePasscodeEntry;
    BOOL _enabled;
    BOOL _shouldBecomeFirstResponderOnTap;
    id <PSPasscodeFieldDelegate> _delegate;
    NSUInteger _numberOfEntryFields;
    UIColor *_foregroundColor;
    long long _keyboardAppearance;
    NSArray *_fieldSpacing;
}

@property(nonatomic) BOOL shouldBecomeFirstResponderOnTap; // @synthesize shouldBecomeFirstResponderOnTap=_shouldBecomeFirstResponderOnTap;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSArray *fieldSpacing; // @synthesize fieldSpacing=_fieldSpacing;
@property(nonatomic) long long keyboardAppearance; // @synthesize keyboardAppearance=_keyboardAppearance;
@property(retain, nonatomic) UIColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property(nonatomic) BOOL securePasscodeEntry; // @synthesize securePasscodeEntry=_securePasscodeEntry;
@property(nonatomic) NSUInteger numberOfEntryFields; // @synthesize numberOfEntryFields=_numberOfEntryFields;
@property(nonatomic) __weak id <PSPasscodeFieldDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)deleteBackward;
@property(readonly, nonatomic) BOOL hasText;
- (void)insertText:(id)arg1;
@property(nonatomic) long long keyboardType;
- (BOOL)becomeFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)setStringValue:(id)arg1;
- (id)stringValue;
- (void)_delegateEnteredPasscode:(id)arg1;
- (void)layoutSubviews;
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
- (void)passcodeFieldTapped:(id)arg1;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (id)initWithNumberOfEntryFields:(NSUInteger)arg1;

@end

