//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Preferences/PSController-Protocol.h>

@class NSMutableSet, PSSpecifier, PSStackPushAnimationController;

@interface PSRootController : UINavigationController <PSController, UINavigationControllerDelegate>
{
    PSSpecifier *_specifier;
    NSMutableSet *_tasks;
    BOOL _deallocating;
    PSStackPushAnimationController *_stackAnimationController;
    NSUInteger _supportedOrientationsOverride;
}

+ (BOOL)processedBundle:(id)arg1 parentController:(id)arg2 parentSpecifier:(id)arg3 bundleControllers:(id )arg4 settings:(id)arg5;
+ (id)readPreferenceValue:(id)arg1;
+ (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
+ (void)writePreference:(id)arg1;
// - (void).cxx_destruct;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)_setNavigationBarHidden:(BOOL)arg1 edge:(NSUInteger)arg2 duration:(double)arg3;
- (void)pushControllersAsStack:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)setViewControllers:(id)arg1 animated:(BOOL)arg2;
- (id)popToRootViewControllerAnimated:(BOOL)arg1;
- (id)popToViewController:(id)arg1 animated:(BOOL)arg2;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)_delayedControllerReleaseAfterPop:(id)arg1;
- (BOOL)canBeShownFromSuspendedState;
- (void)didDismissFormSheetView;
- (void)willDismissFormSheetView;
- (void)didDismissPopupView;
- (void)willDismissPopupView;
- (id)aggregateDictionaryPath;
- (id)rootController;
- (void)setRootController:(id)arg1;
- (id)parentController;
- (void)dealloc;
- (BOOL)deallocating;
- (void)didWake;
- (void)didUnlock;
- (void)willUnlock;
- (void)didLock;
- (void)suspend;
- (NSUInteger)supportedInterfaceOrientations;
- (void)setSupportedInterfaceOrientations:(NSUInteger)arg1;
- (void)sendWillBecomeActive;
- (void)sendWillResignActive;
- (void)willBecomeActive;
- (void)willResignActive;
- (void)statusBarWillChangeHeight:(id)arg1;
- (void)showLeftButton:(id)arg1 withStyle:(long long)arg2 rightButton:(id)arg3 withStyle:(long long)arg4;
- (void)handleURL:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)handleURL:(id)arg1;
- (void)showController:(id)arg1 animate:(BOOL)arg2;
- (void)showController:(id)arg1;
- (void)pushController:(id)arg1 animate:(BOOL)arg2;
- (void)pushController:(id)arg1;
- (id)specifier;
- (void)setSpecifier:(id)arg1;
- (void)setParentController:(id)arg1;
- (void)statusBarWillAnimateByHeight:(double)arg1;
- (id)specifiers;
- (id)contentViewForTopController;
- (BOOL)busy;
- (void)taskFinished:(id)arg1;
- (void)addTask:(id)arg1;
- (BOOL)taskIsRunning:(id)arg1;
- (id)tasksDescription;
- (id)initWithTitle:(id)arg1 identifier:(id)arg2;
- (id)readPreferenceValue:(id)arg1;
- (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;

@end

