//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSSpecifierObserver-Protocol.h>

@class NSArray, PSSearchIndexOperation;
@protocol PSSpecifierDataSource;

@protocol PSSearchIndexOperationDelegate <PSSpecifierObserver>
- (void)searchIndexOperationDidFinish:(PSSearchIndexOperation *)arg1 searchEntries:(NSArray *)arg2;
- (void)searchIndexOperation:(PSSearchIndexOperation *)arg1 didFindSpecifierDataSource:(id <PSSpecifierDataSource>)arg2;

@optional
- (void)searchIndexOperationDidCancel:(PSSearchIndexOperation *)arg1;
@end

