//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>


@class NSMutableArray, NSMutableDictionary, NSMutableSet;

@interface PSSearchResults : NSObject <NSCopying>
{
    NSMutableArray *_sectionEntries;
    NSMutableSet *_explicitlyAddedSectionEntries;
    NSMutableDictionary *_entriesBySection;
    BOOL _needsSorting;
    BOOL _treatSectionEntriesAsRegularEntries;
    id /* CDUnknownBlockType */ _sectionComparator;
    id /* CDUnknownBlockType */ _entryComparator;
}

@property(nonatomic) BOOL treatSectionEntriesAsRegularEntries; // @synthesize treatSectionEntriesAsRegularEntries=_treatSectionEntriesAsRegularEntries;
@property(copy, nonatomic) id /* CDUnknownBlockType */ entryComparator; // @synthesize entryComparator=_entryComparator;
@property(copy, nonatomic) id /* CDUnknownBlockType */ sectionComparator; // @synthesize sectionComparator=_sectionComparator;
// - (void).cxx_destruct;
- (id)description;
- (id)resultsByMergingWithResults:(id)arg1;
- (void)mergeWithResults:(id)arg1;
- (void)sortResults;
- (id)allSectionEntries;
- (id)entryAtIndexPath:(id)arg1;
- (id)entriesInSectionAtIndex:(NSUInteger)arg1;
- (id)sectionEntryAtIndex:(NSUInteger)arg1;
- (NSUInteger)totalNumberOfEntries;
- (NSUInteger)numberOfEntriesInSectionAtIndex:(NSUInteger)arg1;
- (NSUInteger)numberOfSectionEntries;
- (NSUInteger)removeEntries:(id)arg1;
- (BOOL)removeEntry:(id)arg1;
- (void)addEntries:(id)arg1;
- (void)addEntry:(id)arg1;
// - (id)copyWithZone:(_NSZone )arg1;
- (id)_initForCopyWithSectionEntries:(id)arg1 entriesBySection:(id)arg2 explicitlyAddedSectionEntries:(id)arg3;
- (id)init;

@end

