//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSViewController.h>

@class NSString, UITextView;

@interface PSSoftwareUpdateLicenseViewController : PSViewController
{
    NSString *_licenseTextInfo;
    UITextView *_licenseTextView;
}

@property(retain, nonatomic) UITextView *licenseTextView; // @synthesize licenseTextView=_licenseTextView;
@property(retain, nonatomic) NSString *licenseTextInfo; // @synthesize licenseTextInfo=_licenseTextInfo;
// - (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)setLicenseText:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithLicense:(id)arg1;

@end

