//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>


@interface PSSpecifierAction : NSObject <NSCopying>
{
    id /* CDUnknownBlockType */ _getter;
    id /* CDUnknownBlockType */ _setter;
}

+ (id)actionWithTarget:(id)arg1 getterSelector:(SEL)arg2 setterSelector:(SEL)arg3;
+ (id)actionWithGetter:(CDUnknownBlockType)arg1 setter:(CDUnknownBlockType)arg2;
+ (id)actionWithBoolDetailClass:(Class)arg1;
@property(copy, nonatomic) id /* CDUnknownBlockType */ setter; // @synthesize setter=_setter;
@property(copy, nonatomic) id /* CDUnknownBlockType */ getter; // @synthesize getter=_getter;
// - (void).cxx_destruct;
// - (id)copyWithZone:(_NSZone )arg1;

@end

