//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSTableCell.h>

@class UIActivityIndicatorView;

@interface PSSpinnerTableCell : PSTableCell
{
    UIActivityIndicatorView *_spinner;
}

// - (void).cxx_destruct;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

