//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Preferences/PSKeyboardNavigationSearchResultsController-Protocol.h>

@class NSArray, NSMutableArray, NSMutableDictionary;
@protocol PSSpotlightSearchResultsControllerDelegate;

@interface PSSpotlightSearchResultsController : UITableViewController <PSKeyboardNavigationSearchResultsController>
{
    NSMutableDictionary *_iconViewMap;
    NSMutableArray *_reusableIconViews;
    long long _deviceOrientation;
    double originalInset;
    NSArray *_results;
    id <PSSpotlightSearchResultsControllerDelegate> _delegate;
    NSMutableArray *_tableData;
}

@property(retain, nonatomic) NSMutableArray *tableData; // @synthesize tableData=_tableData;
@property(nonatomic) __weak id <PSSpotlightSearchResultsControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *results; // @synthesize results=_results;
// - (void).cxx_destruct;
- (void)showSelectedSearchResult;
- (void)_selectIndexPath:(id)arg1;
- (void)selectNextSearchResult;
- (void)selectPreviousSearchResult;
- (void)searchQueryCompleted;
- (void)searchQueryFoundItems:(id)arg1;
- (void)searchQueryStarted;
- (void)tableViewDidFinishReload:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_updateIconViews:(BOOL)arg1;
- (void)_removeIconViewForSection:(id)arg1;
- (void)viewDidLayoutSubviews;
- (double)iconWidth;
- (id)_itemForIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;
- (id)init;

@end

