//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>


@class NSArray, NSMutableArray, PSSpecifierGroupIndex, PSSpecifierUpdateContext;

@interface PSSpecifierUpdates : NSObject <NSCopying>
{
    NSMutableArray *_currentSpecifiers;
    NSMutableArray *_updates;
    PSSpecifierGroupIndex *_groupIndex;
    BOOL _wantsDebugCallbacks;
    NSArray *_originalSpecifiers;
    PSSpecifierUpdateContext *_context;
}

+ (id)updatesByDiffingSpecifiers:(id)arg1 withSpecifiers:(id)arg2 changedBlock:(CDUnknownBlockType)arg3;
+ (void)_assertSpecifierIDsAreUnique:(id)arg1;
+ (BOOL)_wantsDebugCallbacks;
+ (Class)_groupIndexClass;
+ (id)updatesWithSpecifiers:(id)arg1;
@property(copy, nonatomic) PSSpecifierUpdateContext *context; // @synthesize context=_context;
@property(readonly, copy, nonatomic) NSArray *originalSpecifiers; // @synthesize originalSpecifiers=_originalSpecifiers;
// - (void).cxx_destruct;
- (id)specifiersAfterApplyingUpdatesToIndex:(NSUInteger)arg1;
- (id)stepByStepDescription;
- (id)description;
- (BOOL)swapSpecifier:(id)arg1 withSpecifier:(id)arg2;
- (BOOL)swapSpecifierAtIndex:(NSUInteger)arg1 withSpecifierAtIndex:(NSUInteger)arg2;
- (BOOL)moveSpecifier:(id)arg1 toIndex:(NSUInteger)arg2;
- (BOOL)moveSpecifierAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (BOOL)moveSpecifierAtIndex:(NSUInteger)arg1 toIndex:(NSUInteger)arg2;
- (BOOL)reloadSpecifiersInRange:(NSRange *)arg1;
- (BOOL)reloadSpecifierAtIndexPath:(id)arg1;
- (BOOL)reloadSpecifierAtIndex:(NSUInteger)arg1;
- (BOOL)reloadSpecifiersWithIDs:(id)arg1;
- (BOOL)reloadSpecifierWithID:(id)arg1;
- (BOOL)reloadSpecifiersInGroupWithID:(id)arg1;
- (BOOL)reloadSpecifiersInGroup:(id)arg1;
- (BOOL)reloadSpecifiersInGroupAtGroupIndex:(NSUInteger)arg1;
- (BOOL)reloadSpecifiers:(id)arg1;
- (BOOL)reloadSpecifier:(id)arg1;
- (BOOL)removeSpecifiersInGroupWithID:(id)arg1;
- (BOOL)removeSpecifiersInGroup:(id)arg1;
- (BOOL)removeSpecifiersInGroupAtGroupIndex:(NSUInteger)arg1;
- (BOOL)removeSpecifierAtIndexPath:(id)arg1;
- (BOOL)removeSpecifiersInRange:(NSRange *)arg1;
- (BOOL)_removeOneSpecifierOnlyAtIndex:(NSUInteger)arg1;
- (BOOL)removeSpecifierAtIndex:(NSUInteger)arg1;
- (BOOL)removeSpecifiersWithIDs:(id)arg1;
- (BOOL)removeSpecifierWithID:(id)arg1;
- (BOOL)removeSpecifiers:(id)arg1;
- (BOOL)removeSpecifier:(id)arg1;
- (BOOL)appendSpecifiers:(id)arg1 toGroupWithID:(id)arg2;
- (BOOL)appendSpecifier:(id)arg1 toGroupWithID:(id)arg2;
- (BOOL)appendSpecifiers:(id)arg1 toGroup:(id)arg2;
- (BOOL)appendSpecifier:(id)arg1 toGroup:(id)arg2;
- (BOOL)appendSpecifiers:(id)arg1 toGroupAtGroupIndex:(NSUInteger)arg2;
- (BOOL)appendSpecifier:(id)arg1 toGroupAtGroupIndex:(NSUInteger)arg2;
- (BOOL)appendSpecifiers:(id)arg1;
- (BOOL)appendSpecifier:(id)arg1;
- (BOOL)insertContiguousSpecifiers:(id)arg1 afterSpecifierWithID:(id)arg2;
- (BOOL)insertContiguousSpecifiers:(id)arg1 afterSpecifier:(id)arg2;
- (BOOL)insertContiguousSpecifiers:(id)arg1 atIndex:(NSUInteger)arg2;
- (BOOL)insertSpecifier:(id)arg1 afterSpecifierWithID:(id)arg2;
- (BOOL)insertSpecifier:(id)arg1 afterSpecifier:(id)arg2;
- (BOOL)insertSpecifier:(id)arg1 atIndexPath:(id)arg2;
- (BOOL)insertSpecifier:(id)arg1 atIndex:(NSUInteger)arg2;
- (BOOL)_addAndApplyOperation:(id)arg1;
- (void)_didApplyOperation:(id)arg1;
- (void)_operationFailed:(id)arg1 reason:(id)arg2;
- (BOOL)_enumerateArrayWithConjuctionalResult:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)specifierForID:(id)arg1;
- (NSUInteger)indexOfSpecifierWithID:(id)arg1;
- (NSUInteger)indexOfSpecifier:(id)arg1;
- (void)enumerateUpdatesUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSArray *updates;
@property(readonly, copy, nonatomic) NSArray *currentSpecifiers;
@property(readonly, copy, nonatomic) PSSpecifierGroupIndex *groupIndex;
- (id)_groupIndexCreatingIfNecessary;
// - (id)copyWithZone:(_NSZone )arg1;
- (id)_initForCopyWithOriginalSpecifiers:(id)arg1 currentSpecifiers:(id)arg2 updates:(id)arg3;
- (id)initWithSpecifiers:(id)arg1 applyUpdates:(id)arg2;
- (id)initWithSpecifiers:(id)arg1;
- (id)init;
- (id)_init;

@end

