//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSControlTableCell.h>

@class UIActivityIndicatorView;

@interface PSSwitchTableCell : PSControlTableCell
{
    UIActivityIndicatorView *_activityIndicator;
}

// - (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setValue:(id)arg1;
- (void)reloadWithSpecifier:(id)arg1 animated:(BOOL)arg2;
- (id)controlValue;
@property(nonatomic) BOOL loading;
- (void)setCellEnabled:(BOOL)arg1;
- (BOOL)canReload;
- (id)newControl;
- (void)prepareForReuse;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

