//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, PSPhotosPolicyController;

@interface PSSystemPolicyForApp : NSObject
{
    NSUInteger _policyOptions;
    BOOL _forcePolicyOptions;
    PSPhotosPolicyController *_photosPrivacyController;
    NSString *_bundleIdentifier;
}

+ (BOOL)isServiceRestricted:(id)arg1;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
// - (void).cxx_destruct;
- (id)preferredLanguage:(id)arg1;
- (id)preferredLanguageSpecifier;
- (id)documentSource:(id)arg1;
- (id)documentsSpecifier;
- (id)privacyAccessForSpecifier:(id)arg1;
// - (id)_privacyAccessForService:(struct __CFString )arg1;
- (void)setPrivacyAccess:(id)arg1 forSpecifier:(id)arg2;
// - (struct __CFBundle )copyTCCBundleForService:(struct __CFString )arg1;
// - (id)privacySpecifierForService:(struct __CFString )arg1;
- (id)privacySpecifiers;
- (id)authLevelStringForStatus:(NSUInteger)arg1;
- (id)locationStatus:(id)arg1;
- (BOOL)_isLocationServicesRestricted;
- (id)locationServicesSpecifier;
- (id)photosServicesSpecifier;
- (id)isBackgroundRefreshEnabled:(id)arg1;
- (void)setBackgroundRefreshEnabled:(id)arg1 forSpecifier:(id)arg2;
- (BOOL)_isBackgroundAppRefreshAllowed;
- (BOOL)_supportsBackgroundAppRefresh;
- (id)backgroundAppRefreshSpecifier;
- (id)wirelessDataSpecifierWithAppName:(id)arg1;
- (BOOL)_isWirelessDataRestricted;
- (BOOL)isCellularBundleID:(id)arg1;
- (id)dataUsageWorkspaceInfo;
- (id)assistantAndSearchSpecifiers;
- (id)notificationSpecifier;
- (id)specifiersForPolicyOptions:(NSUInteger)arg1 force:(BOOL)arg2;
- (id)specifiers;
- (id)initWithBundleIdentifier:(id)arg1;

@end

