//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSTableCell.h>


@class PSTextView;

@interface PSTextViewTableCell : PSTableCell <UITextContentViewDelegate>
{
    PSTextView *_textView;
}

// - (void).cxx_destruct;
- (void)drawTitleInRect:(CGRect)arg1 selected:(BOOL)arg2;
@property(retain, nonatomic) PSTextView *textView;
- (BOOL)resignFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)textContentViewDidEndEditing:(id)arg1;
- (void)_adjustTextView:(id)arg1 updateTable:(BOOL)arg2 withSpecifier:(id)arg3;
- (void)layoutSubviews;
- (void)cellRemovedFromView;
- (void)textContentViewDidChange:(id)arg1;
- (void)setValue:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

