//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class PSTextViewTableCell;

@interface PSTextView : UITextContentView
{
    PSTextViewTableCell *_cell;
}

// - (void).cxx_destruct;
- (void)setCell:(id)arg1;

@end

