//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSSpecifierController.h>

@class PSSystemPolicyForApp;

@interface PSThirdPartyAppController : PSSpecifierController
{
    PSSystemPolicyForApp *_systemPolicy;
}

@property(retain, nonatomic) PSSystemPolicyForApp *systemPolicy; // @synthesize systemPolicy=_systemPolicy;
// - (void).cxx_destruct;
- (id)bundle;
- (id)loadSpecifiers;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
- (void)postThirdPartySettingDidChangeNotificationForSpecifier:(id)arg1;
- (void)showPrivacyControllerForSpecifier:(id)arg1;
- (void)_setToggleSwitchSpecifierValue:(id)arg1 specifier:(id)arg2;
- (id)_readToggleSwitchSpecifierValue:(id)arg1;
- (id)_valueFromUIValue:(id)arg1 specifier:(id)arg2;
- (id)_uiValueFromValue:(id)arg1 specifier:(id)arg2;

@end

