//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSEditableListController.h>

@interface PSUsageBundleDetailController : PSEditableListController
{
}

+ (void)setupSpecifier:(id)arg1 forMediaGroups:(id)arg2;
+ (id)mediaGroups;
- (id)specifiers;
- (id)sizeForSpecifier:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)updateSizesAfterDeletingSize:(float)arg1 shouldPop:(BOOL)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)size:(id)arg1;
- (BOOL)canBeShownFromSuspendedState;
- (void)loadView;

@end

