//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSLayoutConstraint, NSString, NTKCFaceContainerView, UILabel, UIView;

@interface _NTKCCFacesCollectionCell : UICollectionViewCell
{
    UILabel *_nameLabel;
    NSLayoutConstraint *_faceNameFirstBaselineToFaceConstraint;
    NTKCFaceContainerView *_faceContainerView;
}

+ (id)luxoReuseIdentifier;
+ (id)nonLuxoReuseIdentifier;
+ (id)reuseIdentifier;
@property(retain, nonatomic) NTKCFaceContainerView *faceContainerView; // @synthesize faceContainerView=_faceContainerView;
// - (void).cxx_destruct;
- (void)_highlight;
- (void)setSelected:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1;
@property(nonatomic) BOOL active;
@property(copy, nonatomic) NSString *name;
@property(retain, nonatomic) UIView *faceView;
@property(nonatomic) CGSize faceSize;
- (void)_fontSizeDidChange;
- (void)dealloc;
- (id)initWithFrame:(CGRect)arg1;

@end

