//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSViewController.h>

#import <NanoTimeKitCompanion/NTKFaceObserver-Protocol.h>
#import <NanoTimeKitCompanion/NTKFaceCollectionObserver-Protocol.h>

@class NSMutableArray, NTKPersistentFaceCollection, UITableView;

@interface NTKCCLibraryListViewController : PSViewController <UITableViewDelegate, UITableViewDataSource, NTKFaceCollectionObserver, NTKFaceObserver>
{
    UITableView *_tableView;
    NTKPersistentFaceCollection *_library;
    NSMutableArray *_faceVCs;
}

@property(retain, nonatomic) NSMutableArray *faceVCs; // @synthesize faceVCs=_faceVCs;
@property(retain, nonatomic) NTKPersistentFaceCollection *library; // @synthesize library=_library;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
// - (void).cxx_destruct;
- (void)faceConfigurationDidChange:(id)arg1;
- (void)faceCollectionDidLoad:(id)arg1;
- (void)faceCollectionDidReorderFaces:(id)arg1;
- (void)faceCollection:(id)arg1 didRemoveFace:(id)arg2 atIndex:(NSUInteger)arg3;
- (void)faceCollection:(id)arg1 didAddFace:(id)arg2 atIndex:(NSUInteger)arg3;
- (void)faceCollection:(id)arg1 didSelectFace:(id)arg2 atIndex:(NSUInteger)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didCancelReorderingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndReorderingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginReorderingRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)_removeViewControllerForFace:(id)arg1;
- (id)_viewControllerForFace:(id)arg1;
- (void)_updateTitle;
- (void)_reloadFaces;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

