//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, NTKCFaceContainerView, UILabel, UIStackView, UIView;

@interface NTKCCLibraryListCell : UITableViewCell
{
    NTKCFaceContainerView *_faceContainer;
    UILabel *_name;
    UILabel *_subtitle;
    UIStackView *_horizontalStack;
    UIStackView *_verticalStack;
    BOOL _currentFace;
}

+ (id)reuseIdentifier;
@property(nonatomic) BOOL currentFace; // @synthesize currentFace=_currentFace;
// - (void).cxx_destruct;
- (void)_fontSizeDidChange;
- (void)layoutSubviews;
@property(retain, nonatomic) UIView *faceView;
@property(retain, nonatomic) NSString *faceName;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

