#!/bin/sh

echo $DGEN_DEBUG

source $DRAGONBUILD/internal/dragoncolors

eval $(DGEN_DEBUG=${DGEN_DEBUG} python3 $DRAGONBUILD/DragonGen/DragonGen.py)

# echo $?
# echo "e $DRAGON_DPKG"

export TWEAK_NAME=$package_name
export INSTALL_CMD=$install_command
