#!/bin/sh

theos=0

echo $DGEN_DEBUG | grep "1" > /dev/null && echo "DragonGen Debug Enabled"

source $DRAGONBUILD/internal/dragoncolors

echo $simtarg | grep "1" > /dev/null && echo -e "${GenColor}[DragonGen]${BoldColor} Targeting Simulator + simject${NC}"

eval $(DGEN_DEBUG=${DGEN_DEBUG} TARG_SIM=${simtarg} python3 $DRAGONBUILD/DragonGen/DragonGen.py)

if [ $theos == 1 ]; then
  echo -e "${GenColor}[DragonGen]${BoldColor} Building from Theos Makefile${NC}"
fi

export TWEAK_NAME=$package_name
export INSTALL_CMD=$install_command
