#!/bin/sh

source $DRAGONBUILD/internal/dragoncolors

echo -e "${GenColor}[DragonGen]${NC} Loading DragonMake"

generatedLIBS=$(echo "$LIBS" | sed 's/\//\\\//g')
generatedFRAMEWORKS=$(echo $FRAMEWORKS | sed 's/\//\\\//g')
theosEscaped=$(echo "$THEOS" | sed 's/\//\\\//g')
filesEscaped=$(echo "$TWEAK_FILES" | sed 's/\//\\\//g')
dragonEscaped=$(echo "$DRAGONBUILD" | sed 's/\//\\\//g')
cfesc=$(echo "$CFLAGS" | sed 's/\//\\\//g')
xmcName=$(echo "${LOGOS_FILE}" | sed 's/.x/.m/g')

genLogos=""
genComp=""
genLink="build \$dsymtarget : link "

set -f
subsbs=(${TWEAK_FILES})
set +f 
for i in "${subsbs[@]}"; do
    e="${i}.o"
    genComp+="build \$builddir/${e} : compile ${i}ƒƒ"
    genLink+="\$builddir/${e} "
done

set -f
subsbsx=(${LOGOS_FILE})
set +f
for i in "${subsbsx[@]}"; do
    e=$(echo "${i}" | sed 's/\.x/\.m/g')
    genLogos+="build \$builddir/${e} : logos ${i}ƒƒ"
    f="${e}.o"
    genComp+="build \$builddir/${f} : compile \$builddir/${e}ƒƒ"
    genLink+="\$builddir/${f} "
done

echo -e "${GenColor}[DragonGen]${NC} Generating input files"

gencompEscaped=$(echo "$genComp" | sed 's/\//\\\//g')
genlinkEscaped=$(echo "$genLink" | sed 's/\//\\\//g')
genlogosEscaped=$(echo "$genLogos" | sed 's/\//\\\//g')

echo -e "${GenColor}[DragonGen]${NC} Writing build.ninja"

sed -e "s/\%%name%%/${TWEAK_NAME}/" -e "s/\%%dragonbuild%%/${dragonEscaped}/" -e "s/%%files%%/${filesEscaped}/" \
-e "s/%%libs%%/${generatedLIBS}/" -e "s/%%frameworks%%/${generatedFRAMEWORKS}/" -e "s/%%theos%%/${theosEscaped}/" \
-e "s/%%xmcname%%/${xmcName}/" -e "s/%%gencomp%%/${gencompEscaped}/" -e "s/%%genlink%%/${genlinkEscaped}/" \
-e "s/%%cflags%%/${cfesc}/" -e "s/%%archs%%/${ARCHS}/" -e "s/%%minios%%/${MINIOS}/" -e "s/%%logosgen%%/${genlogosEscaped}/" \
$DRAGONBUILD/NinjaTemplates/${TWEAK_TYPE}Template.ninja > .dragon/ninja/build.ninja
# bad hack
tr 'ƒ' '\n' < .dragon/ninja/build.ninja > .dragon/ninja/bt
mv .dragon/ninja/bt .dragon/ninja/build.ninja