//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _SBFloatingDockPlatterMetrics : NSObject
{
    double _continuousCornerRadius;
    double _shadowRadius;
    double _shadowYOffset;
    CGRect _bounds;
}

@property(readonly, nonatomic) double shadowYOffset; // @synthesize shadowYOffset=_shadowYOffset;
@property(readonly, nonatomic) double shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(readonly, nonatomic) double continuousCornerRadius; // @synthesize continuousCornerRadius=_continuousCornerRadius;
@property(readonly, nonatomic) CGRect bounds; // @synthesize bounds=_bounds;
- (id)initWithBounds:(CGRect)arg1 continuousCornerRadius:(double)arg2 shadowRadius:(double)arg3 shadowYOffset:(double)arg4;

@end

