//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSSet.h>

@interface NSSet (SBHAdditions)
- (id)sbh_map:(id /* CDUnknownBlockType */)arg1;
- (id)sbh_diffWithSet:(id)arg1;
@end

