//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBFolderControllerConfiguration.h>

@interface SBFloatyFolderControllerConfiguration : SBFolderControllerConfiguration
{
    BOOL _displaysMultipleIconListsInLandscapeOrientation;
    NSUInteger _backgroundEffect;
}

@property(nonatomic) BOOL displaysMultipleIconListsInLandscapeOrientation; // @synthesize displaysMultipleIconListsInLandscapeOrientation=_displaysMultipleIconListsInLandscapeOrientation;
@property(nonatomic) NSUInteger backgroundEffect; // @synthesize backgroundEffect=_backgroundEffect;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)initWithConfiguration:(id)arg1;

@end

