//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>

@class NSString, SBFolder, SBFolderControllerAnimationContext, SBFolderIconImageCache, SBHIconImageCache, SBIconPageIndicatorImageSetCache, UIView, _UILegibilitySettings;
@protocol SBFolderControllerDelegate, SBIconListLayoutProvider, SBIconViewProviding, SBNestingViewControllerDelegate;

@interface SBFolderControllerConfiguration : NSObject <NSCopying, BSDescriptionProviding>
{
    SBFolder *_folder;
    long long _orientation;
    NSUInteger _allowedOrientations;
    id <SBIconListLayoutProvider> _listLayoutProvider;
    id <SBIconViewProviding> _iconViewProvider;
    id <SBNestingViewControllerDelegate> _delegate;
    id <SBFolderControllerDelegate> _folderDelegate;
    _UILegibilitySettings *_legibilitySettings;
    SBFolderIconImageCache *_folderIconImageCache;
    SBHIconImageCache *_iconImageCache;
    SBIconPageIndicatorImageSetCache *_iconPageIndicatorImageSetCache;
    SBFolderControllerAnimationContext *_animationContext;
    UIView *_headerView;
    double _headerHeight;
    NSString *_originatingIconLocation;
    NSUInteger _userInterfaceLayoutDirectionHandling;
    CGRect _initialViewFrame;
}

@property(nonatomic) CGRect initialViewFrame; // @synthesize initialViewFrame=_initialViewFrame;
@property(nonatomic) NSUInteger userInterfaceLayoutDirectionHandling; // @synthesize userInterfaceLayoutDirectionHandling=_userInterfaceLayoutDirectionHandling;
@property(copy, nonatomic) NSString *originatingIconLocation; // @synthesize originatingIconLocation=_originatingIconLocation;
@property(nonatomic) double headerHeight; // @synthesize headerHeight=_headerHeight;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) SBFolderControllerAnimationContext *animationContext; // @synthesize animationContext=_animationContext;
@property(retain, nonatomic) SBIconPageIndicatorImageSetCache *iconPageIndicatorImageSetCache; // @synthesize iconPageIndicatorImageSetCache=_iconPageIndicatorImageSetCache;
@property(retain, nonatomic) SBHIconImageCache *iconImageCache; // @synthesize iconImageCache=_iconImageCache;
@property(retain, nonatomic) SBFolderIconImageCache *folderIconImageCache; // @synthesize folderIconImageCache=_folderIconImageCache;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) __weak id <SBFolderControllerDelegate> folderDelegate; // @synthesize folderDelegate=_folderDelegate;
@property(nonatomic) __weak id <SBNestingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <SBIconViewProviding> iconViewProvider; // @synthesize iconViewProvider=_iconViewProvider;
@property(retain, nonatomic) id <SBIconListLayoutProvider> listLayoutProvider; // @synthesize listLayoutProvider=_listLayoutProvider;
@property(nonatomic) NSUInteger allowedOrientations; // @synthesize allowedOrientations=_allowedOrientations;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) SBFolder *folder; // @synthesize folder=_folder;
// - (void).cxx_destruct;
// - (id)copyWithZone:(_NSZone )arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithConfiguration:(id)arg1;
- (id)init;

@end

