//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>
#import <SpringBoardHome/SBIconIndexMutableListObserver-Protocol.h>
#import <SpringBoardHome/SBIconIndexNode-Protocol.h>
#import <SpringBoardHome/SBIconListModelObserver-Protocol.h>

@class NSArray, NSCountedSet, NSHashTable, NSMutableSet, NSString, SBFolderIcon, SBIconIndexMutableList;

@interface SBFolder : NSObject <SBIconIndexNode, SBIconIndexMutableListObserver, SBIconListModelObserver, BSDescriptionProviding>
{
    NSHashTable *_nodeObservers;
    NSHashTable *_folderObservers;
    SBIconIndexMutableList *_lists;
    BOOL _displayNameDirty;
    BOOL _open;
    BOOL _cancelable;
    NSMutableSet *_addedIcons;
    NSMutableSet *_removedIcons;
    NSCountedSet *_coalesceChangesRequests;
    NSString *_nodeIdentifier;
    NSString *_uniqueIdentifier;
    NSString *_displayName;
    NSString *_defaultDisplayName;
    SBFolderIcon *_icon;
    NSUInteger _maxListCount;
    NSUInteger _maxIconCountInLists;
    NSUInteger _maxIconCountInFirstList;
    NSUInteger _requiredTrailingEmptyListCount;
}

+ (BOOL)isFolderNodeIdentifier:(id)arg1;
+ (BOOL)isRootFolderClass;
@property(nonatomic) NSUInteger requiredTrailingEmptyListCount; // @synthesize requiredTrailingEmptyListCount=_requiredTrailingEmptyListCount;
@property(readonly, nonatomic) NSUInteger maxIconCountInFirstList; // @synthesize maxIconCountInFirstList=_maxIconCountInFirstList;
@property(readonly, nonatomic) NSUInteger maxIconCountInLists; // @synthesize maxIconCountInLists=_maxIconCountInLists;
@property(readonly, nonatomic) NSUInteger maxListCount; // @synthesize maxListCount=_maxListCount;
@property(nonatomic, getter=isCancelable) BOOL cancelable; // @synthesize cancelable=_cancelable;
@property(nonatomic) __weak SBFolderIcon *icon; // @synthesize icon=_icon;
@property(nonatomic, getter=isOpen) BOOL open; // @synthesize open=_open;
@property(copy, nonatomic) NSString *defaultDisplayName; // @synthesize defaultDisplayName=_defaultDisplayName;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, copy, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
// - (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (void)iconList:(id)arg1 didMoveIcon:(id)arg2;
- (void)iconList:(id)arg1 didRemoveIcon:(id)arg2;
- (void)iconList:(id)arg1 didReplaceIcon:(id)arg2 withIcon:(id)arg3;
- (void)iconList:(id)arg1 didAddIcon:(id)arg2;
- (void)listDidMoveNodes:(id)arg1;
- (void)list:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)list:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
@property(readonly, copy) NSString *description;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)addNodeObserver:(id)arg1;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(NSUInteger)arg2;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)arg1;
- (id)nodeIdentifier;
- (BOOL)canBounceIcon:(id)arg1;
- (void)appendRecursiveDescriptionToString:(id)arg1 prefixPath:(id)arg2;
@property(readonly, copy, nonatomic) NSString *recursiveDescription;
@property(readonly, nonatomic) __weak SBFolder *rootFolder;
@property(readonly, nonatomic) SBFolder *parentFolder;
- (void)didRemoveFolder:(id)arg1;
- (void)didAddFolder:(id)arg1;
- (void)sort;
- (void)enumerateAllIconsWithBaseIndexPath:(id)arg1 options:(NSUInteger)arg2 usingBlock:(id /* CDUnknownBlockType */)arg3;
- (void)enumerateAllIconsWithOptions:(NSUInteger)arg1 usingBlock:(id /* CDUnknownBlockType */)arg2;
- (void)enumerateAllIconsUsingBlock:(id /* CDUnknownBlockType */)arg1;
- (void)stopCoalescingContentChangesForRequestID:(id)arg1 forceReload:(BOOL)arg2;
- (void)stopCoalescingContentChangesForRequestID:(id)arg1;
- (void)startCoalescingContentChangesWithRequestID:(id)arg1;
- (BOOL)_isCoalescingContentChanges;
- (id)firstFolderWithDefaultDisplayName:(id)arg1;
- (id)firstFolderWithDisplayName:(id)arg1;
- (id)folderContainingIndexPath:(id)arg1 relativeIndexPath:(id )arg2;
- (id)iconAtIndexPath:(id)arg1;
- (id)indexPathForFolder:(id)arg1;
- (id)indexPathsForIconsPassingTest:(id /* CDUnknownBlockType */)arg1;
- (id)indexPathForIconWithOptions:(NSUInteger)arg1 passingTest:(id /* CDUnknownBlockType */)arg2;
- (id)indexPathForIconPassingTest:(id /* CDUnknownBlockType */)arg1;
- (id)indexPathForIconWithIdentifier:(id)arg1 includingPlaceholders:(BOOL)arg2;
- (id)indexPathForIconWithIdentifier:(id)arg1;
- (id)indexPathForIcon:(id)arg1 includingPlaceholders:(BOOL)arg2;
- (id)indexPathForIcon:(id)arg1;
- (id)indexPathForNodeIdentifier:(id)arg1;
- (id)listsContainingLeafIconWithIdentifier:(id)arg1;
- (id)listsContainingIcon:(id)arg1;
- (BOOL)containsIcon:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *iconsInLists;
@property(readonly, copy, nonatomic) NSArray *icons;
- (id)folderIcons;
- (id)leafIcons;
- (id)allIcons;
- (void)addIconsOfClass:(Class)arg1 toSet:(id)arg2;
- (id)iconsOfClass:(Class)arg1;
- (void)removeIcon:(id)arg1 options:(NSUInteger)arg2;
- (id)indexPathForFirstFreeSlotStartingAtList:(id)arg1 avoidingFirstList:(BOOL)arg2;
- (id)indexPathForFirstFreeSlotAvoidingFirstList:(BOOL)arg1;
- (BOOL)canAddIconCount:(NSUInteger)arg1 startingAtList:(id)arg2;
- (BOOL)canAddIconCount:(NSUInteger)arg1;
- (BOOL)canAddIcon;
- (void)addIcons:(id)arg1;
- (id)addIcon:(id)arg1;
- (void)removeIconAtIndexPath:(id)arg1 options:(NSUInteger)arg2;
- (void)replaceIcon:(id)arg1 withIcon:(id)arg2;
- (id)insertIcon:(id)arg1 atIndexPath:(id )arg2 options:(NSUInteger)arg3;
- (id)placeIcon:(id)arg1 atIndexPath:(id)arg2;
- (void)removeAllLists;
- (NSUInteger)indexOfList:(id)arg1;
- (id)listAtIndex:(NSUInteger)arg1;
- (id)_createNewListWithIcon:(id)arg1;
- (void)markIconStateClean;
- (BOOL)isIconStateDirty;
- (BOOL)isValidPageIndex:(NSUInteger)arg1;
- (void)removeListAtIndex:(NSUInteger)arg1;
- (void)removeList:(id)arg1;
- (id)addListWithIcon:(id)arg1;
- (id)insertEmptyListAtIndex:(NSUInteger)arg1;
- (id)addEmptyList;
- (void)_removeLists:(id)arg1;
- (void)_setLists:(id)arg1;
- (void)_didAddList:(id)arg1;
- (void)_addList:(id)arg1;
- (void)_insertList:(id)arg1 atIndex:(NSUInteger)arg2;
@property(readonly, nonatomic) NSUInteger trailingEmptyListCount;
- (void)ensureTrailingEmptyLists;
- (BOOL)_compactLists;
- (BOOL)compactLists;
- (id)_listsForCompaction;
@property(readonly, nonatomic) BOOL canEditDisplayName;
@property(readonly, nonatomic) BOOL canRemoveIcons;
@property(readonly, nonatomic) BOOL shouldRemoveWhenEmpty;
@property(readonly, nonatomic, getter=isFull) BOOL full;
@property(readonly, nonatomic, getter=isEmpty) BOOL empty;
@property(readonly, nonatomic) NSUInteger listCount;
@property(readonly, copy, nonatomic) NSArray *lists;
- (void)removeFolderObserver:(id)arg1;
- (void)addFolderObserver:(id)arg1;
- (id)init;
- (id)initWithUniqueIdentifier:(id)arg1 displayName:(id)arg2 maxListCount:(NSUInteger)arg3 maxIconCountInLists:(NSUInteger)arg4;
- (id)initWithDisplayName:(id)arg1 maxListCount:(NSUInteger)arg2 maxIconCountInLists:(NSUInteger)arg3;
@property(readonly, nonatomic) Class listModelClass;
- (BOOL)isRootFolder;

@end

