//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBIcon.h>

#import <SpringBoardHome/SBFolderObserver-Protocol.h>
#import <SpringBoardHome/SBIconIndexNodeObserver-Protocol.h>
#import <SpringBoardHome/SBIconObserver-Protocol.h>

@class NSHashTable, NSMutableSet, NSString, SBFolder;

@interface SBFolderIcon : SBIcon <SBFolderObserver, SBIconObserver, SBIconIndexNodeObserver>
{
    NSHashTable *_nodeObservers;
    NSMutableSet *_finishedDownloadIdentifiers;
    long long _progressState;
    double _progressPercent;
    struct __CFRunLoopObserver _updateIconRunLoopObserver;
    SBFolder *_folder;
}

+ (BOOL)hasIconImage;
// - (void).cxx_destruct;
// - (id)copyWithZone:(_NSZone )arg1;
@property(readonly, nonatomic) SBFolder *folder; // @synthesize folder=_folder;
- (BOOL)isFolderIcon;
- (void)folder:(id)arg1 didReplaceIcon:(id)arg2 withIcon:(id)arg3;
- (void)folder:(id)arg1 didAddIcons:(id)arg2 removedIcons:(id)arg3;
- (void)folder:(id)arg1 didRemoveLists:(id)arg2 atIndexes:(id)arg3;
- (void)folder:(id)arg1 didAddList:(id)arg2;
- (void)nodeDidMoveContainedNodes:(id)arg1;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)addNodeObserver:(id)arg1;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(NSUInteger)arg2;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)arg1;
- (id)nodeIdentifier;
- (void)removeChild:(id)arg1;
- (id)children;
- (void)iconLaunchEnabledDidChange:(id)arg1;
- (void)iconAccessoriesDidUpdate:(id)arg1;
- (void)iconImageDidUpdate:(id)arg1;
- (id)iconAtListIndex:(NSUInteger)arg1 iconIndex:(NSUInteger)arg2;
- (NSUInteger)gridCellIndexForIconIndex:(NSUInteger)arg1;
- (NSUInteger)listIndexForContainedIcon:(id)arg1;
- (BOOL)canBeAddedToMultiItemDrag;
- (id)leafIconsWithBadgesSortedByImportance;
- (void)ancestryDidChange;
- (void)rootFolderDelegateDidChange:(id)arg1;
- (void)_containedIconLaunchEnabledDidUpdate:(id)arg1;
- (void)_containedIconAccessoriesDidUpdate:(id)arg1;
- (void)_containedIconImageChanged:(id)arg1;
- (void)noteContainedIcon:(id)arg1 replacedIcon:(id)arg2;
- (void)noteContainedIconsAdded:(id)arg1 removed:(id)arg2;
- (void)_adjustForIconsAdded:(id)arg1 removed:(id)arg2;
- (double)progressPercent;
- (BOOL)shouldAnimateProgress;
- (BOOL)isProgressPaused;
- (long long)progressState;
- (void)_updateProgress;
- (void)_updateBadgeValue;
- (void)_performDelayedIconUpdates;
- (id)badgeNumberOrString;
- (void)updateLabel;
@property(readonly, copy) NSString *description;
- (void)localeChanged;
- (id)displayNameForLocation:(id)arg1;
- (id)genericIconImageWithInfo:(struct SBIconImageInfo)arg1;
- (id)generateIconImageWithInfo:(struct SBIconImageInfo)arg1;
- (id)rootFolder;
- (void)dealloc;
- (void)invalidateUpdateIconRunLoopObserver;
- (id)initWithFolder:(id)arg1;
- (Class)iconImageViewClassForLocation:(id)arg1;

@end

