//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBHCenterZoomSettings.h>

@class SBFAnimationSettings;

@interface SBHCenterAppZoomSettings : SBHCenterZoomSettings
{
    double _appHeadStart;
    SBFAnimationSettings *_appZoomSettings;
    SBFAnimationSettings *_appFadeSettings;
}

+ (id)settingsControllerModule;
@property(retain, nonatomic) SBFAnimationSettings *appFadeSettings; // @synthesize appFadeSettings=_appFadeSettings;
@property(retain, nonatomic) SBFAnimationSettings *appZoomSettings; // @synthesize appZoomSettings=_appZoomSettings;
@property(nonatomic) double appHeadStart; // @synthesize appHeadStart=_appHeadStart;
// - (void).cxx_destruct;
- (void)setDefaultValues;

@end

