//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBHIconStateBuilder : NSObject
{
}

+ (id)iconStateFolderWithName:(id)arg1 iconLists:(id)arg2;
+ (id)iconStateWithIconLists:(id)arg1;
+ (id)iconStateWithIconLists:(id)arg1 dock:(id)arg2;

@end

