//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoardHome/SBHRecentsDocumentExtensionProviderDelegate-Protocol.h>
#import <SpringBoardHome/WGWidgetViewControllerDelegate-Protocol.h>

@class MTMaterialView, NSArray, NSString, UIContextMenuInteraction;

@interface SBHIconViewContextMenuWrapperViewController : UIViewController <WGWidgetViewControllerDelegate, SBHRecentsDocumentExtensionProviderDelegate>
{
    MTMaterialView *_backgroundView;
    NSArray *_layoutConstraints;
    UIViewController *_contentViewController;
    NSString *_groupNameBase;
    double _backgroundScale;
    UIContextMenuInteraction *_contextMenuInteraction;
}

@property(retain, nonatomic) UIContextMenuInteraction *contextMenuInteraction; // @synthesize contextMenuInteraction=_contextMenuInteraction;
@property(nonatomic) double backgroundScale; // @synthesize backgroundScale=_backgroundScale;
@property(copy, nonatomic) NSString *groupNameBase; // @synthesize groupNameBase=_groupNameBase;
@property(retain, nonatomic) UIViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
// - (void).cxx_destruct;
- (void)_applyPreferredContentSizeChange:(CGSize)arg1;
- (void)recentsDocumentExtensionViewControllerRequestsDismiss:(id)arg1;
- (void)remoteViewControllerViewDidAppearForWidgetViewController:(id)arg1;
- (void)remoteViewControllerDidConnectForWidgetViewController:(id)arg1;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

