//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>

@class NSString;

@interface SBHIconLabelVisualConfiguration : NSObject <NSCopying, BSDescriptionProviding>
{
    double _fontSize;
    double _baselineOffsetFromImage;
    double _height;
    double _widthDelta;
}

@property(nonatomic) double widthDelta; // @synthesize widthDelta=_widthDelta;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double baselineOffsetFromImage; // @synthesize baselineOffsetFromImage=_baselineOffsetFromImage;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
// - (id)copyWithZone:(_NSZone )arg1;
- (id)init;

@end

