//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBHIconModel;

@interface SBHIconStateUnarchiver : NSObject
{
    BOOL _removesEmptyFolders;
    id _archive;
    SBHIconModel *_iconSource;
}

+ (void)_getFolderDisplayName:(id )arg1 defaultDisplayName:(id )arg2 forRepresentation:(id)arg3 iconSource:(id)arg4;
@property(readonly, nonatomic) SBHIconModel *iconSource; // @synthesize iconSource=_iconSource;
@property(readonly, nonatomic) id archive; // @synthesize archive=_archive;
@property(nonatomic) BOOL removesEmptyFolders; // @synthesize removesEmptyFolders=_removesEmptyFolders;
// - (void).cxx_destruct;
- (id)_listFromRepresentation:(id)arg1 withMaxIconCount:(NSUInteger)arg2 identifier:(id)arg3 context:(id)arg4 overflow:(id)arg5;
- (id)_folderFromRepresentation:(id)arg1 withContext:(id)arg2;
- (void)_getFolderDisplayName:(id )arg1 defaultDisplayName:(id )arg2 forRepresentation:(id)arg3;
- (Class)_folderClassForFolderType:(id)arg1 context:(id)arg2;
- (id)_iconFromRepresentation:(id)arg1 withContext:(id)arg2;
- (id)_newFolderIconForFolder:(id)arg1;
- (id)_nodeFromRepresentation:(id)arg1 context:(id)arg2;
- (id)unarchive;
- (id)initWithArchive:(id)arg1 iconSource:(id)arg2;

@end

