//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/SBViewControllerInteractiveTransitioning-Protocol.h>

@class UIInteractionProgress;
@protocol SBViewControllerContextTransitioning;

@interface SBHintInteractor : NSObject <UIInteractionProgressObserver, SBViewControllerInteractiveTransitioning>
{
    id <SBViewControllerContextTransitioning> _transitionContext;
    CDStruct_3e878e9e _hintInterval;
    UIInteractionProgress *_interactionProgress;
}

@property(readonly, nonatomic) UIInteractionProgress *interactionProgress; // @synthesize interactionProgress=_interactionProgress;
// - (void).cxx_destruct;
- (void)_updateInteractionPercentComplete:(double)arg1;
- (void)interactionProgress:(id)arg1 didEnd:(BOOL)arg2;
- (void)interactionProgressDidUpdate:(id)arg1;
- (BOOL)supportsRestarting;
- (void)finishInteractiveTransition;
- (void)cancelTransition;
- (void)updateTransition:(double)arg1;
- (void)startInteractiveTransition:(id)arg1;
@property(readonly, nonatomic) double maxHintProgress;
- (id)initWithInteractionProgress:(id)arg1 maxHintProgress:(double)arg2;

@end

