//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBHIconAnimationSettings.h>

@interface SBHIconZoomSettings : SBHIconAnimationSettings
{
    BOOL _labelAlphaWithZoom;
}

+ (id)settingsControllerModule;
@property(nonatomic) BOOL labelAlphaWithZoom; // @synthesize labelAlphaWithZoom=_labelAlphaWithZoom;
- (void)setDefaultValues;

@end

