//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBHIconApplicationShortcutListComposer : NSObject
{
}

+ (id)composedShortcutsForFolderIcon:(id)arg1 iconImageCache:(id)arg2 iconManagerAllowsEditing:(BOOL)arg3 badgeViewGenerator:(id /* CDUnknownBlockType */)arg4;
+ (id)composedShortcutsForDownloadingApplicationWithBundleIdentifier:(id)arg1 iconDisplayName:(id)arg2 prioritizationIsAvailable:(BOOL)arg3 downloadingInformationAgent:(id)arg4 canShare:(BOOL)arg5;
+ (id)composedShortcutsForBookmarkWithDisplayName:(id)arg1 removeStyle:(long long)arg2;
+ (id)composedShortcutsForApplicationWithBundleIdentifier:(id)arg1 iconDisplayName:(id)arg2 staticItems:(id)arg3 dynamicItems:(id)arg4 applicationItemID:(NSUInteger)arg5 numberOfDisplayItemsInSwitcher:(long long)arg6 supportsMultipleWindows:(BOOL)arg7 isSystemApplication:(BOOL)arg8 isInternalApplication:(BOOL)arg9 isApplicationInBeta:(BOOL)arg10 removeStyle:(long long)arg11;
+ (BOOL)supportsMultiwindowShortcut;
+ (id)filteredApplicationShortcutItemsWithStaticApplicationShortcutItems:(id)arg1 dynamicApplicationShortcutItems:(id)arg2;

@end

