//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, PCPersistentTimer;
@protocol SBHSidebarWidgetLearningDataSource;

@interface SBHSidebarWidgetBootstrappingAdvisor : NSObject
{
    PCPersistentTimer *_widgetLearningCadenceUpdateTimer;
    NSHashTable *_observers;
    BOOL _shouldSidebarWidgetsBeInLearningMode;
    id <SBHSidebarWidgetLearningDataSource> _dataSource;
    double _learningDuration;
    NSUInteger _learningEpoch;
}

@property(readonly, nonatomic) NSUInteger learningEpoch; // @synthesize learningEpoch=_learningEpoch;
@property(readonly, nonatomic) double learningDuration; // @synthesize learningDuration=_learningDuration;
@property(nonatomic) BOOL shouldSidebarWidgetsBeInLearningMode; // @synthesize shouldSidebarWidgetsBeInLearningMode=_shouldSidebarWidgetsBeInLearningMode;
@property(readonly, nonatomic) id <SBHSidebarWidgetLearningDataSource> dataSource; // @synthesize dataSource=_dataSource;
// - (void).cxx_destruct;
- (BOOL)_requiresLearningCadenceForFavoriteWidgets:(BOOL )arg1;
- (void)_updateSidebarWidgetsCommenceDateIfEmpty;
- (void)_updateSidebarWidgetsEpoch;
- (void)_notifyObservers;
- (void)_sidebarLearningPeriodTimeIsUp:(id)arg1;
- (void)_scheduleWidgetLearningCadenceUpdateTimer:(BOOL)arg1;
- (void)_setupSidebarWidgetsLearningCadence;
- (void)noteSignificantSidebarStateChangeDidOccur;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)initWithDataSource:(id)arg1;
- (id)initWithDataSource:(id)arg1 learningDuration:(double)arg2 learningEpoch:(NSUInteger)arg3;

@end

