//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBHIconZoomSettings.h>

@class SBFAnimationSettings;

@interface SBHScaleZoomSettings : SBHIconZoomSettings
{
    BOOL _crossfadeWithZoom;
    BOOL _fadesIconGrid;
    SBFAnimationSettings *_outerFolderFadeSettings;
    SBFAnimationSettings *_crossfadeSettings;
    SBFAnimationSettings *_iconGridFadeSettings;
}

+ (id)settingsControllerModule;
@property(retain, nonatomic) SBFAnimationSettings *iconGridFadeSettings; // @synthesize iconGridFadeSettings=_iconGridFadeSettings;
@property(nonatomic) BOOL fadesIconGrid; // @synthesize fadesIconGrid=_fadesIconGrid;
@property(retain, nonatomic) SBFAnimationSettings *crossfadeSettings; // @synthesize crossfadeSettings=_crossfadeSettings;
@property(nonatomic) BOOL crossfadeWithZoom; // @synthesize crossfadeWithZoom=_crossfadeWithZoom;
@property(retain, nonatomic) SBFAnimationSettings *outerFolderFadeSettings; // @synthesize outerFolderFadeSettings=_outerFolderFadeSettings;
// - (void).cxx_destruct;
- (id)effectiveCrossfadeAnimationSettings;
- (void)setDefaultValues;

@end

