//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBIconListGridLayout.h>

@interface SBIconListFlowLayout : SBIconListGridLayout
{
}

- (struct SBIconCoordinate)iconCoordinateForIndex:(NSUInteger)arg1 forOrientation:(long long)arg2 inList:(id)arg3;

@end

