//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;

@interface SBIconListViewAppDragContext : NSObject
{
    BOOL _hasPaused;
    NSTimer *_pauseTimer;
    CGPoint _pausePoint;
}

@property(nonatomic) BOOL hasPaused; // @synthesize hasPaused=_hasPaused;
@property(nonatomic) CGPoint pausePoint; // @synthesize pausePoint=_pausePoint;
@property(retain, nonatomic) NSTimer *pauseTimer; // @synthesize pauseTimer=_pauseTimer;
// - (void).cxx_destruct;

@end

