//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBIconLabelAccessoryView.h>

@class UIImageView;

@interface SBIconDotLabelAccessoryView : SBIconLabelAccessoryView
{
    UIImageView *_imageView;
}

+ (struct CAColorMatrix)_vibrantColorMatrixInput;
+ (id)_dotColor;
+ (id)labelAccessorySystemImageName;
// - (void).cxx_destruct;
- (CGSize)intrinsicContentSize;
- (id)initWithFrame:(CGRect)arg1;
- (void)updateWithBaseImage:(id)arg1 legibilitySettings:(id)arg2;

@end

