//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSSet;
@protocol SBIconIndexNode;

@protocol SBIconIndexNodeObserver <NSObject>
- (void)nodeDidMoveContainedNodes:(id <SBIconIndexNode>)arg1;
- (void)node:(id <SBIconIndexNode>)arg1 didRemoveContainedNodeIdentifiers:(NSSet *)arg2;
- (void)node:(id <SBIconIndexNode>)arg1 didAddContainedNodeIdentifiers:(NSSet *)arg2;
@end

