//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImage.h>

#import <SpringBoardHome/SBCountedMapValue-Protocol.h>

@class NSString;

@interface SBIconAccessoryImage : UIImage <SBCountedMapValue>
{
    NSString *_countedMapKey;
}

@property(copy, nonatomic) NSString *countedMapKey; // @synthesize countedMapKey=_countedMapKey;
// - (void).cxx_destruct;
- (id)initWithImage:(id)arg1;

@end

