//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBIconLayoutOverrideStrategy : NSObject
{
    UIEdgeInsets _layoutInsets;
    BOOL _preservesCurrentListOrigin;
}

@property(readonly, nonatomic) BOOL preservesCurrentListOrigin; // @synthesize preservesCurrentListOrigin=_preservesCurrentListOrigin;
@property(readonly, nonatomic) UIEdgeInsets layoutInsets; // @synthesize layoutInsets=_layoutInsets;
- (id)initWithLayoutInsets:(UIEdgeInsets)arg1 perservingCurrentListOrigin:(BOOL)arg2;

@end

