//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBIconLabelViewFactory : NSObject
{
}

+ (BOOL)canUseIconLabelView:(id)arg1 toDisplayLabelWithSettings:(id)arg2 imageParameters:(id)arg3 forIconView:(id)arg4;
+ (id)iconLabelViewWithSettings:(id)arg1 imageParameters:(id)arg2 forIconView:(id)arg3;
+ (BOOL)canUseIconSimpleLabelViewToDisplayLabelWithSettings:(id)arg1 imageParameters:(id)arg2 forIconView:(id)arg3;

@end

