//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBIconDraggingEditContext : NSObject
{
    BOOL _enteredScreenLocationNeedsUpdate;
    id _draggingUniqueIdentifier;
    CGPoint _enteredScreenLocation;
}

@property(nonatomic) BOOL enteredScreenLocationNeedsUpdate; // @synthesize enteredScreenLocationNeedsUpdate=_enteredScreenLocationNeedsUpdate;
@property(nonatomic) CGPoint enteredScreenLocation; // @synthesize enteredScreenLocation=_enteredScreenLocation;
@property(retain, nonatomic) id draggingUniqueIdentifier; // @synthesize draggingUniqueIdentifier=_draggingUniqueIdentifier;
// - (void).cxx_destruct;

@end

