//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBReusableView-Protocol.h>

@class SBFParallaxSettings, SBIcon, UIViewPropertyAnimator;
@protocol SBIconAccessoryInfoProvider, SBIconListLayout;

@protocol SBIconAccessoryView <SBReusableView>
- (void)setAccessoryBrightness:(double)arg1;
- (BOOL)displayingAccessory;
- (CGPoint)accessoryCenterForIconBounds:(CGRect)arg1;
- (void)configureForIcon:(SBIcon *)arg1 infoProvider:(id <SBIconAccessoryInfoProvider>)arg2;
- (void)configureAnimatedForIcon:(SBIcon *)arg1 infoProvider:(id <SBIconAccessoryInfoProvider>)arg2 animator:(UIViewPropertyAnimator *)arg3;

@optional
@property(retain, nonatomic) id <SBIconListLayout> listLayout;
@property(retain, nonatomic) SBFParallaxSettings *parallaxSettings;
@end

