//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, SBIcon;

@protocol SBIconDelegate
- (void)icon:(SBIcon *)arg1 launchFromLocation:(NSString *)arg2 context:(id)arg3;
@end

