//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBIconImageView.h>

@interface SBLiveIconImageView : SBIconImageView
{
}

- (id)snapshot;
- (void)prepareForReuse;
- (void)updateImageAnimated:(BOOL)arg1;
- (void)updateUnanimated;
- (void)updateAnimatingState;
- (void)setPaused:(BOOL)arg1;
- (BOOL)isAnimationAllowed;
- (void)setIcon:(id)arg1 location:(id)arg2 animated:(BOOL)arg3;

@end

