//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBIconLabelImageParameters.h>

@class NSString, UIColor, UIFont;

@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters
{
}

@property(nonatomic) UIEdgeInsets fontLanguageInsets; // @dynamic fontLanguageInsets;
@property(nonatomic) UIEdgeInsets textInsets; // @dynamic textInsets;
@property(retain, nonatomic) UIColor *focusHighlightColor; // @dynamic focusHighlightColor;
@property(copy, nonatomic) NSString *contentSizeCategory; // @dynamic contentSizeCategory;
@property(nonatomic, getter=isAccessibilityReduceTransparencyEnabled) BOOL accessibilityReduceTransparencyEnabled; // @dynamic accessibilityReduceTransparencyEnabled;
@property(nonatomic) double scale; // @dynamic scale;
@property(retain, nonatomic) UIColor *textColor; // @dynamic textColor;
@property(nonatomic) long long legibilityStyle; // @dynamic legibilityStyle;
@property(nonatomic) BOOL containsEmoji; // @dynamic containsEmoji;
@property(nonatomic) BOOL canTighten; // @dynamic canTighten;
@property(nonatomic) BOOL canTruncate; // @dynamic canTruncate;
@property(copy, nonatomic) NSString *iconLocation; // @dynamic iconLocation;
@property(retain, nonatomic) UIFont *font; // @dynamic font;
@property(nonatomic) CGSize maxSize; // @dynamic maxSize;
@property(copy, nonatomic) NSString *text; // @dynamic text;
- (id)copy;

@end

