//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface SBRootFolderDockAnimationViewController : UIViewController
{
    long long _forcedInterfaceOrientation;
}

@property(nonatomic) long long forcedInterfaceOrientation; // @synthesize forcedInterfaceOrientation=_forcedInterfaceOrientation;
- (NSUInteger)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;

@end

