//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBRootFolderControllerTransitionInfo : NSObject
{
    long long _sourcePageState;
    long long _destinationPageState;
}

@property(nonatomic) long long destinationPageState; // @synthesize destinationPageState=_destinationPageState;
@property(nonatomic) long long sourcePageState; // @synthesize sourcePageState=_sourcePageState;

@end

