//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBHomeScreenButton.h>

@interface SBTitledHomeScreenButton : SBHomeScreenButton
{
}

+ (id)contentImageWithTitle:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;
- (CGSize)sizeThatFits:(CGSize)arg1;

@end

