//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSArray, NSString;
@protocol SBTreeNode;

@protocol SBTreeNode <NSObject>
@property(readonly, copy, nonatomic) NSString *uniqueIdentifier;
@property(nonatomic) __weak id <SBTreeNode> parent;
@property(readonly, nonatomic) NSArray *children;
- (void)ancestryDidChange;
- (void)removeChild:(id <SBTreeNode>)arg1;
@end

