//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBViewControllerPercentCompletionReporting-Protocol.h>
#import <SpringBoardHome/SBViewControllerReversibleTransitioning-Protocol.h>
#import <SpringBoardHome/SBViewControllerTransitionRestartedReporting-Protocol.h>

@protocol SBViewControllerContextTransitioning <UIViewControllerContextTransitioning, SBViewControllerReversibleTransitioning, SBViewControllerPercentCompletionReporting, SBViewControllerTransitionRestartedReporting>
- (BOOL)wasPreviousPhaseInteractive;
- (BOOL)initiallyInteractive;
- (void)restartTransition;
- (BOOL)supportsRestarting;
- (BOOL)supportsCancelling;
- (BOOL)isTransitioning;
@end

