//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;
@protocol OS_dispatch_queue;

@interface PKIconImageCache : NSObject
{
    NSObject<OS_dispatch_queue> *_cacheAccessQueue;
    NSDictionary *_iconCache;
}

+ (id)settingsIconCacheWithScale:(double)arg1;
+ (id)settingsIconCache;
@property(retain, nonatomic) NSDictionary *iconCache; // @synthesize iconCache=_iconCache;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheAccessQueue; // @synthesize cacheAccessQueue=_cacheAccessQueue;
// - (void).cxx_destruct;
- (id)allImageIconKeys;
- (id)imageForKey:(id)arg1;
- (id)initWithPath:(id)arg1 scale:(double)arg2;

@end

