//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Preferences/PSHeaderFooterView-Protocol.h>

@class NSLayoutConstraint, NSString, NSURL, UITextView;

@interface PSFooterHyperlinkView : UITableViewHeaderFooterView <PSHeaderFooterView, UITextViewDelegate>
{
    NSString *_text;
    NSURL *_URL;
    id _target;
    SEL _action;
    UITextView *_textView;
    NSLayoutConstraint *_textViewLeadingConstraint;
    NSLayoutConstraint *_textViewTrailingConstraint;
    NSRange * _linkRange;
}

@property(retain, nonatomic) NSLayoutConstraint *textViewTrailingConstraint; // @synthesize textViewTrailingConstraint=_textViewTrailingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *textViewLeadingConstraint; // @synthesize textViewLeadingConstraint=_textViewLeadingConstraint;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) NSRange * linkRange; // @synthesize linkRange=_linkRange;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
// - (void).cxx_destruct;
- (void)_accessibilitySetInterfaceStyleIntent:(NSUInteger)arg1;
- (BOOL)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(NSRange *)arg3;
- (double)preferredHeightForWidth:(double)arg1 inTableView:(id)arg2;
- (BOOL)isValidLinkRange;
- (void)_linkify;
- (void)updateConstraints;
- (void)setTableView:(id)arg1;
- (void)setupSubviewsAndContstraints;
- (id)initWithSpecifier:(id)arg1;

@end

