//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Preferences/PSHeaderFooterView-Protocol.h>

@class UILabel;

@interface PSKeychainSyncHeaderView : UIView <PSHeaderFooterView>
{
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    BOOL _usesCompactLayout;
}

@property(nonatomic) BOOL usesCompactLayout; // @synthesize usesCompactLayout=_usesCompactLayout;
// - (void).cxx_destruct;
- (double)preferredHeightForWidth:(double)arg1 inTableView:(id)arg2;
- (void)layoutSubviews;
- (void)setTitleText:(id)arg1;
- (void)setDetailText:(id)arg1;
- (id)initWithSpecifier:(id)arg1;

@end

