//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSString, PSPasscodeField;

@protocol PSPasscodeFieldDelegate <NSObject>
- (void)passcodeField:(PSPasscodeField *)arg1 enteredPasscode:(NSString *)arg2;

@optional
- (NSString *)passcodeField:(PSPasscodeField *)arg1 shouldInsertText:(NSString *)arg2;
@end

