//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer, UITableViewCell;

@interface PSTableCellHighlightContext : NSObject
{
    NSTimer *_timer;
    BOOL _animateUnhighlight;
    BOOL _valid;
    UITableViewCell *_cell;
    long long _originalSelectionStyle;
}

+ (id)contextWithCell:(id)arg1;
@property(readonly, nonatomic) BOOL valid; // @synthesize valid=_valid;
@property(nonatomic) long long originalSelectionStyle; // @synthesize originalSelectionStyle=_originalSelectionStyle;
@property(readonly, nonatomic) BOOL animateUnhighlight; // @synthesize animateUnhighlight=_animateUnhighlight;
@property(nonatomic) __weak UITableViewCell *cell; // @synthesize cell=_cell;
// - (void).cxx_destruct;
- (void)_killTimer;
- (void)invalidate;
- (void)_timerFired;
- (void)performHighlightForDuration:(double)arg1 animateUnhighlight:(BOOL)arg2;
- (void)dealloc;

@end

