//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  5 2019 09:59:31).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSTableCell.h>

@class NSArray, UILabel;
@protocol PSTimeRangeCellDelegate;

@interface PSTimeRangeCell : PSTableCell
{
    UILabel *_fromTitle;
    UILabel *_toTitle;
    UILabel *_fromTime;
    UILabel *_toTime;
    NSArray *_constraints;
    id <PSTimeRangeCellDelegate> _delegate;
}

// - (void).cxx_destruct;
- (id)accessibilityConstraintsWithVariableBindings:(id)arg1 metrics:(id)arg2;
- (id)regularConstraintsWithVariableBindings:(id)arg1 metrics:(id)arg2;
- (void)updateConstraints;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

