//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString;

@interface _SBApplicationLaunchAlertInfo : NSObject
{
    NSString *_bundleID;
    NSMutableSet *_foregroundScenes;
    NSMutableSet *_alertItems;
}

@property(readonly, nonatomic) NSMutableSet *alertItems; // @synthesize alertItems=_alertItems;
@property(readonly, nonatomic) NSMutableSet *foregroundScenes; // @synthesize foregroundScenes=_foregroundScenes;
@property(readonly, copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
// - (void).cxx_destruct;
- (id)description;
- (id)initWithBundleID:(id)arg1;

@end

