//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBAppLayout, SBDisplayItem, XBApplicationSnapshot;

@interface _SBAppSwitcherSnapshotImageCacheRequest : NSObject
{
    BOOL _loadFullSizeSnapshot;
    NSUInteger _sequenceID;
    SBAppLayout *_appLayout;
    SBDisplayItem *_displayItem;
    XBApplicationSnapshot *_snapshot;
}

@property(retain, nonatomic) XBApplicationSnapshot *snapshot; // @synthesize snapshot=_snapshot;
@property(retain, nonatomic) SBDisplayItem *displayItem; // @synthesize displayItem=_displayItem;
@property(retain, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
@property(nonatomic) BOOL loadFullSizeSnapshot; // @synthesize loadFullSizeSnapshot=_loadFullSizeSnapshot;
@property(readonly, nonatomic) NSUInteger sequenceID; // @synthesize sequenceID=_sequenceID;
// - (void).cxx_destruct;
- (id)description;
- (id)initWithSequenceID:(NSUInteger)arg1;

@end

