//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBSwitcherModifierTimelineEntry, UILabel, UITapGestureRecognizer;
@protocol _SBFluidSwitcherModifierTimelineEntryViewDelegate;

@interface _SBFluidSwitcherModifierTimelineEntryView : UIView
{
    UILabel *_nameLabel;
    UILabel *_postStackLabel;
    UILabel *_actionsLabel;
    UITapGestureRecognizer *_tapRecognizer;
    SBSwitcherModifierTimelineEntry *_entry;
    id <_SBFluidSwitcherModifierTimelineEntryViewDelegate> _delegate;
}

@property(nonatomic) __weak id <_SBFluidSwitcherModifierTimelineEntryViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBSwitcherModifierTimelineEntry *entry; // @synthesize entry=_entry;
// - (void).cxx_destruct;
- (id)_appendRecursiveDescriptionToString:(id)arg1 level:(NSUInteger)arg2 snapshot:(id)arg3;
- (id)_stringForStack:(id)arg1;
- (id)_randomColor;
- (void)_tap:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(CGRect)arg1 entry:(id)arg2;

@end

