//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUUID, SBInteractiveScreenshotGestureHostRootViewController, SBInteractiveScreenshotGestureHostWindow, SBInteractiveScreenshotGestureRootViewController, SBInteractiveScreenshotGestureRootWindow;

@interface _SBInteractiveScreenshotGestureSession : NSObject
{
    NSUUID *_sessionID;
    SBInteractiveScreenshotGestureRootWindow *_rootWindow;
    SBInteractiveScreenshotGestureHostWindow *_hostWindow;
}

@property(retain, nonatomic) SBInteractiveScreenshotGestureHostWindow *hostWindow; // @synthesize hostWindow=_hostWindow;
@property(retain, nonatomic) SBInteractiveScreenshotGestureRootWindow *rootWindow; // @synthesize rootWindow=_rootWindow;
@property(readonly, copy, nonatomic) NSUUID *sessionID; // @synthesize sessionID=_sessionID;
// - (void).cxx_destruct;
@property(readonly, nonatomic) SBInteractiveScreenshotGestureRootViewController *rootViewController;
@property(readonly, nonatomic) SBInteractiveScreenshotGestureHostRootViewController *hostRootViewController;
- (id)initWithSessionID:(id)arg1;

@end

