//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _SBMainScreenActiveInterfaceOrientationWindowRootViewController : UIViewController
{
    NSUInteger _supportedInterfaceOrientations;
}

@property(nonatomic) NSUInteger supportedInterfaceOrientations; // @synthesize supportedInterfaceOrientations=_supportedInterfaceOrientations;
- (BOOL)_canShowWhileLocked;
- (id)_viewControllerForSupportedInterfaceOrientationsWithDismissCheck:(BOOL)arg1;
- (BOOL)shouldAutorotate;

@end

