//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _SBStatusBarLocalDataOverridesWrapper : NSObject
{
    CDStruct_fdd39a06 _overrides;
}

@property(nonatomic) CDStruct_fdd39a06 overrides; // @synthesize overrides=_overrides;
- (void)dealloc;

@end

