//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>


@class NSString, SBApplication;

@interface _SBStatusBarTapApplicationDestination : NSObject <NSCopying>
{
    SBApplication *_application;
    NSString *_sceneIdentifier;
}

@property(readonly, copy, nonatomic) NSString *sceneIdentifier; // @synthesize sceneIdentifier=_sceneIdentifier;
// - (void).cxx_destruct;
- (id)description;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)arg1;
// - (id)copyWithZone:(_NSZone )arg1;
- (id)initWithApplication:(id)arg1 sceneIdentifier:(id)arg2;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier;
- (id)application;

@end

