//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _UIScrollToTopView
- (void)_scrollToTopFromTouchAtScreenLocation:(CGPoint)arg1 resultHandler:(void (^)(BOOL))arg2;
- (BOOL)isScrollEnabled;
@end

