//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class CSPageViewController;
@protocol CSCoverSheetParticipating, SBFLegibilitySettingsProvider;

@protocol CSSpotlightPresenting <NSObject>
@property(nonatomic) __weak CSPageViewController *todayPageViewController;
- (id <SBFLegibilitySettingsProvider>)createSpotlightLegiblitySettingsProvider;
- (void)dismissSpotlightWithCompletion:(void (^)(void))arg1;
- (void)dismissSpotlight;
- (void)launchSpotlightForSourceViewController:(id <CSCoverSheetParticipating>)arg1 interactive:(BOOL)arg2 completion:(void (^)(void))arg3;
- (void)launchSpotlightForSourceViewController:(id <CSCoverSheetParticipating>)arg1 interactive:(BOOL)arg2;
@end

