//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/BSTransactionObserver-Protocol.h>

@class FBApplicationProcess, FBApplicationProcessLaunchTransaction;

@protocol FBApplicationProcessLaunchTransactionObserver <BSTransactionObserver>

@optional
- (void)transaction:(FBApplicationProcessLaunchTransaction *)arg1 didLaunchProcess:(FBApplicationProcess *)arg2;
- (void)transaction:(FBApplicationProcessLaunchTransaction *)arg1 willLaunchProcess:(FBApplicationProcess *)arg2;
@end

