//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class FBSWorkspaceSceneRequestOptions, FBWorkspace;

@protocol FBWorkspaceDelegate <NSObject>
- (void)workspace:(FBWorkspace *)arg1 didReceiveSceneRequestWithOptions:(FBSWorkspaceSceneRequestOptions *)arg2 completion:(void (^)(FBScene *, NSError *))arg3;
@end

