//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NCNotificationManagementContentProvider, NCNotificationRequest, UIView;

@protocol NCNotificationManagementContentProviderDelegate <NSObject>
- (void)notificationManagementContentProvider:(NCNotificationManagementContentProvider *)arg1 requestsPresentingNotificationManagementViewType:(NSUInteger)arg2 forNotificationRequest:(NCNotificationRequest *)arg3 withPresentingView:(UIView *)arg4;
@end

