//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (SpringBoard)
- (void)_sb_safeAddObject:(id)arg1;
- (id)_sb_peek;
- (id)_sb_dequeue;
- (void)_sb_enqueue:(id)arg1;
@end

