//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>

@class NSString;

@interface SBAnalyticsStateMachineEdge : NSObject <BSDescriptionProviding>
{
    NSUInteger _fromState;
    id /* CDUnknownBlockType */ _transition;
}

+ (id)edgeFromState:(NSUInteger)arg1 transition:(id /* CDUnknownBlockType */)arg2;
+ (id)edgeFromState:(NSUInteger)arg1 toState:(NSUInteger)arg2 uponEvent:(NSUInteger)arg3;
+ (id)edgeFromState:(NSUInteger)arg1 toState:(NSUInteger)arg2 uponGestureState:(long long)arg3 andDo:(id /* CDUnknownBlockType */)arg4;
+ (id)edgeFromState:(NSUInteger)arg1 toState:(NSUInteger)arg2 uponGestureState:(long long)arg3;
@property(readonly, nonatomic) NSUInteger fromState; // @synthesize fromState=_fromState;
// - (void).cxx_destruct;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (NSUInteger)handleEvent:(NSUInteger)arg1 withContext:(id)arg2;
- (id)initWithFromState:(NSUInteger)arg1 transition:(id /* CDUnknownBlockType */)arg2;

@end

