//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSceneViewControlling-Protocol.h>

@class SBApplicationSceneHandle;
@protocol SBApplicationSceneViewControllingStatusBarDelegate;

@protocol SBApplicationSceneViewControlling <SBSceneViewControlling>
@property(nonatomic) __weak id <SBApplicationSceneViewControllingStatusBarDelegate> applicationSceneStatusBarDelegate;
@property(readonly, nonatomic) long long overrideStatusBarStyle;
@property(readonly, nonatomic) double statusBarAlpha;
@property(readonly, nonatomic) SBApplicationSceneHandle *sceneHandle;
@end

