//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSString, SBDeviceApplicationSceneHandle;

@protocol SBApplicationSceneStatusBarDescribing <NSObject>
@property(readonly, nonatomic) SBDeviceApplicationSceneHandle *statusBarControllingSceneHandle;
@property(readonly, nonatomic) NSString *statusBarSceneIdentifier;
@property(readonly, nonatomic) CGRect statusBarAvoidanceFrame;
@property(readonly, nonatomic) int statusBarStyleOverridesToSuppress;
@property(readonly, nonatomic) long long statusBarOrientation;
@property(readonly, nonatomic) double statusBarAlpha;
@property(readonly, nonatomic) BOOL statusBarHidden;
@property(readonly, nonatomic) long long statusBarStyle;
- (long long)statusBarStyleForPartWithIdentifier:(NSString *)arg1;
@end

