//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface SBAppBrightnessChangeLogger : NSObject
{
    NSString *_bundleID;
    long long _brightnessLevel;
    NSDate *_eventTimestamp;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSDate *eventTimestamp; // @synthesize eventTimestamp=_eventTimestamp;
@property(nonatomic) long long brightnessLevel; // @synthesize brightnessLevel=_brightnessLevel;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
// - (void).cxx_destruct;
- (void)_screenLocked;
- (void)_publishMetrics;
- (void)_publishMetricsIfNeeded;
- (void)noteApp:(id)arg1 setScreenBrightness:(double)arg2;
- (id)init;

@end

