//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSwitcherModifier.h>

@class NSArray, NSString, SBAppLayout;
@protocol SBFluidSwitcherModifierProviding;

@interface SBAppExposeSwitcherModifier : SBSwitcherModifier
{
    NSString *_bundleIdentifier;
    SBAppLayout *_activatingAppLayout;
    NSUInteger _incomingTransitionPhase;
    NSArray *_appLayoutsToKeepDuringIncomingTransition;
    id <SBFluidSwitcherModifierProviding> _modifierProvider;
    SBSwitcherModifier *_outgoingTransitionModifier;
    BOOL _isFloating;
    BOOL _isShowingReopenClosedWindowsButton;
    long long _numberOfHiddenAppLayouts;
}

// - (void).cxx_destruct;
- (BOOL)_canShowReopenClosedWindowsButton;
- (id)_updateReopenClosedWindowsButtonPresence;
- (BOOL)_shouldFilteringIncludeAppLayout:(id)arg1;
- (id)appLayoutToScrollToBeforeReopeningClosedWindows;
- (id)appLayoutToScrollToBeforeTransitioning;
- (id)adjustedAppLayoutsForAppLayouts:(id)arg1;
- (long long)plusButtonStyle;
- (long long)appExposeAccessoryButtonsOverrideUserInterfaceStyle;
- (double)reopenClosedWindowsButtonScale;
- (double)reopenClosedWindowsButtonAlpha;
- (double)plusButtonAlpha;
- (id)appExposeAccessoryButtonsBundleIdentifier;
- (BOOL)isTetheredScrollingEnabled;
- (id)handleTimerEvent:(id)arg1;
- (id)handleTetheredInsertionEvent:(id)arg1;
- (id)handleTetheredRemovalEvent:(id)arg1;
- (id)handleInsertionEvent:(id)arg1;
- (id)handleRemovalEvent:(id)arg1;
- (id)handleAppExposeEvent:(id)arg1;
- (id)handleMainTransitionEvent:(id)arg1;
- (id)handleEvent:(id)arg1;
- (long long)liveContentRasterizationStyle;
- (id)appLayoutsForInsertionOrRemoval;
- (id)initWithBundleIdentifier:(id)arg1 modifierProvider:(id)arg2 floating:(BOOL)arg3;

@end

