//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSwitcherWallpaperPageContentView.h>

#import <SpringBoard/SBAppSwitcherPageContentView-Protocol.h>
#import <SpringBoard/SBAppSwitcherSnapshotImageCacheObserver-Protocol.h>
#import <SpringBoard/SBReusableView-Protocol.h>

@class CAShapeLayer, NSMutableArray, NSMutableDictionary, NSString, SBAppLayout, SBAppSwitcherSettings, SBAppSwitcherSnapshotImageCache, SBAppSwitcherSnapshotLockoutViewControllerProvider, SBMedusaSettings, SBOrientationTransformWrapperView, SBSwitcherSnapshotImageView, UIView, UIViewController;
@protocol SBAppSwitcherReusableSnapshotViewDelegate;

@interface SBAppSwitcherReusableSnapshotView : SBSwitcherWallpaperPageContentView <SBAppSwitcherSnapshotImageCacheObserver, SBReusableView, SBAppSwitcherPageContentView>
{
    SBOrientationTransformWrapperView *_firstOrientationWrapper;
    SBOrientationTransformWrapperView *_secondOrientationWrapper;
    SBSwitcherSnapshotImageView *_firstImageView;
    SBSwitcherSnapshotImageView *_secondImageView;
    UIViewController *_containerViewController;
    id <SBAppSwitcherReusableSnapshotViewDelegate> _delegate;
    NSMutableDictionary *_snapshotViewStateByRole;
    NSMutableDictionary *_lockoutViewControllerByRole;
    CAShapeLayer *_medusaDividerLayer;
    UIView *_solidColorBackstopView;
    SBAppSwitcherSnapshotImageCache *_snapshotCache;
    SBAppSwitcherSnapshotLockoutViewControllerProvider *_lockoutVCProvider;
    SBAppSwitcherSettings *_settings;
    SBMedusaSettings *_medusaSettings;
    BOOL _shouldUseBrightMaterial;
    BOOL _showingIconOverlayView;
    NSMutableArray *_deferredSnapshotCrossfadeQueue;
    BOOL _active;
    BOOL _visible;
    SBAppLayout *_appLayout;
}

@property(nonatomic) BOOL shouldUseBrightMaterial; // @synthesize shouldUseBrightMaterial=_shouldUseBrightMaterial;
@property(nonatomic, getter=isVisible) BOOL visible; // @synthesize visible=_visible;
@property(nonatomic, getter=isActive) BOOL active; // @synthesize active=_active;
@property(retain, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
// - (void).cxx_destruct;
- (void)_removeAppLockoutOverlayForRole:(long long)arg1;
- (void)_addAppLockoutOverlayIfNecessaryForRole:(long long)arg1;
- (void)_updateContentOrientationForRole:(long long)arg1;
- (void)_updateDivider;
- (void)_updateTranslucency;
- (long long)_contentOrientationForSnapshotOrientation:(long long)arg1;
- (void)_performDeferredSnapshotUpdatesIfNecessaryForRole:(long long)arg1;
@property(readonly, nonatomic) BOOL contentRequiresGroupOpacity;
- (void)_updateToNewSnapshotImageUsingCacheEntry:(id)arg1;
- (void)_requestFreshImages;
- (CGRect)_frameInLayoutSpaceForRole:(long long)arg1 inAppLayout:(id)arg2 inOrientation:(long long)arg3;
- (CGRect)_snapshotImageFrameForCacheEntry:(id)arg1;
- (void)_updateCornerRadiusIfNecessaryForLockoutView:(id)arg1 matchingSnapshotImage:(id)arg2;
- (void)_updateCornerRadiusIfNecessaryForSnapshotImageView:(id)arg1 cacheEntry:(id)arg2;
- (void)_configureSnapshotImageView:(id)arg1 cacheEntry:(id)arg2;
- (id)_orientationWrapperForRole:(long long)arg1;
- (id)_imageViewForRole:(long long)arg1;
- (void)_setAnimatingTransition:(BOOL)arg1 forRole:(long long)arg2;
- (BOOL)_isAnimatingTransitionForRole:(long long)arg1;
- (void)_setCacheEntry:(id)arg1 forRole:(long long)arg2;
- (id)_cacheEntryForRole:(long long)arg1;
- (id)_applicationForRole:(long long)arg1;
- (void)_setSceneHandle:(id)arg1 forRole:(long long)arg2;
- (id)_sceneHandleForRole:(long long)arg1;
- (void)_handleInstalledAppsChanged:(id)arg1;
- (void)didUpdateCacheEntry:(id)arg1;
- (void)setShowingIconOverlayView:(BOOL)arg1;
- (void)invalidate;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (CGRect)_frameForBackstopLayer;
@property(nonatomic) long long orientation;
@property(nonatomic) double cornerRadius;
@property(readonly, copy) NSString *description;
- (id)initWithDelegate:(id)arg1 snapshotCache:(id)arg2 lockoutVCProvider:(id)arg3 containerViewController:(id)arg4;

@end

