//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBApplicationSceneEntityDestructionIntent : NSObject
{
    BOOL _shouldRemoveFromHistory;
    NSUInteger _layoutRoles;
    NSUInteger _animation;
}

@property(nonatomic) BOOL shouldRemoveFromHistory; // @synthesize shouldRemoveFromHistory=_shouldRemoveFromHistory;
@property(nonatomic) NSUInteger animation; // @synthesize animation=_animation;
@property(nonatomic) NSUInteger layoutRoles; // @synthesize layoutRoles=_layoutRoles;

@end

