//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/MCProfileConnectionObserver-Protocol.h>

@class FBSApplicationLibrary, NSArray, NSHashTable, NSMutableDictionary, NSMutableSet, SBSplashBoardController;
@protocol OS_dispatch_queue;

@interface SBApplicationLibraryObserver : NSObject <MCProfileConnectionObserver>
{
    SBSplashBoardController *_splashBoardController;
    FBSApplicationLibrary *_appLibrary;
    NSMutableSet *_suspendCalloutsAssertionReasons;
    NSObject<OS_dispatch_queue> *_mainQueueProxy;
    NSMutableDictionary *_placeholdersByBundleID;
    NSHashTable *_applicationObservers;
    NSHashTable *_placeholderObservers;
}

+ (id)new;
// - (void).cxx_destruct;
- (void)profileConnectionDidReceiveProfileListChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)_didChangeNetworkUsage:(BOOL)arg1;
- (void)_didDemoteApplications:(id)arg1;
- (void)_didRemoveApplications:(id)arg1;
- (void)_didUpdateApplications:(id)arg1;
- (void)_didReplaceApplications:(id)arg1;
- (void)_didAddApplications:(id)arg1;
- (void)_didCancelPlaceholders:(id)arg1;
- (void)_didAddPlaceholders:(id)arg1;
- (void)_waitForLaunchImageGenerationForApplications:(id)arg1;
- (void)_removeObserver:(id)arg1 table:(id)arg2;
- (void)_addObserver:(id)arg1 table:(id)arg2;
- (void)removePlaceholderLifecycleObserver:(id)arg1;
- (void)addPlaceholderLifecycleObserver:(id)arg1;
- (void)removeApplicationLifecycleObserver:(id)arg1;
- (void)addApplicationLifecycleObserver:(id)arg1;
- (id)suspendCalloutsAssertionWithReason:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *placeholders;
- (id)initWithAppLibrary:(id)arg1;
- (id)init;

@end

