//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBAWDMetric.h>

@interface SBAppBrightnessMetric : SBAWDMetric
{
}

- (id)configureWithData:(id)arg1;
- (Class)dataClass;
- (NSUInteger)metricID;
- (void)postWithDataBuilder:(id /* CDUnknownBlockType */)arg1;

@end

