//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSceneViewController.h>

#import <SpringBoard/SBApplicationSceneViewControlling-Protocol.h>

@class SBAppStatusBarSettings;
@protocol SBApplicationSceneViewControllingStatusBarDelegate;

@interface SBApplicationSceneViewController : SBSceneViewController <SBApplicationSceneViewControlling>
{
    BOOL __applicationStatusBarHidden;
    id <SBApplicationSceneViewControllingStatusBarDelegate> _applicationSceneStatusBarDelegate;
    SBAppStatusBarSettings *_overrideStatusBarSettings;
}

@property(retain, nonatomic, getter=_overrideStatusBarSettings, setter=_setOverrideStatusBarSettings:) SBAppStatusBarSettings *overrideStatusBarSettings; // @synthesize overrideStatusBarSettings=_overrideStatusBarSettings;
@property(readonly, nonatomic, getter=_isApplicationStatusBarHidden) BOOL _applicationStatusBarHidden; // @synthesize _applicationStatusBarHidden=__applicationStatusBarHidden;
@property(nonatomic) __weak id <SBApplicationSceneViewControllingStatusBarDelegate> applicationSceneStatusBarDelegate; // @synthesize applicationSceneStatusBarDelegate=_applicationSceneStatusBarDelegate;
// - (void).cxx_destruct;
- (double)_applicationStatusBarAlpha;
@property(readonly, nonatomic) long long overrideStatusBarStyle;
@property(readonly, nonatomic) double statusBarAlpha;
- (id)initWithSceneHandle:(id)arg1;

@end

