//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSSet, SBApplicationRestrictionController;

@protocol SBApplicationRestrictionObserver <NSObject>
- (void)applicationRestrictionController:(SBApplicationRestrictionController *)arg1 didUpdateVisibleTags:(NSSet *)arg2 hiddenTags:(NSSet *)arg3;
@end

