//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBAlertItem.h>

@class SBApplication;

@interface SBApplicationLaunchNotifyAlertItem : SBAlertItem
{
    SBApplication *_application;
}

@property(readonly, nonatomic) SBApplication *application; // @synthesize application=_application;
// - (void).cxx_destruct;
- (BOOL)dismissOnLock;
- (id)initWithApplication:(id)arg1;

@end

