//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBUISettings.h>

#import <SpringBoard/MCProfileConnectionObserver-Protocol.h>

@interface SBAttentionAwarenessSettings : SBUISettings <MCProfileConnectionObserver>
{
    BOOL _allowsAttentionAwareAutoLock;
    BOOL _supportsAttentionSensor;
    BOOL _shouldUseAttentionSensor;
    BOOL _isObservingDataSources;
    struct AWNotification_s _attentionAwarenessToken;
    double _sampleInterval;
    double _dimInterval;
    double _sleepInterval;
}

+ (id)settingsControllerModule;
+ (BOOL)attentionSensorSupported;
@property(nonatomic) double sleepInterval; // @synthesize sleepInterval=_sleepInterval;
@property(nonatomic) double dimInterval; // @synthesize dimInterval=_dimInterval;
@property(nonatomic) double sampleInterval; // @synthesize sampleInterval=_sampleInterval;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)setDefaultValues;
@property(nonatomic) BOOL shouldUseAttentionSensor;
- (void)dealloc;

@end

