//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBBacklightController;

@protocol SBBacklightControllerObserver <NSObject>

@optional
- (void)backlightController:(SBBacklightController *)arg1 didAnimateBacklightToFactor:(float)arg2 source:(long long)arg3;
- (void)backlightController:(SBBacklightController *)arg1 willAnimateBacklightToFactor:(float)arg2 source:(long long)arg3;
@end

