//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBBatteryWidgetVisibilityController : NSObject
{
}

+ (id)sharedInstance;
- (void)_makeVisible;
- (BOOL)_isVisible;
- (BOOL)_isAlwaysVisible;
- (void)_setVisibleIfNecessary:(BOOL)arg1;
- (BOOL)_containsExternalBattery;
- (void)_connectedDevicesDidChange;
- (id)init;

@end

