//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBBiometricMonitorObserver-Protocol.h>

@class SBBiometricMonitorViewController, UIWindow;
@protocol SBBiometricMonitorDataSource;

@interface SBBiometricMonitorUI : NSObject <SBBiometricMonitorObserver>
{
    BOOL _enabled;
    UIWindow *_debugWindow;
    SBBiometricMonitorViewController *_debugViewController;
    BOOL _deferredMatchUpdatePending;
    BOOL _deferredPresenceDetectUpdatePending;
    id <SBBiometricMonitorDataSource> _dataSource;
}

@property(retain, nonatomic) id <SBBiometricMonitorDataSource> dataSource; // @synthesize dataSource=_dataSource;
// - (void).cxx_destruct;
- (void)biometricMonitorDataSourcePoseUpdated:(id)arg1;
- (void)biometricMonitorDataSourcePresenceDetectionEnded:(id)arg1;
- (void)biometricMonitorDataSourcePresenceDetectionSucceeded:(id)arg1;
- (void)biometricMonitorDataSourcePresenceDetectionFailed:(id)arg1;
- (void)biometricMonitorDataSourcePresenceDetectionStarted:(id)arg1;
- (void)biometricMonitorDataSourceMatchingEnded:(id)arg1;
- (void)biometricMonitorDataSourceMatchingSucceeded:(id)arg1;
- (void)biometricMonitorDataSourceMatchingFailed:(id)arg1;
- (void)biometricMonitorDataSourceMatchingStarted:(id)arg1;
- (void)_cancelDeferredUpdatePresenceDetectState;
- (BOOL)_isDeferredPresenceDetectStateUpdatePending;
- (void)_deferredUpdatePresenceDetectState;
- (void)_cancelDeferredUpdateMatchState;
- (BOOL)_isDeferredMatchStateUpdatePending;
- (void)_deferredUpdateMatchState;
- (void)_doDeferredPresenceDetectUpdate;
- (void)_updatePresenceDetectState;
- (void)_doDeferredMatchStateUpdate;
- (void)_updateMatchState;
- (void)disable;
- (void)enable;
- (id)init;

@end

