//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSwitcherModifierAction.h>

@class SBAppLayout;

@interface SBBlurItemContainerSwitcherModifierAction : SBSwitcherModifierAction
{
    BOOL _shouldBlur;
    SBAppLayout *_appLayout;
}

@property(readonly, nonatomic) BOOL shouldBlur; // @synthesize shouldBlur=_shouldBlur;
@property(readonly, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
// - (void).cxx_destruct;
- (id)description;
- (long long)type;
- (id)initWithAppLayout:(id)arg1 shouldBlur:(BOOL)arg2;

@end

