//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>


@interface SBBouncingItem : NSObject <UIDynamicItem>
{
    CGRect _bounds;
    CGPoint _center;
    double _multiplier;
    id /* CDUnknownBlockType */ _translateBlock;
}

@property(copy) id /* CDUnknownBlockType */ translateBlock; // @synthesize translateBlock=_translateBlock;
@property double multiplier; // @synthesize multiplier=_multiplier;
// - (void).cxx_destruct;
@property(nonatomic) CGAffineTransform transform;
@property(readonly, nonatomic) CGRect bounds;
@property(nonatomic) CGPoint center;

@end

