//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIDynamicBehavior.h>


@class UIAttachmentBehavior, UICollisionBehavior, UIDynamicItemBehavior, UIGravityBehavior, _UIEdgeFeedbackGenerator;
@protocol UIDynamicItem;

@interface SBBounceBehavior : UIDynamicBehavior <UICollisionBehaviorDelegate>
{
    double _midwayPosition;
    double _completionThreshold;
    double _previousLinearVelocity;
    double _previousPreviousLinearVelocity;
    CGRect _targetFrame;
    id <UIDynamicItem> _item;
    UIDynamicItemBehavior *_bodyBehavior;
    UICollisionBehavior *_collisionBehavior;
    UIGravityBehavior *_gravityBehavior;
    UIDynamicItemBehavior *_pushBehavior;
    UIAttachmentBehavior *_draggingBehavior;
    double _gravity;
    double _velocity;
    double _elasticity;
    double _friction;
    double _resistance;
    double _minVelocityToAssist;
    double _maxVelocityToAssist;
    double _maxVelocityAssistance;
    _UIEdgeFeedbackGenerator *_hapticGenerator;
    UIEdgeInsets _boundaryInsets;
}

@property(nonatomic) UIEdgeInsets boundaryInsets; // @synthesize boundaryInsets=_boundaryInsets;
@property(retain, nonatomic) _UIEdgeFeedbackGenerator *hapticGenerator; // @synthesize hapticGenerator=_hapticGenerator;
@property(nonatomic) double maxVelocityAssistance; // @synthesize maxVelocityAssistance=_maxVelocityAssistance;
@property(nonatomic) double maxVelocityToAssist; // @synthesize maxVelocityToAssist=_maxVelocityToAssist;
@property(nonatomic) double minVelocityToAssist; // @synthesize minVelocityToAssist=_minVelocityToAssist;
@property(nonatomic) double resistance; // @synthesize resistance=_resistance;
@property(nonatomic) double friction; // @synthesize friction=_friction;
@property(nonatomic) double elasticity; // @synthesize elasticity=_elasticity;
@property(nonatomic) double velocity; // @synthesize velocity=_velocity;
@property(nonatomic) double gravity; // @synthesize gravity=_gravity;
// - (void).cxx_destruct;
- (BOOL)allowsAnimatorToStop;
- (double)_maxVelocityToAssist;
- (double)_minVelocityToAssist;
- (double)_velocityAssistance;
- (BOOL)_shouldAssistWithVelocity:(double)arg1;
- (double)_adjustedVelocity:(double)arg1;
- (double)_itemOriginY;
- (BOOL)_itemStopped;
- (BOOL)_itemCompleted;
- (BOOL)_itemPastMidway;
- (double)_percentRemaining;
- (double)_percentComplete;
- (void)_removeDraggingBehavior;
- (void)_beginInteraction;
- (void)finishInteraction;
- (void)finishInteractionWithVelocity:(CGPoint)arg1;
- (void)finishInteractionWithVelocity:(CGPoint)arg1 removingGravityAtMidway:(BOOL)arg2;
- (void)updateInteractionWithPoint:(CGPoint)arg1;
- (void)initiateInteractionFromPoint:(CGPoint)arg1;
- (void)bounce;
- (void)_setupCollisionBoundaries;
- (void)_frameCollisionBoundaryPoints:(CGPoint )arg1;
- (BOOL)_isGravityDown;
- (BOOL)isActive;
- (void)collisionBehavior:(id)arg1 beganContactForItem:(id)arg2 withBoundaryIdentifier:(id)arg3 atPoint:(CGPoint)arg4;
- (id)initWithItem:(id)arg1;
- (id)initWithItem:(id)arg1 targetFrame:(CGRect)arg2 feedbackGenerator:(id)arg3;

@end

