//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBLeafIcon.h>

@class NSURL, SBBookmark, UIWebClip;

@interface SBBookmarkIcon : SBLeafIcon
{
    SBBookmark *_bookmark;
}

@property(readonly, nonatomic) SBBookmark *bookmark; // @synthesize bookmark=_bookmark;
// - (void).cxx_destruct;
- (BOOL)isBookmarkIcon;
- (id)representedSceneIdentifier;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)applicationToLaunch;
@property(readonly, nonatomic) BOOL representsWebApp;
@property(readonly, nonatomic) BOOL displaysShareBookmarkShortcutItem;
@property(readonly, nonatomic) NSURL *launchURL;
@property(readonly, nonatomic) UIWebClip *webClip;
// - (id)copyWithZone:(_NSZone )arg1;
- (id)initWithBookmark:(id)arg1;

@end

