//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBApplicationIcon.h>

#import <SpringBoard/SBCalendarIconImageProviderDelegate-Protocol.h>

@class SBCalendarIconImageProvider;

@interface SBCalendarApplicationIcon : SBApplicationIcon <SBCalendarIconImageProviderDelegate>
{
    SBCalendarIconImageProvider *_imageProvider;
}

+ (BOOL)canGenerateIconsInBackground;
+ (Class)downloadingIconClass;
@property(readonly, nonatomic) SBCalendarIconImageProvider *imageProvider; // @synthesize imageProvider=_imageProvider;
// - (void).cxx_destruct;
- (void)calendarIconImageProviderHasChanged:(id)arg1;
- (id)unmaskedIconImageWithInfo:(struct SBIconImageInfo)arg1;
- (id)generateIconImageWithInfo:(struct SBIconImageInfo)arg1;
- (void)localeChanged;
- (id)initWithApplication:(id)arg1;

@end

