//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBDateTimeOverrideObserver-Protocol.h>

@class SBDateTimeController;
@protocol SBCalendarIconImageProviderDelegate;

@interface SBCalendarIconImageProvider : NSObject <SBDateTimeOverrideObserver>
{
    id <SBCalendarIconImageProviderDelegate> _delegate;
    SBDateTimeController *_dateTimeController;
}

@property(readonly, nonatomic) SBDateTimeController *dateTimeController; // @synthesize dateTimeController=_dateTimeController;
@property(nonatomic) __weak id <SBCalendarIconImageProviderDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)controller:(id)arg1 didChangeOverrideDateFromDate:(id)arg2;
- (id)unmaskedIconImageWithInfo:(struct SBIconImageInfo)arg1;
- (id)iconImageWithInfo:(struct SBIconImageInfo)arg1;
- (id)preparedISIcon;
- (void)_stopListeningForSignificantTimeChanges;
- (void)_startListeningForSignificantTimeChanges;
- (void)localeChanged;
- (void)reloadIconImage;
- (void)dealloc;
- (id)initWithDateTimeController:(id)arg1;
- (id)init;

@end

