//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBApplication.h>

@interface SBCameraApplication : SBApplication
{
    BOOL _hasPreHeatInFlight;
}

@property(nonatomic) BOOL hasPreHeatInFlight; // @synthesize hasPreHeatInFlight=_hasPreHeatInFlight;
- (void)_cancelPreheatForUserLaunchIfNecessary;
- (BOOL)icon:(id)arg1 launchFromLocation:(id)arg2 context:(id)arg3;
- (void)preHeatForUserLaunchIfNecessaryWithAbsoluteTime:(NSUInteger)arg1 andContinuousTime:(NSUInteger)arg2;

@end

