//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBToAppsWorkspaceTransaction.h>

@class SBDismissOverlaysAnimationController, SBTransientOverlayDismissAllWorkspaceTransaction;

@interface SBCoverSheetToAppsWorkspaceTransaction : SBToAppsWorkspaceTransaction
{
    SBDismissOverlaysAnimationController *_dismissOverlaysAnimationController;
    SBTransientOverlayDismissAllWorkspaceTransaction *_transientOverlayTransaction;
    BOOL _preservesBanners;
}

@property(nonatomic) BOOL preservesBanners; // @synthesize preservesBanners=_preservesBanners;
// - (void).cxx_destruct;
- (NSUInteger)_dismissOverlaysOptions;
- (void)_dismissOverlaysIfNeeded;
- (void)_begin;
- (id)initWithTransitionRequest:(id)arg1;

@end

