//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBDataPlanAlertItem.h>

@interface SBDataPlanDisableAlertItem : SBDataPlanAlertItem
{
}

- (void)_showSettings;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;

@end

