//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/CSEmergencyCalling-Protocol.h>
#import <SpringBoard/PTSettingsKeyObserver-Protocol.h>
#import <SpringBoard/SBLockScreenCallHandling-Protocol.h>

@class CSCoverSheetViewController, SBDashBoardEmergencyDialerViewController;

@interface SBDashBoardEmergencyDialerController : NSObject <PTSettingsKeyObserver, CSEmergencyCalling, SBLockScreenCallHandling>
{
    CSCoverSheetViewController *_coverSheetViewController;
    SBDashBoardEmergencyDialerViewController *_emergencyDialerViewController;
}

// - (void).cxx_destruct;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)exitEmergencyDialerAnimated:(BOOL)arg1;
- (void)emergencyDialerExitedWithError:(id)arg1;
- (void)launchInCallAlert;
- (void)launchEmergencyDialerAnimated:(BOOL)arg1;
- (void)launchEmergencyDialer;
- (BOOL)isMakingEmergencyCall;
- (void)dealloc;
- (id)initWithCoverSheetViewController:(id)arg1;

@end

