//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBBiometricUnlockBehavior-Protocol.h>
#import <SpringBoard/SBMesaUnlockTriggerDelegate-Protocol.h>

@class CSLockScreenPearlSettings, NSString, SBMesaUnlockTrigger;
@protocol SBBiometricUnlockBehaviorDelegate;

@interface SBDashBoardPearlUnlockBehavior : NSObject <SBMesaUnlockTriggerDelegate, SBBiometricUnlockBehavior>
{
    CSLockScreenPearlSettings *_pearlSettings;
    id <SBBiometricUnlockBehaviorDelegate> _biometricUnlockBehaviorDelegate;
    SBMesaUnlockTrigger *_trigger;
}

@property(retain, nonatomic, getter=_trigger, setter=_setTrigger:) SBMesaUnlockTrigger *trigger; // @synthesize trigger=_trigger;
@property(nonatomic) __weak id <SBBiometricUnlockBehaviorDelegate> biometricUnlockBehaviorDelegate; // @synthesize biometricUnlockBehaviorDelegate=_biometricUnlockBehaviorDelegate;
// - (void).cxx_destruct;
- (void)_handlePearlFailure;
- (id)_feedbackForBioUnlockEventThatWasSpontaneous:(BOOL)arg1;
- (id)_feedbackForPasscodeEvent;
- (id)_feedbackForFailureSettings:(id)arg1;
- (void)mesaUnlockTriggerFired:(id)arg1;
- (void)handleBiometricEvent:(NSUInteger)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (id)initWithPearlSettings:(id)arg1 andUnlockTrigger:(id)arg2;

@end

