//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBNotificationHomeAffordanceControllerClient-Protocol.h>

@protocol CSHomeGestureParticipating;

@interface SBDashBoardHomeAffordanceControllerClientBridge : NSObject <SBNotificationHomeAffordanceControllerClient>
{
    id <CSHomeGestureParticipating> _coverSheetHomeGestureParticipant;
}

// - (void).cxx_destruct;
- (void)homeGestureParticipantOwningHomeGestureDidChange:(id)arg1;
- (id)initWithCoverSheetHomeGestureParticipant:(id)arg1;

@end

