//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/SBIdleTimerObserving-Protocol.h>

@class NSMutableSet;
@protocol BSInvalidatable, SBDashBoardIdleTimerProviderDelegate, SBFIdleTimerBehaviorProviding, SBIdleTimer;

@interface SBDashBoardIdleTimerProvider : NSObject <SBIdleTimerObserving, BSDescriptionProviding>
{
    id <SBIdleTimer> _idleTimer;
    id <SBFIdleTimerBehaviorProviding> _idleTimerProvider;
    id <BSInvalidatable> _stateCaptureAssertion;
    NSMutableSet *_disabledIdleTimerAssertions;
    id <SBDashBoardIdleTimerProviderDelegate> _delegate;
}

@property(retain, nonatomic) id <SBIdleTimer> idleTimer; // @synthesize idleTimer=_idleTimer;
@property(nonatomic) __weak id <SBDashBoardIdleTimerProviderDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)_proposeIdleTimerBehavior:(id)arg1 forReason:(id)arg2;
- (void)_proposeEffectiveIdleTimerBehaviorForReason:(id)arg1;
- (id)_copyIdleTimerBehaviorForBehaviorProvider:(id)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (void)idleTimerDidWarn:(id)arg1;
- (void)idleTimerDidExpire:(id)arg1;
- (void)idleTimerDidRefresh:(id)arg1;
@property(readonly, nonatomic, getter=isIdleTimerEnabled) BOOL idleTimerEnabled;
- (BOOL)isDisabledAssertionActiveForReason:(id)arg1;
- (void)removeDisabledIdleTimerAssertionReason:(id)arg1;
- (void)addDisabledIdleTimerAssertionReason:(id)arg1;
- (id)effectiveIdleTimerBehavior;
- (void)updateIdleTimerWithIdleDimProvider:(id)arg1 reason:(id)arg2;
- (void)resetIdleTimer;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

