//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBScenePlaceholderContentViewProvider-Protocol.h>

@protocol SBScenePlaceholderContentViewProviderDelegate;

@interface SBDeviceApplicationSceneViewPlaceholderContentViewProvider : NSObject <SBScenePlaceholderContentViewProvider>
{
    id <SBScenePlaceholderContentViewProviderDelegate> _delegate;
}

@property(nonatomic) __weak id <SBScenePlaceholderContentViewProviderDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (NSUInteger)_contentTypeToSearchFromSceneHandle:(id)arg1 withContext:(id)arg2;
- (id)_loadLiveXIBViewForApplication:(id)arg1;
- (CGSize)_naturalSizeForOrientation:(long long)arg1 referenceSize:(CGSize)arg2;
- (BOOL)_checkApplicationRestorationState:(id)arg1 useSnapshot:(BOOL )arg2;
- (id)_contentViewFromSceneHandle:(id)arg1 displayConfiguration:(id)arg2 orientation:(long long)arg3 snapshot:(id)arg4 size:(CGSize)arg5 statusBarDescriptor:(id)arg6;
- (id)sceneView:(id)arg1 requestsPlaceholderContentViewWithContext:(id)arg2;
- (void)_snapshotsDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithApplication:(id)arg1;

@end

