//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBApplicationSceneViewControlling-Protocol.h>

@class SBDeviceApplicationSceneHandle, SBHomeGrabberView, SBSceneViewStatusBarAssertion;

@protocol SBDeviceApplicationSceneViewControlling <SBApplicationSceneViewControlling>
@property(readonly, nonatomic) SBHomeGrabberView *homeGrabberView;
@property(readonly, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle;
- (SBSceneViewStatusBarAssertion *)statusBarAssertionWithStatusBarHidden:(BOOL)arg1 atLevel:(NSUInteger)arg2;
@end

