//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>

@class NSString;

@interface SBDisplayItem : NSObject <NSCopying, BSDescriptionProviding>
{
    NSString *_uniqueStringRepresentation;
    id /* CDUnknownBlockType */ _sceneIdentifierFromBundleIdentifierGenerator;
    long long _type;
    NSString *_bundleIdentifier;
    NSString *_uniqueIdentifier;
}

+ (id)displayItemWithProtobufRepresentation:(id)arg1;
+ (id)applicationDisplayItemWithBundleIdentifier:(id)arg1 sceneIdentifier:(id)arg2;
+ (id)webAppDisplayItemWithWebAppIdentifier:(id)arg1;
+ (id)switcherServiceDisplayItemWithServiceIdentifier:(id)arg1;
+ (id)remoteAlertDisplayItemWithServiceBundleIdentifier:(id)arg1;
+ (id)homeScreenDisplayItem;
+ (id)displayItemWithType:(long long)arg1 bundleIdentifier:(id)arg2 uniqueIdentifier:(id)arg3;
@property(readonly, copy, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
// - (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (long long)compare:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSUInteger hash;
- (id)uniqueStringRepresentation;
- (id)_calculateUniqueStringRepresentation;
- (BOOL)isHomeScreenDisplayItem;
- (id)protobufRepresentation;
- (id)plistRepresentation;
@property(readonly, copy, nonatomic) NSString *webClipIdentifier;
- (id)_newSceneIdentifierForBundleIdentifier:(id)arg1;
- (id)_initWithLegacyPlistRepresentation:(id)arg1 sceneIdentifierFromBundleIdentifierGenerator:(id /* CDUnknownBlockType */)arg2;
- (id)initWithLegacyPlistRepresentation:(id)arg1;
- (id)_initWithArrayPlistRepresentation:(id)arg1;
- (id)_initWithDictionaryPlistRepresentation:(id)arg1;
- (id)_initWithPlistRepresentation:(id)arg1 sceneIdentifierFromBundleIdentifierGenerator:(id /* CDUnknownBlockType */)arg2;
- (id)initWithPlistRepresentation:(id)arg1;
// - (id)copyWithZone:(_NSZone )arg1;
- (id)initWithType:(long long)arg1 bundleIdentifier:(id)arg2 uniqueIdentifier:(id)arg3;
- (id)init;

@end

