//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBUIAnimationController.h>

@interface SBDismissOverlaysAnimationController : SBUIAnimationController
{
    NSUInteger _dismissOptions;
}

+ (NSUInteger)_overlaysToDismissForOptions:(NSUInteger)arg1;
+ (BOOL)willDismissOverlaysForDismissOptions:(NSUInteger)arg1;
@property(readonly, nonatomic) NSUInteger dismissOptions; // @synthesize dismissOptions=_dismissOptions;
- (id)animationSettings;
- (void)_startAnimation;
- (BOOL)_canBeInterrupted;
- (id)initWithTransitionContextProvider:(id)arg1 options:(NSUInteger)arg2;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

