//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MTMaterialShadowView, SBElasticSliderView;

@interface SBElasticSliderMaterialWrapperView : UIView
{
    UIView *_sliderWrapperView;
    UIView *_maskView;
    SBElasticSliderView *_sliderView;
    MTMaterialShadowView *_baseMaterialView;
    long long _shadowMode;
}

@property(nonatomic) long long shadowMode; // @synthesize shadowMode=_shadowMode;
@property(readonly, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(readonly, nonatomic) MTMaterialShadowView *baseMaterialView; // @synthesize baseMaterialView=_baseMaterialView;
@property(readonly, nonatomic) SBElasticSliderView *sliderView; // @synthesize sliderView=_sliderView;
// - (void).cxx_destruct;
- (void)_updateShadowMode;
- (void)_setContinuousCornerRadius:(double)arg1;
- (void)layoutSubviews;
- (id)init;

@end

