//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BaseBoard/BSAbstractDefaultDomain.h>

@interface SBExternalSettingsDefaults : BSAbstractDefaultDomain
{
}

+ (BOOL)__useDynamicMethodResolution;
@property(nonatomic, getter=isBadgedForSoftwareUpdate) BOOL badgedForSoftwareUpdate;
- (id)init;

@end

