//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSError, NSString;

@protocol SBFAuthenticationPolicy <NSObject>
- (void)wipeDeviceWithReason:(NSString *)arg1;
- (BOOL)usesSecureMode;
- (BOOL)shouldClearBlockStateOnSync;
- (BOOL)allowAuthenticationRevocation;

@optional
- (void)passcodeAuthenticationFailedWithError:(NSError *)arg1;
- (void)clearPasscodeCache;
- (void)cachePasscode:(NSString *)arg1;
@end

