//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBFluidSwitcherModifierTimelineViewController, UIWindow;

@interface SBFluidSwitcherModifierTimelineController : NSObject
{
    UIWindow *_window;
    SBFluidSwitcherModifierTimelineViewController *_rootViewController;
    BOOL _visible;
}

@property(nonatomic, getter=isVisible) BOOL visible; // @synthesize visible=_visible;
// - (void).cxx_destruct;
- (void)addEntry:(id)arg1;

@end

