//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBFluidSwitcherRootSwitcherModifier.h>

@class SBAppLayout;

@interface SBFloatingFluidSwitcherRootSwitcherModifier : SBFluidSwitcherRootSwitcherModifier
{
    BOOL _floatingSwitcherVisible;
    SBAppLayout *_activeAppLayout;
    long long _interfaceOrientation;
    long long _floatingConfiguration;
    CGRect _containerViewBounds;
}

@property(nonatomic) CGRect containerViewBounds; // @synthesize containerViewBounds=_containerViewBounds;
@property(nonatomic, getter=isFloatingSwitcherVisible) BOOL floatingSwitcherVisible; // @synthesize floatingSwitcherVisible=_floatingSwitcherVisible;
@property(nonatomic) long long floatingConfiguration; // @synthesize floatingConfiguration=_floatingConfiguration;
@property(nonatomic) long long interfaceOrientation; // @synthesize interfaceOrientation=_interfaceOrientation;
@property(retain, nonatomic) SBAppLayout *activeAppLayout; // @synthesize activeAppLayout=_activeAppLayout;
// - (void).cxx_destruct;
- (Class)_defaultMultitaskingModifierClass;
- (id)lowEndHardwareModifier;
- (id)tetheredInsertionModifierFortetheredInsertionEvent:(id)arg1;
- (id)tetheredRemovalModifierForTetheredRemovalEvent:(id)arg1;
- (id)insertionModifierForInsertionEvent:(id)arg1;
- (id)entityRemovalModifierForEvent:(id)arg1;
- (id)multitaskingModifierForEvent:(id)arg1;
- (id)floorModifierForTransitionEvent:(id)arg1;
- (id)appExposeModifierForAppExposeEvent:(id)arg1;
- (id)transitionModifierForMainTransitionEvent:(id)arg1;
- (id)gestureModifierForGestureEvent:(id)arg1;
- (id)newMultitaskingModifierFromMultitaskingModifier:(id)arg1;
- (id)appExposeAccessoryButtonsBundleIdentifier;
- (id)adjustedAppLayoutsForAppLayouts:(id)arg1;
- (id)handleEvent:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)init;

@end

