//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFTouchPassThroughView.h>

#import <SpringBoard/SBAppPlatterDragSourceViewProviding-Protocol.h>
#import <SpringBoard/SBFailureNotifyingTapGestureRecognizerDelegate-Protocol.h>

@class NSArray, NSString, SBAppSwitcherPageView, SBAppSwitcherSettings, SBFFluidBehaviorSettings, SBFailureNotifyingTapGestureRecognizer, SBFluidSwitcherIconOverlayView, SBFluidSwitcherItemContainerHeaderView, SBFluidSwitcherTouchPassThroughScrollView, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;
@protocol SBAppSwitcherPageContentView, SBFluidSwitcherItemContainerDelegate;

@interface SBFluidSwitcherItemContainer : SBFTouchPassThroughView <UIScrollViewDelegate, UIGestureRecognizerDelegate, SBFailureNotifyingTapGestureRecognizerDelegate, SBAppPlatterDragSourceViewProviding>
{
    SBAppSwitcherPageView *_pageView;
    id <SBFluidSwitcherItemContainerDelegate> _delegate;
    SBFluidSwitcherTouchPassThroughScrollView *_killScrollView;
    SBFluidSwitcherItemContainerHeaderView *_iconAndLabelHeader;
    SBFluidSwitcherIconOverlayView *_iconOverlayView;
    UIRectCornerRadii _contentCornerRadii;
    double _contentPageViewScale;
    double _titleOpacity;
    double _titleAndIconOpacity;
    UILongPressGestureRecognizer *_pressDownGestureRecognizer;
    UILongPressGestureRecognizer *_selectionHighlightGestureRecognizer;
    SBFailureNotifyingTapGestureRecognizer *_tapGestureRecognizer;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    SBFFluidBehaviorSettings *_squishSettings;
    SBAppSwitcherSettings *_settings;
    BOOL _sentKillRequest;
    CGPoint _highlightTapDownLocation;
    BOOL _highlighted;
    BOOL _animatingPageViewScale;
    double _killProgressForCurrentDecelerationTarget;
    BOOL _dragging;
    BOOL _clipsToUnobscuredMargin;
    BOOL _killable;
    BOOL _shouldScaleOverlayToFillBounds;
    BOOL _active;
    BOOL _visible;
    double _unobscuredMargin;
    NSUInteger _killAxis;
    double _minimumTranslationForKillingContainer;
    double _contentAlpha;
    NSString *_additionalDescriptionDebugText;
    NSArray *_headerItems;
}

+ (double)preferredRestingVisibleMarginForBounds:(CGRect)arg1;
@property(copy, nonatomic) NSArray *headerItems; // @synthesize headerItems=_headerItems;
@property(copy, nonatomic) NSString *additionalDescriptionDebugText; // @synthesize additionalDescriptionDebugText=_additionalDescriptionDebugText;
@property(nonatomic, getter=isVisible) BOOL visible; // @synthesize visible=_visible;
@property(nonatomic, getter=isActive) BOOL active; // @synthesize active=_active;
@property(nonatomic) double contentAlpha; // @synthesize contentAlpha=_contentAlpha;
@property(nonatomic) BOOL shouldScaleOverlayToFillBounds; // @synthesize shouldScaleOverlayToFillBounds=_shouldScaleOverlayToFillBounds;
@property(nonatomic) double minimumTranslationForKillingContainer; // @synthesize minimumTranslationForKillingContainer=_minimumTranslationForKillingContainer;
@property(nonatomic, getter=isKillable) BOOL killable; // @synthesize killable=_killable;
@property(nonatomic) NSUInteger killAxis; // @synthesize killAxis=_killAxis;
@property(nonatomic) BOOL clipsToUnobscuredMargin; // @synthesize clipsToUnobscuredMargin=_clipsToUnobscuredMargin;
@property(nonatomic, getter=isDragging) BOOL dragging; // @synthesize dragging=_dragging;
@property(nonatomic) double unobscuredMargin; // @synthesize unobscuredMargin=_unobscuredMargin;
@property(nonatomic) double contentPageViewScale; // @synthesize contentPageViewScale=_contentPageViewScale;
@property(nonatomic) double titleAndIconOpacity; // @synthesize titleAndIconOpacity=_titleAndIconOpacity;
@property(nonatomic) double titleOpacity; // @synthesize titleOpacity=_titleOpacity;
@property(nonatomic) UIRectCornerRadii contentCornerRadii; // @synthesize contentCornerRadii=_contentCornerRadii;
@property(nonatomic) __weak id <SBFluidSwitcherItemContainerDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (id)containerViewForBlurContentView;
- (id)initialRimShadowFilters;
- (id)initialDiffuseShadowFilters;
- (struct SBDragPreviewShadowParameters)initialRimShadowParameters;
- (struct SBDragPreviewShadowParameters)initialDiffuseShadowParameters;
- (id)initialCornerRadiusConfiguration;
- (id)sourceView;
- (BOOL)_scrollViewShouldPanGestureTryToBegin:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint )arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)gestureRecognizerTransitionedToFailed:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (CGAffineTransform)_squishedPageViewScaleTransform;
@property(nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)_handleSelectionHighlightGesture:(id)arg1;
- (void)_handlePageViewPressDown:(id)arg1;
- (void)_handlePageViewTap:(id)arg1;
- (void)_updateShadowVisibility;
- (id)_springLoadingEffectTargetView;
- (void)_updateHeaderAnimated:(BOOL)arg1;
- (double)_scaleTransformFactor;
- (double)_inverseScaleTransformFactor;
- (void)_setKillingDarkeningAlpha:(double)arg1;
- (double)_killingDarkeningAlpha;
- (BOOL)_isTitleIconVisible;
- (CGPoint)_CGPointFromScalarBasedOnKillAxis:(double)arg1;
- (CGSize)_CGSizeFromLengthBasedOnKillAxis:(double)arg1;
- (double)_CGPointXOrYBasedOnKillAxis:(CGPoint)arg1;
- (double)_CGSizeWidthOrHeightBasedOnKillAxis:(CGSize)arg1;
- (CGPoint)_contentOffsetAtRest;
- (void)_resetKillProgressScrollState;
- (CGSize)_overlayViewSize;
- (CGSize)_contentSizeForScrollView;
- (CGRect)_frameForPageView;
- (CGRect)_frameForScrollView;
- (void)_ensureSubviewOrder;
- (void)layoutSubviews;
- (BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic) BOOL isDeceleratingTowardsKillZone;
- (void)removeIconOverlay;
- (void)configureOverlayForIconZoomWithView:(id)arg1;
@property(retain, nonatomic) UIView<SBAppSwitcherPageContentView> *contentView;
@property(nonatomic) long long shadowStyle;
@property(nonatomic) double shadowOffset;
@property(nonatomic) double shadowAlpha;
- (CGPoint)_contentOffsetForKillingProgress:(double)arg1;
- (double)_killingProgressForContentOffset:(CGPoint)arg1;
@property(readonly, nonatomic) double killingProgress;
@property(nonatomic) double lighteningAlpha;
@property(nonatomic) double wallpaperOverlayAlpha;
@property(nonatomic) double darkeningAlpha;
- (void)_updatePageViewContentClippingFrame;
- (void)_updatePageViewContentViewClipping;
- (void)setContentOverlay:(id)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) UIView *contentOverlay;
@property(nonatomic) BOOL blocksContentViewTouches;
- (void)setHeaderItems:(id)arg1 animated:(BOOL)arg2;
@property(readonly, copy) NSString *description;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)prepareForReuse;
- (void)_addPageView;
- (id)_createScrollView;
- (id)initWithFrame:(CGRect)arg1 delegate:(id)arg2 active:(BOOL)arg3;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

