//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBAppLayout, SBFluidSwitcherPageContentViewProvider, SBTransientOverlayViewController, UIViewController;
@protocol SBAppSwitcherReusableSnapshotViewDelegate;

@protocol SBFluidSwitcherPageContentViewProviderDelegate <NSObject>
- (id <SBAppSwitcherReusableSnapshotViewDelegate>)delegateForForSnapshotPageViewFromProvider:(SBFluidSwitcherPageContentViewProvider *)arg1;
- (SBTransientOverlayViewController *)viewControllerForTransientOverlayAppLayout:(SBAppLayout *)arg1 fromProvider:(SBFluidSwitcherPageContentViewProvider *)arg2;
- (UIViewController *)containerViewControllerForPageViewFromProvider:(SBFluidSwitcherPageContentViewProvider *)arg1;
- (CGSize)sizeForAppLayout:(SBAppLayout *)arg1 fromProvider:(SBFluidSwitcherPageContentViewProvider *)arg2;
- (long long)orientationForPageViewFromProvider:(SBFluidSwitcherPageContentViewProvider *)arg1;
@end

