//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SiriUIFluidDismissalState-Protocol.h>

@interface SBFluidDismissalState : NSObject <SiriUIFluidDismissalState>
{
    double _backgroundWeighting;
    double _contentWeighting;
    long long _dismissalType;
    long long _transitionPhase;
    CGRect _contentRect;
}

@property(nonatomic) long long transitionPhase; // @synthesize transitionPhase=_transitionPhase;
@property(nonatomic) long long dismissalType; // @synthesize dismissalType=_dismissalType;
@property(nonatomic) CGRect contentRect; // @synthesize contentRect=_contentRect;
@property(nonatomic) double contentWeighting; // @synthesize contentWeighting=_contentWeighting;
@property(nonatomic) double backgroundWeighting; // @synthesize backgroundWeighting=_backgroundWeighting;

@end

