//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBFolderController, SBHIconManager;
@protocol SBViewControllerTransitionCoordinator;

@protocol SBFolderPresentationObserver <NSObject>
- (void)iconManager:(SBHIconManager *)arg1 willPerformTransitionWithFolder:(SBFolderController *)arg2 presenting:(BOOL)arg3 withTransitionCoordinator:(id <SBViewControllerTransitionCoordinator>)arg4;
@end

