//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBIconAccessoryInfoProvider-Protocol.h>

@class NSString;

@interface SBForceTouchAppIconInfoProvider : NSObject <SBIconAccessoryInfoProvider>
{
}

@property(readonly, nonatomic) long long continuityBadgeType;
@property(readonly, nonatomic, getter=isHighlighted) BOOL highlighted;
@property(readonly, copy, nonatomic) NSString *location;

@end

