//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBFWallpaperConfigurationManager;

@protocol SBFWallpaperConfigurationManagerDelegate <NSObject>
- (void)wallpaperConfigurationManager:(SBFWallpaperConfigurationManager *)arg1 didChangeWallpaperConfigurationForVariants:(long long)arg2;

@optional
- (BOOL)wallpaperConfigurationManager:(SBFWallpaperConfigurationManager *)arg1 isVideoSupportedForVariant:(long long)arg2;
@end

