//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSwitcherModifier.h>

#import <SpringBoard/SBGridSwitcherScrollProviding-Protocol.h>

@class SBAppLayout, SBGridLayoutSwitcherModifier, _SBGridFloorSwitcherModifier;
@protocol SBFluidSwitcherScrollProvidingDelegate;

@interface SBGridSwitcherModifier : SBSwitcherModifier <SBGridSwitcherScrollProviding>
{
    SBGridLayoutSwitcherModifier *_gridLayoutModifier;
    _SBGridFloorSwitcherModifier *_floorModifier;
    NSUInteger _ongoingAppLayoutRemovals;
    SBAppLayout *_activeAppLayoutInSwitcher;
    id <SBFluidSwitcherScrollProvidingDelegate> _scrollDelegate;
}

@property(nonatomic) __weak id <SBFluidSwitcherScrollProvidingDelegate> scrollDelegate; // @synthesize scrollDelegate=_scrollDelegate;
// - (void).cxx_destruct;
- (id)handleTapOutsideToDismissEvent:(id)arg1;
- (id)handleTapAppLayoutEvent:(id)arg1;
- (id)handleRemovalEvent:(id)arg1;
- (id)handleMainTransitionEvent:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
@property(readonly, nonatomic) double effectiveHorizontalSpacing;
@property(readonly, nonatomic) NSUInteger numberOfRows;
- (id)gridLayoutModifier;
- (void)didMoveToParentModifier:(id)arg1;

@end

