//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBHardwareButtonGestureParameters;
@protocol SBHardwareButtonGestureParametersObserver;

@protocol SBHardwareButtonGestureParametersProvider <NSObject>
@property(readonly, nonatomic) SBHardwareButtonGestureParameters *hardwareButtonGestureParameters;
- (void)removeHardwareButtonGestureParametersObserver:(id <SBHardwareButtonGestureParametersObserver>)arg1;
- (void)addHardwareButtonGestureParametersObserver:(id <SBHardwareButtonGestureParametersObserver>)arg1;
@end

