//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>
#include <IOKit/hid/IOHIDEvent.h>   
#import <SpringBoard/SBHardwareButtonGestureParametersObserver-Protocol.h>

@class BKSButtonHapticsDefinition, NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, SBHardwareButtonGestureParameters, SBHomeHardwareButtonActions, SBHomeHardwareButtonGestureRecognizerConfiguration, SBNotificationBannerDestination, UIGestureRecognizer;
@protocol BSInvalidatable;

@interface SBHomeHardwareButton : NSObject <UIGestureRecognizerDelegate, SBHardwareButtonGestureParametersObserver>
{
    id <BSInvalidatable> _fingerDetectEnabledAssertion;
    NSMutableSet *_hintSuppressionAssertions;
    NSMutableOrderedSet *_longPressDurationAssertions;
    BOOL _longPressDidOccur;
    SBNotificationBannerDestination *_bannerDestination;
    SBHomeHardwareButtonActions *_buttonActions;
    SBHardwareButtonGestureParameters *_buttonGestureParameters;
    SBHomeHardwareButtonGestureRecognizerConfiguration *_gestureRecognizerConfiguration;
    UIGestureRecognizer *_screenshotGestureRecognizer;
    long long _homeButtonType;
    long long _maximumPressCount;
    long long _maximumTapCount;
    NSMutableDictionary *_emulatedPerSenderDownCount;
    BKSButtonHapticsDefinition *_buttonDefinition;
}

@property(retain, nonatomic) BKSButtonHapticsDefinition *buttonDefinition; // @synthesize buttonDefinition=_buttonDefinition;
@property(retain, nonatomic) NSMutableDictionary *emulatedPerSenderDownCount; // @synthesize emulatedPerSenderDownCount=_emulatedPerSenderDownCount;
@property(nonatomic) BOOL longPressDidOccur; // @synthesize longPressDidOccur=_longPressDidOccur;
@property(nonatomic) long long maximumTapCount; // @synthesize maximumTapCount=_maximumTapCount;
@property(nonatomic) long long maximumPressCount; // @synthesize maximumPressCount=_maximumPressCount;
@property(nonatomic) long long homeButtonType; // @synthesize homeButtonType=_homeButtonType;
@property(nonatomic) __weak UIGestureRecognizer *screenshotGestureRecognizer; // @synthesize screenshotGestureRecognizer=_screenshotGestureRecognizer;
@property(retain, nonatomic) SBHomeHardwareButtonGestureRecognizerConfiguration *gestureRecognizerConfiguration; // @synthesize gestureRecognizerConfiguration=_gestureRecognizerConfiguration;
@property(retain, nonatomic) SBHardwareButtonGestureParameters *buttonGestureParameters; // @synthesize buttonGestureParameters=_buttonGestureParameters;
@property(retain, nonatomic) SBHomeHardwareButtonActions *buttonActions; // @synthesize buttonActions=_buttonActions;
@property(nonatomic) __weak SBNotificationBannerDestination *bannerDestination; // @synthesize bannerDestination=_bannerDestination;
// - (void).cxx_destruct;
- (BOOL)_isMenuDoublePressAllowed:(id )arg1;
- (BOOL)_isMenuDoublePressDisabled;
- (void)_cancelGestureRecognizer:(id)arg1;
- (void)doubleTapUp:(id)arg1;
- (void)triplePressUp:(id)arg1;
- (void)doublePressUp:(id)arg1;
- (void)doublePressDown:(id)arg1;
- (BOOL)_processDoubleDownAndDoubleUpSimultaneously;
- (void)longPress:(id)arg1;
- (void)singlePressUp:(id)arg1;
- (void)acceleratedSinglePressUp:(id)arg1;
- (void)_singlePressUp:(id)arg1;
- (void)initialButtonUp:(id)arg1;
- (void)initialButtonDown:(id)arg1;
- (BOOL)emulateHomeButtonEventsIfNeeded:(IOHIDEventRef)arg1;
- (void)_terminateHomeButtonEventAtCount:(long long)arg1;
- (BOOL)_longPressGestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)_acceleratedSinglePressRecognizerShouldBegin;
- (BOOL)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
@property(readonly, nonatomic) BOOL supportsAcceleratedAppDismiss;
@property(readonly, nonatomic, getter=isButtonDown) BOOL buttonDown;
@property(nonatomic) long long hapticType;
- (void)removeLongPressDurationAssertion:(id)arg1;
- (void)addLongPressDurationAssertion:(id)arg1;
- (void)removeHintSuppressionAssertion:(id)arg1;
- (void)addHintSuppressionAssertion:(id)arg1;
- (void)cancelLongPress;
- (void)screenshotRecognizerDidRecognize:(id)arg1;
- (void)performAfterMenuButtonUpIsHandledUsingBlock:(id /* CDUnknownBlockType */)arg1;
- (void)performWhenMenuButtonIsUpUsingBlock:(id /* CDUnknownBlockType */)arg1;
- (void)_reconfigureGestureRecognizersForNewMaximumPressCount:(long long)arg1 oldMaximumPressCount:(long long)arg2;
- (void)_reconfigureGestureRecognizersForNewMaximumTapCount:(long long)arg1 oldMaximumTapCount:(long long)arg2;
- (void)_createGestureRecognizersWithConfiguration:(id)arg1;
- (void)_reconfigureHomeButton;
- (void)_startObservingReconfigurationTriggers;
- (void)provider:(id)arg1 didUpdateButtonGestureParameters:(id)arg2;
- (void)_setFingerDetectionEnabled:(BOOL)arg1;
- (void)configureForwardingToLockButton:(id)arg1;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeButtonType:(long long)arg2 buttonActions:(id)arg3 gestureRecognizerConfiguration:(id)arg4;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeButtonType:(long long)arg2;

@end

