//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBFStatusBarLegibilityView;

@interface SBHomeScreenView : UIView
{
    SBFStatusBarLegibilityView *_statusBarLegibilityView;
}

@property(readonly, nonatomic) SBFStatusBarLegibilityView *statusBarLegibilityView; // @synthesize statusBarLegibilityView=_statusBarLegibilityView;
// - (void).cxx_destruct;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)setFrame:(CGRect)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

