//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBHomeScreenTodayViewController;

@protocol SBHomeScreenTodayViewControllerDelegate <NSObject>
- (void)todayViewControllerDidFocusSearchField:(SBHomeScreenTodayViewController *)arg1;
- (void)todayViewController:(SBHomeScreenTodayViewController *)arg1 didEndInteractivePullToSearchSuccessfully:(BOOL)arg2;
- (void)todayViewController:(SBHomeScreenTodayViewController *)arg1 didUpdateInteractivePullToSearchWithProgress:(double)arg2;
- (void)todayViewControllerDidBeginInteractivePullToSearch:(SBHomeScreenTodayViewController *)arg1;
- (BOOL)todayViewControllerCanBeginInteractivePullToSearch:(SBHomeScreenTodayViewController *)arg1;
@end

