//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableSet, SBFluidSwitcherAnimationSettings;
@protocol SBHomeScreenBackdropViewBaseDelegate;

@interface SBHomeScreenBackdropViewBase : UIView
{
    NSMutableSet *_backdropViewRequiringReasons;
    NSMutableSet *_liveBackdropViewRequiringReasons;
    SBFluidSwitcherAnimationSettings *_animationSettings;
    id <SBHomeScreenBackdropViewBaseDelegate> _delegate;
}

@property(nonatomic) __weak id <SBHomeScreenBackdropViewBaseDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (id)backdropBlurSettings;
- (BOOL)requiresLiveBackdropView;
- (BOOL)requiresBackdropView;
- (void)cancelInProcessAnimations;
- (BOOL)isOpaque;
- (void)setBlurProgress:(double)arg1 behaviorMode:(long long)arg2 completion:(id /* CDUnknownBlockType */)arg3;
- (void)endRequiringLiveBackdropViewForReason:(id)arg1;
- (void)endRequiringBackdropViewForReason:(id)arg1;
- (void)beginRequiringLiveBackdropViewForReason:(id)arg1;
- (void)beginRequiringBackdropViewForReason:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

