//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFTouchPassThroughViewController.h>

#import <SpringBoard/SBHUDViewControlling-Protocol.h>

@class NSString, UIImage, UIImageView, UIView, _UIBackdropView;

@interface SBHUDViewController : SBFTouchPassThroughViewController <UIViewControllerTransitioningDelegate, SBHUDViewControlling>
{
    BOOL _showsProgress;
    UIImage *_image;
    double _progress;
    NSString *_title;
    NSString *_subtitle;
    double _visibilityProgress;
    UIView *_hudView;
    UIView *_blockView;
    _UIBackdropView *_backdropView;
    UIImageView *_backdropMaskImageView;
}

+ (double)progressIndicatorStep;
@property(readonly, nonatomic) UIImageView *backdropMaskImageView; // @synthesize backdropMaskImageView=_backdropMaskImageView;
@property(readonly, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(readonly, nonatomic) UIView *blockView; // @synthesize blockView=_blockView;
@property(readonly, nonatomic) UIView *hudView; // @synthesize hudView=_hudView;
@property(nonatomic) double visibilityProgress; // @synthesize visibilityProgress=_visibilityProgress;
@property(nonatomic) BOOL showsProgress; // @synthesize showsProgress=_showsProgress;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
// - (void).cxx_destruct;
- (void)dismissAnimatedWithCompletion:(id /* CDUnknownBlockType */)arg1;
- (BOOL)definesAnimatedDismissal;
- (void)_rotateToInterfaceOrientation:(long long)arg1;
- (void)_updateBlockView;
- (id)_blockColorForValue:(float)arg1;
- (void)_updateBackdropMask;
- (BOOL)displaysLabel;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;

@end

