//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBSoftLockoutControllerDelegate-Protocol.h>

@class SBFMobileKeyBag, SBSoftLockoutController;

@interface SBiCloudPasscodeRequirementLockoutController : NSObject <SBSoftLockoutControllerDelegate>
{
    SBSoftLockoutController *_lockOutController;
    SBFMobileKeyBag *_mobileKeybag;
    BOOL _providedPasscode;
}

// - (void).cxx_destruct;
- (BOOL)_deviceHasComplexPasscode;
- (BOOL)requiresLockout;
- (void)noteAuthenticationSucceededWithPasscode:(id)arg1;
@property(readonly, nonatomic) BOOL desiresPasscode;
- (void)dealloc;
- (id)initWithLockScreenManager:(id)arg1 mobileKeyBag:(id)arg2;

@end

