//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/SBFIdleTimerBehaviorProviding-Protocol.h>

@class NSString;

@interface SBIdleTimerBehavior : NSObject <SBFIdleTimerBehaviorProviding, BSDescriptionProviding>
{
    long long _idleWarnMode;
    long long _idleTimerMode;
    long long _idleTimerDuration;
    double _customIdleWarningTimeout;
    double _customIdleExpirationTimeout;
}

+ (id)behaviorForBehaviorProvider:(id)arg1;
+ (id)disabledBehavior;
+ (id)autoLockBehavior;
+ (id)lockScreenBehavior;
+ (id)defaultBehavior;
@property(readonly, nonatomic) double customIdleExpirationTimeout; // @synthesize customIdleExpirationTimeout=_customIdleExpirationTimeout;
@property(readonly, nonatomic) double customIdleWarningTimeout; // @synthesize customIdleWarningTimeout=_customIdleWarningTimeout;
@property(readonly, nonatomic) long long idleTimerDuration; // @synthesize idleTimerDuration=_idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode; // @synthesize idleTimerMode=_idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode; // @synthesize idleWarnMode=_idleWarnMode;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (id)_initWithBehaviorProvider:(id)arg1;
- (id)_initWithDuration:(long long)arg1 mode:(long long)arg2 warnMode:(long long)arg3;

@end

