//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBTransitionSwitcherModifierEvent.h>

@interface SBInlineTransitionSwitcherModifierEvent : SBTransitionSwitcherModifierEvent
{
    NSUInteger _scrollAxis;
    double _cardScale;
    CGSize _fixedCardSize;
}

@property(nonatomic) CGSize fixedCardSize; // @synthesize fixedCardSize=_fixedCardSize;
@property(nonatomic) double cardScale; // @synthesize cardScale=_cardScale;
@property(nonatomic) NSUInteger scrollAxis; // @synthesize scrollAxis=_scrollAxis;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (long long)type;

@end

