//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBTransitionSwitcherModifier.h>

@class SBAppLayout, SBSwitcherModifier;

@interface SBInlineGridToFullScreenSwitcherModifier : SBTransitionSwitcherModifier
{
    SBAppLayout *_fullScreenAppLayout;
    SBSwitcherModifier *_multitaskingModifier;
    UIRectCornerRadii _fullScreenCornerRadii;
    BOOL _dimInactiveCards;
}

@property(readonly, nonatomic) SBSwitcherModifier *multitaskingModifier; // @synthesize multitaskingModifier=_multitaskingModifier;
@property(readonly, nonatomic) SBAppLayout *fullScreenAppLayout; // @synthesize fullScreenAppLayout=_fullScreenAppLayout;
// - (void).cxx_destruct;
- (double)_unselectedCardScale;
- (BOOL)_isIndexFullScreenAppLayout:(NSUInteger)arg1;
- (id)appLayoutToScrollToBeforeTransitioning;
- (id)topMostAppLayouts;
- (BOOL)isContentStatusBarVisibleForIndex:(NSUInteger)arg1;
- (BOOL)isContainerStatusBarVisible;
- (id)layoutSettings;
- (long long)liveContentRasterizationStyle;
- (double)backdropBlurProgress;
- (double)dimmingAlpha;
- (long long)backdropBlurType;
- (UIRectCornerRadii)cardCornerRadiiForIndex:(NSUInteger)arg1;
- (double)darkeningAlphaForIndex:(NSUInteger)arg1;
- (double)titleOpacityForIndex:(NSUInteger)arg1;
- (double)opacityForIndex:(NSUInteger)arg1;
- (double)reopenClosedWindowsButtonScale;
- (double)reopenClosedWindowsButtonAlpha;
- (double)plusButtonAlpha;
- (long long)plusButtonStyle;
- (long long)appExposeAccessoryButtonsOverrideUserInterfaceStyle;
- (id)appExposeAccessoryButtonsBundleIdentifier;
- (double)scaleForIndex:(NSUInteger)arg1;
- (BOOL)isIndexVisible:(NSUInteger)arg1;
- (CGRect)frameForIndex:(NSUInteger)arg1;
- (id)transitionWillBegin;
- (id)initWithTransitionID:(id)arg1 fullScreenAppLayout:(id)arg2 multitaskingModifier:(id)arg3 fullscreenCornerRadii:(UIRectCornerRadii)arg4 dimInactiveCards:(BOOL)arg5;

@end

