//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBTestRecipe-Protocol.h>

@class SBInsecureDrawingAlertItem;

@interface SBInsecureDrawingAlertItemTestRecipe : NSObject <SBTestRecipe>
{
    SBInsecureDrawingAlertItem *_alertItem;
}

+ (void)load;
// - (void).cxx_destruct;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (id)title;

@end

