//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface SBInteractiveScreenshotGestureMultiPartAnimation : NSObject
{
    id /* CDUnknownBlockType */ _completionHandler;
    NSMutableArray *_pendingAnimationIdentifiers;
}

// - (void).cxx_destruct;
- (void)completeAnimationWithIdentifier:(id)arg1 finished:(BOOL)arg2 retargeted:(BOOL)arg3;
- (void)beginAnimationWithIdentifier:(id)arg1;
- (id)initWithCompletionHandler:(id /* CDUnknownBlockType */)arg1;

@end

