//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIWindow;

@interface SBKeyboardHomeAffordanceAssertion : NSObject
{
    double _additionalEdgeMargin;
    UIWindow *_sourceWindow;
}

+ (id)assertionForGestureWindow:(id)arg1;
@property(nonatomic) __weak UIWindow *sourceWindow; // @synthesize sourceWindow=_sourceWindow;
@property(nonatomic) double additionalEdgeMargin; // @synthesize additionalEdgeMargin=_additionalEdgeMargin;
// - (void).cxx_destruct;
- (void)invalidate;
- (void)dealloc;
- (id)initWithGestureWindow:(id)arg1;

@end

