//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/SBAppPlatterDragSourceViewProviding-Protocol.h>

@class FBDisplayLayoutElement, FBSDisplayIdentity, SBLayoutElement, SBLayoutState, SBOrientationTransformWrapperView, UIView;

@interface SBLayoutElementViewController : UIViewController <SBAppPlatterDragSourceViewProviding>
{
    SBOrientationTransformWrapperView *_contentWrapperView;
    FBDisplayLayoutElement *_displayLayoutElement;
    BOOL _isViewVisible;
    BOOL _isTransitioningVisibility;
    BOOL _dragging;
    UIView *_contentContainerView;
    FBSDisplayIdentity *_displayIdentity;
    SBLayoutElement *_layoutElement;
    SBLayoutState *_layoutState;
    NSUInteger _supportedContentInterfaceOrientations;
    long long _contentWrapperInterfaceOrientation;
    CGRect _referenceFrame;
}

@property(nonatomic) long long contentWrapperInterfaceOrientation; // @synthesize contentWrapperInterfaceOrientation=_contentWrapperInterfaceOrientation;
@property(readonly, nonatomic) NSUInteger supportedContentInterfaceOrientations; // @synthesize supportedContentInterfaceOrientations=_supportedContentInterfaceOrientations;
@property(readonly, nonatomic) CGRect referenceFrame; // @synthesize referenceFrame=_referenceFrame;
@property(readonly, nonatomic) SBLayoutState *layoutState; // @synthesize layoutState=_layoutState;
@property(readonly, nonatomic) SBLayoutElement *layoutElement; // @synthesize layoutElement=_layoutElement;
@property(readonly, nonatomic) FBSDisplayIdentity *displayIdentity; // @synthesize displayIdentity=_displayIdentity;
@property(nonatomic, getter=isDragging) BOOL dragging; // @synthesize dragging=_dragging;
@property(readonly, nonatomic) UIView *_contentContainerView; // @synthesize _contentContainerView;
// - (void).cxx_destruct;
- (id)containerViewForBlurContentView;
- (id)initialRimShadowFilters;
- (id)initialDiffuseShadowFilters;
- (struct SBDragPreviewShadowParameters)initialRimShadowParameters;
- (struct SBDragPreviewShadowParameters)initialDiffuseShadowParameters;
- (id)initialCornerRadiusConfiguration;
- (id)sourceView;
@property(readonly, nonatomic) BOOL _shouldDisplayLayoutElementBecomeActive;
- (id)_newDisplayLayoutElementForEntity:(id)arg1;
- (void)_updateDisplayLayoutElementWithBuilder:(id /* CDUnknownBlockType */)arg1;
- (void)_updateDisplayLayoutElementVisibility;
- (void)didEndTransitionToVisible:(BOOL)arg1;
- (void)willBeginTransitionToVisible:(BOOL)arg1;
- (void)prepareForReuse;
- (id)animationControllerForTransitionRequest:(id)arg1;
- (void)configureWithWorkspaceEntity:(id)arg1 forLayoutElement:(id)arg2 layoutState:(id)arg3 referenceFrame:(CGRect)arg4;
- (void)invalidate;
@property(readonly, nonatomic) BOOL supportsReuse;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithDisplayIdentity:(id)arg1;
- (id)mainWorkspaceApplicationSceneLayoutElementViewController;

@end

