//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBLockScreenViewControllerBase.h>

#import <SpringBoard/SBLockScreenBatteryChargingViewControllerDelegate-Protocol.h>
#import <SpringBoard/SBLockScreenPluginManagerDelegate-Protocol.h>
#import <SpringBoard/SBLoginAppSceneHosterDelegate-Protocol.h>
#import <SpringBoard/SBWallpaperObserver-Protocol.h>

@class NSHashTable, NSMutableSet, SBAppStatusBarSettingsAssertion, SBLockScreenBatteryChargingViewController, SBLockScreenPluginManager, SBLockScreenTemperatureWarningViewController, SBLoginAppContainerPluginWrapperViewController, SBWallpaperController;
@protocol BSInvalidatable, SBLoginAppSceneHoster;

@interface SBLoginAppContainerViewController : SBLockScreenViewControllerBase <SBLockScreenBatteryChargingViewControllerDelegate, SBLoginAppSceneHosterDelegate, SBWallpaperObserver, SBLockScreenPluginManagerDelegate>
{
    id <SBLoginAppSceneHoster> _sceneHoster;
    SBLockScreenBatteryChargingViewController *_batteryChargingViewController;
    SBLockScreenTemperatureWarningViewController *_thermalWarningViewController;
    SBLoginAppContainerPluginWrapperViewController *_pluginWrapperViewController;
    SBAppStatusBarSettingsAssertion *_statusBarAssertion;
    NSMutableSet *_showStatusBarReasons;
    id <BSInvalidatable> _deferOrientationUpdatesAssertion;
    long long _idleTimerMode;
    SBLockScreenPluginManager *_pluginManager;
    SBWallpaperController *_wallpaperController;
    NSHashTable *_observers;
}

// - (void).cxx_destruct;
- (id)coordinatorRequestedIdleTimerBehavior:(id)arg1;
- (BOOL)shouldAutoUnlockForSource:(int)arg1;
- (BOOL)pluginManager:(id)arg1 plugin:(id)arg2 handleAction:(id)arg3;
- (void)pluginManager:(id)arg1 displayedPluginDidUpdateAppearance:(id)arg2;
- (void)pluginManager:(id)arg1 displayedPluginDidChangeFromPlugin:(id)arg2 toPlugin:(id)arg3;
- (void)pluginManager:(id)arg1 activePluginDidChange:(id)arg2;
- (void)pluginManager:(id)arg1 willUnloadPlugin:(id)arg2;
- (void)pluginManager:(id)arg1 didLoadPlugin:(id)arg2;
- (void)_updateLegibility;
- (void)wallpaperDidChangeForVariant:(long long)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(long long)arg2;
- (void)_showOrHideThermalTrapUIAnimated:(BOOL)arg1;
- (void)chargingViewControllerFadedOutContent:(id)arg1;
- (void)_cleanupBatteryChargingViewWithAnimationDuration:(double)arg1;
- (void)_fadeViewsForChargingViewVisible:(BOOL)arg1;
- (void)_updateBatteryChargingViewAnimated:(BOOL)arg1;
- (void)_removeBatteryChargingView;
- (void)_addBatteryChargingView;
- (void)_handleBacklightFadeEnded;
- (void)sceneUpdatedWallpaperMode:(NSUInteger)arg1;
- (void)sceneUpdatedRotationMode:(long long)arg1;
- (void)sceneUpdatedStatusBarUserName:(id)arg1;
- (void)sceneUpdatedIdleTimerMode:(long long)arg1;
- (void)sceneInvalidated;
- (void)_setupLoginScene;
- (void)_reallyRelinquishStatusBarAssertion;
- (void)_reallyAcquireStatusBarAssertionIfNecessaryInitiallyVisible:(BOOL)arg1;
- (id)_statusBarSettingsAssertion;
- (id)_hostedSceneIdentifier;
- (id)_hostedAppView;
- (id)_hostedAppBundleID;
- (void)_killLoginApp;
- (void)_setupLoginAppHosting;
- (BOOL)suppressesControlCenter;
- (void)prepareForUIUnlock;
- (void)prepareForUILock;
- (BOOL)suppressesScreenshots;
- (id)_displayLayoutElementIdentifier;
- (BOOL)shouldDisableALS;
- (BOOL)shouldShowLockStatusBarTime;
- (BOOL)handleVolumeDownButtonPress;
- (BOOL)handleVolumeUpButtonPress;
- (BOOL)handleHomeButtonDoublePress;
- (void)disableLockScreenPluginWithContext:(id)arg1;
- (void)enableLockScreenPluginWithContext:(id)arg1;
- (void)startLockScreenFadeInAnimationForSource:(int)arg1;
- (void)noteDeviceBlockedStatusUpdated;
- (BOOL)requiresPasscodeInputForUIUnlockFromSource:(int)arg1 withOptions:(id)arg2;
- (BOOL)canBeDeactivatedForUIUnlockFromSource:(int)arg1;
- (BOOL)willUIUnlockFromSource:(int)arg1;
- (BOOL)_canShowWhileLocked;
- (void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)loginContainerView;
- (void)removeLoginObserver:(id)arg1;
- (void)addLoginObserver:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 sceneHoster:(id)arg3 wallpaperController:(id)arg4;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)_initWithSceneHoster:(id)arg1 wallpaperController:(id)arg2;

@end

