//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/PTSettingsKeyObserver-Protocol.h>

@class CSLockScreenSettings, PCPersistentTimer, PTToggleTestRecipe, SBMediaController;
@protocol SBLockScreenNowPlayingControllerDelegate;

@interface SBLockScreenNowPlayingController : NSObject <PTSettingsKeyObserver>
{
    SBMediaController *_mediaController;
    PCPersistentTimer *_disableTimer;
    CSLockScreenSettings *_testSettings;
    PTToggleTestRecipe *_testRecipe;
    BOOL _enabled;
    long long _currentState;
    id <SBLockScreenNowPlayingControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBLockScreenNowPlayingControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long currentState; // @synthesize currentState=_currentState;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
// - (void).cxx_destruct;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)_disableTimerFired;
- (void)_invalidateDisableTimer;
- (void)_startDisableTimer;
- (void)_updateToState:(long long)arg1;
- (void)_updateNowPlayingPlugin;
- (void)_removeObservers;
- (void)_addObservers;
- (BOOL)_isMediaRecentlyActive;
- (double)_timeoutInterval;
- (BOOL)isNowPlayingActive;
- (void)dealloc;
- (id)initWithMediaController:(id)arg1;

@end

