//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface SBLockScreenActionManager : NSObject
{
    NSMutableDictionary *_actionProviders;
}

@property(retain, nonatomic) NSMutableDictionary *actionProviders; // @synthesize actionProviders=_actionProviders;
// - (void).cxx_destruct;
- (void)_clearActionOnAllProviders;
- (void)runUnlockAction;
- (id)currentLockScreenActionContextActionSource:(NSUInteger )arg1;
- (id)currentLockScreenActionContext;
- (void)registerLockScreenActionProvider:(id)arg1 forSource:(NSUInteger)arg2;
- (id)init;

@end

