//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SBDismissOnlyAlertItem;

@interface SBLockdownManager : NSObject
{
    int _state;
    BOOL _settingUpActivationState;
    SBDismissOnlyAlertItem *_activatingAlertItem;
    NSString *_unqiueDeviceIdentifier;
}

+ (BOOL)_isDeveloperDevice;
+ (id)sharedInstance;
// - (void).cxx_destruct;
- (int)lockdownState;
- (BOOL)brickedDevice;
- (void)_setupActivationState;
- (void)_resetActivationState;
- (id)init;

@end

