//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@protocol SBLockScreenBacklightControlling <NSObject>
@property(nonatomic) double backlightLevel;
- (BOOL)shouldDisableALS;
- (void)startLockScreenFadeInAnimationForSource:(int)arg1;
- (void)setInScreenOffMode:(BOOL)arg1 forAutoUnlock:(BOOL)arg2 fromUnlockSource:(int)arg3;
- (void)setInScreenOffMode:(BOOL)arg1;
- (BOOL)isInScreenOffMode;
@end

