//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSString;

@protocol SBMainDisplayInterfaceOrientationSource <NSObject>
@property(readonly, nonatomic) double orientationSourceLevel;
@property(readonly, nonatomic, getter=isActive) BOOL active;
@property(readonly, nonatomic) long long activeInterfaceOrientation;

@optional
@property(readonly, copy, nonatomic) NSString *orientationSourceDescription;
@end

