//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSceneLayoutViewController.h>

#import <SpringBoard/PTSettingsKeyObserver-Protocol.h>
#import <SpringBoard/SBDeviceApplicationSceneStatusBarBreadcrumbProviderObserver-Protocol.h>
#import <SpringBoard/SBMainDisplaySceneLayoutStatusBarViewDataSource-Protocol.h>
#import <SpringBoard/SBSceneHandleObserver-Protocol.h>
#import <SpringBoard/TFBetaLaunchHandleActivationDelegate-Protocol.h>

@class FBScene, NSArray, NSLayoutConstraint, NSMutableSet, NSObject, NSString, SBFHomeGrabberSettings, SBHomeGrabberRotationView, SBHomeGrabberView, SBKeyboardHomeAffordanceAssertion, SBMainDisplaySceneLayoutGestureManager, SBMainDisplaySceneLayoutStatusBarView, SBOrientationTransformWrapperView, SBSceneHandleBlockObserver, SBSeparatorView, UIApplicationSceneClientSettingsDiffInspector, UIView;
@protocol BSInvalidatable, OS_dispatch_queue;

@interface SBMainDisplaySceneLayoutViewController : SBSceneLayoutViewController <SBMainDisplaySceneLayoutStatusBarViewDataSource, PTSettingsKeyObserver, SBSceneHandleObserver, TFBetaLaunchHandleActivationDelegate, SBDeviceApplicationSceneStatusBarBreadcrumbProviderObserver>
{
    SBMainDisplaySceneLayoutGestureManager *_gestureManager;
    NSMutableSet *_pushPopTransformReasons;
    NSMutableSet *_pushPopWallpaperReasons;
    BOOL _showsPushInWallpaper;
    SBOrientationTransformWrapperView *_contentWrapperView;
    SBMainDisplaySceneLayoutStatusBarView *_statusBarView;
    UIView *_contentView;
    SBSeparatorView *_separatorView;
    id _keyboardWillChangeFrameObserver;
    double _separatorViewKeyboardMargin;
    SBFHomeGrabberSettings *_homeGrabberSettings;
    SBSceneHandleBlockObserver *_sceneHandleObserver;
    UIApplicationSceneClientSettingsDiffInspector *_clientSettingsInspector;
    BOOL _isKeyboardShowing;
    FBScene *_medusaKeyboardScene;
    SBKeyboardHomeAffordanceAssertion *_keyboardHomeAffordanceAssertion;
    NSMutableSet *_activeBetaLaunchHandles;
    NSObject<OS_dispatch_queue> *_betaLaunchUIActivationQueue;
    NSLayoutConstraint *_homeGrabberTopConstraint;
    NSLayoutConstraint *_homeGrabberBottomConstraint;
    NSLayoutConstraint *_homeGrabberLeftConstraint;
    NSLayoutConstraint *_homeGrabberRightConstraint;
    BOOL __preventsCornerRadiusUpdate;
    double _separatorViewAlpha;
    NSUInteger _nubStyle;
    id <BSInvalidatable> _pushPopWallpaperRequireAssertion;
    SBHomeGrabberRotationView *_homeGrabberRotationView;
    NSString *_keyboardFocusSceneID;
}

@property(copy, nonatomic, getter=_keyboardFocusSceneID, setter=_setKeyboardFocusSceneID:) NSString *keyboardFocusSceneID; // @synthesize keyboardFocusSceneID=_keyboardFocusSceneID;
@property(nonatomic, setter=_setPreventsCornerRadiusUpdate:) BOOL _preventsCornerRadiusUpdate; // @synthesize _preventsCornerRadiusUpdate=__preventsCornerRadiusUpdate;
@property(readonly, nonatomic) SBHomeGrabberRotationView *homeGrabberRotationView; // @synthesize homeGrabberRotationView=_homeGrabberRotationView;
@property(retain, nonatomic) id <BSInvalidatable> pushPopWallpaperRequireAssertion; // @synthesize pushPopWallpaperRequireAssertion=_pushPopWallpaperRequireAssertion;
@property(nonatomic, setter=_setNubStyle:) NSUInteger _nubStyle; // @synthesize _nubStyle;
@property(nonatomic, setter=_setSeparatorViewAlpha:) double _separatorViewAlpha; // @synthesize _separatorViewAlpha;
// - (void).cxx_destruct;
- (CGSize)_layoutSizeForLayoutRole:(long long)arg1 spaceConfiguration:(long long)arg2 interfaceOrientation:(long long)arg3 frameOptions:(NSUInteger)arg4;
- (CGRect)_layoutFrameForLayoutRole:(long long)arg1 inLayoutState:(id)arg2;
- (unsigned int)_convertAnchorEdge:(unsigned int)arg1 toLayoutOrientation:(long long)arg2;
- (unsigned int)_anchorEdgeForLayoutRole:(long long)arg1;
- (CGRect)_separatorViewFrame;
- (void)_createOrDestroyHomeGrabberRotationViewIfNecessary;
- (id)_createStatusBarWithFrame:(CGRect)arg1 interfaceOrientation:(long long)arg2 reason:(id)arg3;
- (void)statusBarBreadcrumbProviderDidUpdateDisplayProperties:(id)arg1;
- (void)sceneHandle:(id)arg1 didUpdateSettingsWithDiff:(id)arg2 previousSettings:(id)arg3;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)betaLaunchHandle:(id)arg1 activateIfNeededEndedWithResult:(BOOL)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidEndWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionWillEndWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidBeginWithTransitionContext:(id)arg2;
- (BOOL)_shouldConsiderHomeScreenAsActive;
- (id)_sceneHandleForBottomEdgeLocation:(double)arg1;
- (id)_sceneHandlesIntersectingHomeGrabber;
- (void)_updateHomeGrabberEdgeProtectAndAutoHideWithResetDelay:(double)arg1 unhideDelay:(double)arg2;
- (void)_updateHomeGrabberEdgeProtectAndAutoHideForAppRequest;
- (void)_configureHomeGrabberForSettingsChangeWithDiff:(id)arg1 transitionContext:(id)arg2;
- (void)_configureHomeGrabberForLayoutStateTransition;
- (void)_setUpObservationWithCurrentEntities:(id)arg1 previousEntities:(id)arg2;
- (BOOL)_isEdgeProtectedForHomeGestureAtEdgeLocation:(double)arg1;
@property(readonly, nonatomic) SBHomeGrabberView *_activeHomeGrabberView;
- (BOOL)_shouldDrawHomeGrabber;
- (BOOL)_shouldNubViewBeVisibleForLayoutRole:(long long)arg1 inLayoutState:(id)arg2;
- (id)_sceneHandleForLayoutRole:(long long)arg1;
- (void)_updateAuxiliaryViewsWhichWantToAnimateDuringRotation;
- (void)_updateAuxiliaryViews;
- (BOOL)_isLayoutElementViewControllerOccluded:(id)arg1;
- (BOOL)_isCurrentlyRotating;
- (BOOL)_isTransitioningNoninteractivelyFromAppToApp;
- (BOOL)_shouldRotateToLayoutOrientation:(long long)arg1;
- (BOOL)_shouldAdjustViewAffordancesAfterTransition;
- (BOOL)_shouldRepositionViewAfterTransition;
- (void)_doCommonCleanupUponEndingLayoutTransitionWithInterruption:(BOOL)arg1;
- (void)_beginLayoutStateTransitionWithTransitionContext:(id)arg1;
- (void)_addLayoutElementViewController:(id)arg1 forLayoutElement:(id)arg2 entity:(id)arg3;
- (CGRect)referenceFrameForUniqueIdentifier:(id)arg1 inLayoutState:(id)arg2;
- (CGRect)referenceFrameForEntity:(id)arg1 inLayoutState:(id)arg2;
- (id)_displayConfiguration;
- (id)_inlineAppExposeOverlayForLayoutRole:(long long)arg1;
- (id)_applicationSceneLayoutElementControllerForLayoutRole:(long long)arg1;
@property(readonly, copy, nonatomic) NSArray *_transitioningAppViewControllers;
@property(readonly, nonatomic) NSArray *appViewControllers;
- (CGRect)_updateRectInReferenceCoordinateSpace:(CGRect)arg1 withBlock:(id /* CDUnknownBlockType */)arg2;
- (CGPoint)_updatePointInReferenceCoordinateSpace:(CGPoint)arg1 withBlock:(id /* CDUnknownBlockType */)arg2;
- (CGAffineTransform)_convertTransformFromContentViewCoordinateSpaceToReferenceCoordinateSpace:(CGAffineTransform)arg1;
- (CGRect)_convertRectFromContentViewCoordinateSpaceToReferenceCoordinateSpace:(CGRect)arg1;
- (CGPoint)_convertPointFromContentViewCoordinateSpaceToReferenceCoordinateSpace:(CGPoint)arg1;
- (CGAffineTransform)_convertTransformFromReferenceCoordinateSpaceToContentViewCoordinateSpace:(CGAffineTransform)arg1;
- (CGRect)_convertRectFromReferenceCoordinateSpaceToContentViewCoordinateSpace:(CGRect)arg1;
- (CGPoint)_convertPointFromReferenceCoordinateSpaceToContentViewCoordinateSpace:(CGPoint)arg1;
@property(readonly, nonatomic) UIView *_separatorView;
- (BOOL)_shouldReverseLayoutDirection;
- (void)_updateWallpaperStyleAndBackgroundColorWithAnimationFactory:(id)arg1;
- (void)_endRequiringPushedInWallpaperForReason:(id)arg1 animationFactory:(id)arg2;
- (void)_beginRequiringPushedInWallpaperForReason:(id)arg1 animationFactory:(id)arg2;
- (void)_popOutForReason:(id)arg1 animationFactory:(id)arg2;
- (void)_pushInForReason:(id)arg1 animationFactory:(id)arg2;
- (CGAffineTransform)_pushedInTransform;
- (void)_setMaskDisplayCorners:(BOOL)arg1 forReason:(id)arg2;
- (void)setUserResizing:(BOOL)arg1;
- (CGRect)_separatorViewReferenceFrameForSpaceConfiguration:(long long)arg1 interfaceOrientation:(long long)arg2 frameOptions:(NSUInteger)arg3;
- (CGRect)_referenceFrameForLayoutRole:(long long)arg1 spaceConfiguration:(long long)arg2 interfaceOrientation:(long long)arg3 frameOptions:(NSUInteger)arg4;
- (CGSize)_layoutSizeForLayoutRole:(long long)arg1 spaceConfiguration:(long long)arg2 layoutState:(id)arg3;
- (CGRect)_referenceFrameForLayoutElement:(id)arg1 inLayoutState:(id)arg2;
- (unsigned int)_layoutSpaceAnchorEdgeForLayoutRole:(long long)arg1;
- (double)_layoutWidthForLayoutRole:(long long)arg1 inSpaceConfiguration:(long long)arg2 interfaceOrientation:(long long)arg3;
- (CGRect)_layoutFrameForSize:(CGSize)arg1 withRole:(long long)arg2 inInterfaceOrientation:(long long)arg3 frameOptions:(NSUInteger)arg4;
- (void)_updateViewControllerNubViewHighlightState:(id)arg1 forKeyboardFocusSceneID:(id)arg2;
- (void)_updateSuppressingHomeAffordanceBounce;
- (void)_updateKeyboardHomeAffordanceAssertion;
- (BOOL)_shouldTakeKeyboardHomeAffordanceAssertion;
- (void)_keyboardWillHide:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (BOOL)_keyboardIsSuppressedForMedusaKeyboardScene;
- (id)_medusaKeyboardSceneHandle;
- (void)_noteKeyboardIsNotForMedusa;
- (void)_noteKeyboardIsForMedusaWithOwningScene:(id)arg1;
- (BOOL)_isStatusBarHidden;
- (id)_trailingStatusBarStyleRequest;
- (id)_leadingStatusBarStyleRequest;
- (UIEdgeInsets)_statusBarEdgeInsetsForLayoutState:(id)arg1;
- (CGRect)_statusBarAvoidanceFrameForLayoutState:(id)arg1 layoutRole:(long long)arg2;
- (CGRect)_statusBarAvoidanceFrameForLayoutState:(id)arg1;
@property(readonly, nonatomic) CGRect _separatorViewHitTestFrame;
@property(readonly, nonatomic) double _separatorViewWidth;
- (unsigned int)_anchorEdgeForLayoutRole:(long long)arg1 inInterfaceOrientation:(long long)arg2;
- (void)_orderFrontOverlayViews;
- (void)_orderFrontLayoutElementViewController:(id)arg1;
- (void)_orderFrontLayoutElementViewControllerForLayoutRole:(long long)arg1;
- (long long)_overrideInterfaceOrientationMechanics;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSceneManager:(id)arg1;
- (id)animationWrapperViewForLayoutState:(id)arg1 roleMask:(NSUInteger)arg2 interfaceOrientation:(long long)arg3 maskDisplayCorners:(BOOL)arg4;
- (id)_animationWrapperViewForElement:(id)arg1 entity:(id)arg2 layoutState:(id)arg3;
- (void)_rotateAppViewsWithAnimationSettings:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)_resizeAppViewsWithAnimationSettings:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)_performJiggleHintAnimationForApplicationSceneHandle:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)_removeAppForTransitionRequest:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)_replaceSingleSceneForTransitionRequest:(id)arg1 animationSettings:(id)arg2 completion:(id /* CDUnknownBlockType */)arg3;
- (void)_fadeOutInlineOverlayForTransitionRequest:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)_slideOverAndFadeElementOffscreenForTransitionRequest:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)_addSingleSceneForTransitionRequest:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (id)_createFadeOutInlineOverlayWithTransitionRequest:(id)arg1;
- (id)_createSlideOverAndFadeElementOffscreenWithTransitionRequest:(id)arg1;
- (id)_createSplitAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_replaceSingleAppAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_removeAppAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_rotateAppsAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_resizeAppsAnimationControllerWithTransitionRequest:(id)arg1;
- (id)_jiggleAppAnimationControllerForTransitionRequest:(id)arg1;
- (id)animationControllerForRotatingWithTransitionRequest:(id)arg1;
- (id)animationControllerForTransitionRequest:(id)arg1;
- (double)normalizedDismissRightLocation;
- (double)normalizedWideNarrowLocation;
- (double)normalizedHalfHalfLocation;
- (double)normalizedNarrowWideLocation;
- (double)normalizedDismissLeftLocation;
- (CGRect)statusBarAvoidanceFrame;
- (long long)_layoutRoleForSceneWithIdentifier:(id)arg1;
- (id)_layoutElementForSceneWithIdentifier:(id)arg1;
- (id)currentlyValidStatusBarPartIdentifiers;
- (CGRect)frameForSceneIdentifier:(id)arg1 inView:(id)arg2;
- (id)statusBarDescriberAtPoint:(CGPoint)arg1 inView:(id)arg2 pointInSceneLayoutSpace:(CGPoint )arg3;
- (id)statusBarPartsForSceneWithIdentifier:(id)arg1;
- (BOOL)allowsConfiguringIndividualStatusBarParts;
- (id)statusBarDescriberForStatusBarPart:(id)arg1;
- (id)statusBarDescribers;
- (long long)statusBarOrientation;

@end

