//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBWindow.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/SBUIActiveOrientationObserver-Protocol.h>

@class NSCountedSet, NSString, UIViewController;

@interface SBMainScreenActiveInterfaceOrientationWindow : SBWindow <BSDescriptionProviding, SBUIActiveOrientationObserver>
{
    NSCountedSet *_orientationUpdateDisableReasons;
    BOOL _passesTouchesThrough;
    NSString *_debugName;
    UIViewController *_sb_rootViewController;
}

@property(nonatomic) BOOL passesTouchesThrough; // @synthesize passesTouchesThrough=_passesTouchesThrough;
@property(retain, nonatomic, setter=sb_setRootViewController:) UIViewController *sb_rootViewController; // @synthesize sb_rootViewController=_sb_rootViewController;
@property(readonly, copy, nonatomic) NSString *debugName; // @synthesize debugName=_debugName;
// - (void).cxx_destruct;
- (BOOL)isActive;
- (void)_updateInterfaceOrientationToCurrentActiveInterfaceOrientationWithDuration:(double)arg1;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (BOOL)isDisablingInterfaceOrientationChanges;
- (void)enableInterfaceOrientationChangesForReason:(id)arg1;
- (void)disableInterfaceOrientationChangesForReason:(id)arg1;
- (id)hitTest:(CGPoint)arg1 withEvent:(id)arg2;
- (void)setHidden:(BOOL)arg1;
- (void)setRootViewController:(id)arg1;
- (id)initWithDebugName:(id)arg1;

@end

