//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBTestRecipe-Protocol.h>

@class FBApplicationUpdateScenesTransaction, NSString;

@interface SBMedusaAppsTestRecipe : NSObject <SBTestRecipe>
{
    BOOL _activated;
    NSString *_leftTestBundleID;
    NSString *_rightTestBundleID;
    FBApplicationUpdateScenesTransaction *_currentTransaction;
}

+ (void)load;
@property(retain, nonatomic) FBApplicationUpdateScenesTransaction *currentTransaction; // @synthesize currentTransaction=_currentTransaction;
// - (void).cxx_destruct;
- (void)_updateAppsToBringUpFromPreferences;
- (void)_toggle;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (id)title;
- (id)init;

@end

