//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBDeviceApplicationSceneViewControlling-Protocol.h>
#import <SpringBoard/SBLayoutStateTransitionObserver-Protocol.h>

@class BSUIAnimationFactory, SBInlineAppExposeContainerViewController, SBMainWorkspaceTransitionRequest, SBSceneViewStatusBarAssertion, SBUIAnimationController;

@protocol SBMedusaDecoratedDeviceApplicationSceneViewControlling <SBDeviceApplicationSceneViewControlling, SBLayoutStateTransitionObserver>
@property(nonatomic, getter=isNubViewHighlighted) BOOL nubViewHighlighted;
@property(nonatomic, getter=isNubViewHidden) BOOL nubViewHidden;
@property(readonly, nonatomic, getter=isBlurred) BOOL blurred;
- (SBSceneViewStatusBarAssertion *)statusBarAssertionWithStatusBarHidden:(BOOL)arg1 nubViewHidden:(long long)arg2 atLevel:(NSUInteger)arg3;
- (SBUIAnimationController *)animationControllerForTransitionRequest:(SBMainWorkspaceTransitionRequest *)arg1;
- (void)setInlineAppExposeContainerViewController:(SBInlineAppExposeContainerViewController *)arg1;
- (void)blurApplicationContent:(BOOL)arg1 withAnimationFactory:(BSUIAnimationFactory *)arg2 completion:(void (^)(void))arg3;
@end

