//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBMedusaDecoratedDeviceApplicationSceneViewControlling-Protocol.h>

@class NSString;

@protocol SBMedusaDecoratedDeviceApplicationSceneViewControlling_Internal <SBMedusaDecoratedDeviceApplicationSceneViewControlling>
- (void)_endRequiringSceneViewMatchMoveAnimationForReason:(NSString *)arg1;
- (void)_beginRequiringSceneViewMatchMoveAnimationForReason:(NSString *)arg1;
@end

