//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBAppStatusBarSettings.h>

@class NSNumber, _UILegibilitySettings;

@interface SBMutableAppStatusBarSettings : SBAppStatusBarSettings
{
}

// - (id)copyWithZone:(_NSZone )arg1;
- (void)applySettings:(id)arg1;
@property(nonatomic) int styleOverridesToCancel; // @dynamic styleOverridesToCancel;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @dynamic legibilitySettings;
@property(nonatomic) long long style; // @dynamic style;
@property(retain, nonatomic) NSNumber *alpha; // @dynamic alpha;
- (id)init;

@end

