//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/NCNotificationViewControllerDelegate-Protocol.h>
#import <SpringBoard/NCNotificationViewControllerObserving-Protocol.h>
#import <SpringBoard/SBHomeGestureParticipantDelegate-Protocol.h>

@class NCNotificationViewController;
@protocol BSInvalidatable, NCNotificationAlertDestination><NCNotificationViewControllerDelegatePrivate><NCNotificationViewControllerObserving;

@interface SBNotificationLongLookBannerDestination : NSObject <NCNotificationViewControllerDelegate, NCNotificationViewControllerObserving, SBHomeGestureParticipantDelegate>
{
    NCNotificationViewController *_presentedBanner;
    id <NCNotificationAlertDestination><NCNotificationViewControllerDelegatePrivate><NCNotificationViewControllerObserving> _parentDestination;
    id <BSInvalidatable> _idleTimerDisableAssertion;
    id <BSInvalidatable> _starModeDisableAssertion;
}

+ (BOOL)shouldNotificationRequestPresentAsLongLook:(id)arg1;
@property(retain, nonatomic) id <BSInvalidatable> starModeDisableAssertion; // @synthesize starModeDisableAssertion=_starModeDisableAssertion;
@property(retain, nonatomic) id <BSInvalidatable> idleTimerDisableAssertion; // @synthesize idleTimerDisableAssertion=_idleTimerDisableAssertion;
@property(nonatomic) __weak id <NCNotificationAlertDestination><NCNotificationViewControllerDelegatePrivate><NCNotificationViewControllerObserving> parentDestination; // @synthesize parentDestination=_parentDestination;
@property(retain, nonatomic) NCNotificationViewController *presentedBanner; // @synthesize presentedBanner=_presentedBanner;
// - (void).cxx_destruct;
- (void)homeGestureParticipantOwningHomeGestureDidChange:(id)arg1;
- (void)notificationViewControllerDidDismiss:(id)arg1;
- (void)notificationViewControllerWillDismiss:(id)arg1;
- (void)notificationViewControllerDidPresent:(id)arg1;
- (void)notificationViewControllerWillPresent:(id)arg1;
- (id)settleHomeAffordanceAnimationBehaviorDescriptionForNotificationViewController:(id)arg1;
- (id)unhideHomeAffordanceAnimationSettingsForNotificationViewController:(id)arg1;
- (id)hideHomeAffordanceAnimationSettingsForNotificationViewController:(id)arg1;
- (id)notificationViewController:(id)arg1 keyboardAssertionForGestureWindow:(id)arg2;
- (void)notificationViewController:(id)arg1 executeAction:(id)arg2 withParameters:(id)arg3 completion:(id /* CDUnknownBlockType */)arg4;
- (void)notificationViewController:(id)arg1 requestPermissionToExecuteAction:(id)arg2 withParameters:(id)arg3 completion:(id /* CDUnknownBlockType */)arg4;
- (void)_setReadyForNotificationRequests;
- (void)_dismissBannerCompleted;
- (id)_delegate;
- (BOOL)_presentedBannerMatchesNotificationRequest:(id)arg1;
- (void)dismissPresentedBannerAnimated:(BOOL)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)postNotificationRequest:(id)arg1 withPresentingViewController:(id)arg2 animated:(BOOL)arg3 completion:(id /* CDUnknownBlockType */)arg4;
- (BOOL)canWithdrawNotificationRequest:(id)arg1;
- (BOOL)canModifyNotificationRequest:(id)arg1;
- (BOOL)canReceiveNotificationRequest:(id)arg1;
- (BOOL)shouldReceiveNotificationRequest:(id)arg1;
@property(readonly, nonatomic, getter=isPreemptingSTAR) BOOL preemptingSTAR;
@property(readonly, nonatomic, getter=isPreventingAutomaticLock) BOOL preventingAutomaticLock;
@property(readonly, nonatomic, getter=isPresentingBanner) BOOL presentingBanner;
- (id)initWithParentDestination:(id)arg1;

@end

