//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString, SBPasscodeAlertItem, SBPasscodeComplianceAlertItem;
@protocol OS_dispatch_queue;

@interface SBPasscodeController : NSObject
{
    SBPasscodeAlertItem *_passcodeAlertItem;
    int _mode;
    NSString *_previousPasscode;
    NSString *_newPasscode;
    int _unlockScreenType;
    int _simplePasscodeType;
    SBPasscodeComplianceAlertItem *_complianceAlertItem;
    NSDate *_forcedComplianceDate;
    id _manageConfigurationEffectiveSettingsObserver;
    id _telephonyNotificationObserver;
    int _restoreCompletedAlertStateChangedToken;
    BOOL _delayedComplianceAlertUntilAfterRestoreCompletedAlert;
    NSObject<OS_dispatch_queue> *_passcodeComplianceQueue;
}

+ (id)sharedInstance;
// - (void).cxx_destruct;
- (void)checkPasscodeCompliance;
- (void)_activateComplianceAlert;
- (void)_stopListeningToRestoreCompletedAlertStateChangedNotifications;
- (void)_startListeningToRestoreCompletedAlertStateChangedNotifications;
- (BOOL)_isRestoreCompletedAlertActive;
- (void)_stopListeningToTelephonyNotifications;
- (void)_startListeningToTelephonyNotifications;
- (void)_didEndCall;
- (void)_abort;
- (void)_userWantsToComplyNow:(BOOL)arg1;
- (void)_stopListeningToManagedConfigurationNotification;
- (void)_startListeningToManagedConfigurationNotification;
- (void)_presentPasscodeAlertItemWithMode:(int)arg1 alertItemErrorString:(id)arg2 unlockScreenType:(int)arg3;
- (void)_fetchAndSetUnlockScreenTypeForNewPasscode:(BOOL)arg1;
- (void)_passwordEntered:(id)arg1;
- (void)forceUserToChangePasscode;
- (void)dealloc;
- (id)init;

@end

