//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>


@class SBPBDisplayItem;

@interface SBPBAppLayout : PBCodable <NSCopying>
{
    int _environment;
    int _layoutConfiguration;
    SBPBDisplayItem *_primaryDisplayItem;
    SBPBDisplayItem *_secondaryDisplayItem;
    int _secondaryDisplayItemRole;
    BOOL _hidden;
    struct {
        unsigned int secondaryDisplayItemRole:1;
    } _has;
}

@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
@property(nonatomic) int environment; // @synthesize environment=_environment;
@property(retain, nonatomic) SBPBDisplayItem *secondaryDisplayItem; // @synthesize secondaryDisplayItem=_secondaryDisplayItem;
@property(retain, nonatomic) SBPBDisplayItem *primaryDisplayItem; // @synthesize primaryDisplayItem=_primaryDisplayItem;
@property(nonatomic) int layoutConfiguration; // @synthesize layoutConfiguration=_layoutConfiguration;
// - (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)arg1;
// - (id)copyWithZone:(_NSZone )arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (int)StringAsEnvironment:(id)arg1;
- (id)environmentAsString:(int)arg1;
@property(readonly, nonatomic) BOOL hasSecondaryDisplayItem;
- (int)StringAsSecondaryDisplayItemRole:(id)arg1;
- (id)secondaryDisplayItemRoleAsString:(int)arg1;
@property(nonatomic) BOOL hasSecondaryDisplayItemRole;
@property(nonatomic) int secondaryDisplayItemRole; // @synthesize secondaryDisplayItemRole=_secondaryDisplayItemRole;
@property(readonly, nonatomic) BOOL hasPrimaryDisplayItem;
- (int)StringAsLayoutConfiguration:(id)arg1;
- (id)layoutConfigurationAsString:(int)arg1;

@end

