//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>


@class NSMutableArray;

@interface SBPBAppLayoutList : PBCodable <NSCopying>
{
    NSMutableArray *_applayouts;
}

+ (Class)applayoutsType;
@property(retain, nonatomic) NSMutableArray *applayouts; // @synthesize applayouts=_applayouts;
// - (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)arg1;
// - (id)copyWithZone:(_NSZone )arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)applayoutsAtIndex:(NSUInteger)arg1;
- (NSUInteger)applayoutsCount;
- (void)addApplayouts:(id)arg1;
- (void)clearApplayouts;

@end

