//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface SBPIPContentViewLayoutSettings : NSObject
{
    long long _position;
    double _size;
    NSMutableArray *_observers;
}

+ (void)removeObserver:(id)arg1;
+ (void)addObserver:(id)arg1;
+ (CGSize)maximumContentViewSizeForAspectRatio:(CGSize)arg1;
+ (CGSize)minimumContentViewSizeForAspectRatio:(CGSize)arg1;
+ (CGSize)defaultContentViewSizeForAspectRatio:(CGSize)arg1;
+ (CGSize)currentContentViewSizeForAspectRatio:(CGSize)arg1;
+ (void)setContentViewSize:(CGSize)arg1;
+ (long long)currentContentViewPosition;
+ (void)setContentViewPosition:(long long)arg1;
+ (double)contentViewPadding;
+ (id)_sharedInstance;
// - (void).cxx_destruct;
- (void)_notifyObservers;
- (void)_removeObserver:(id)arg1;
- (void)_addObserver:(id)arg1;
@property(nonatomic) double size;
@property(nonatomic) long long position;
- (id)init;

@end

