//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBTransientOverlayViewController.h>

#import <SpringBoard/SBPowerDownViewDelegate-Protocol.h>

@class SBPowerDownView;
@protocol SBPowerDownViewControllerDelegate;

@interface SBPowerDownViewController : SBTransientOverlayViewController <SBPowerDownViewDelegate>
{
    NSUInteger _aggdStartTime;
    BOOL _canAlterScreenBrightness;
    SBPowerDownView *_powerDownView;
    id <SBPowerDownViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBPowerDownViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)_resetScreenBrightness;
- (void)_endTimeTrackingIncludingReportWithKey:(id)arg1;
- (void)_incrementCountForKey:(id)arg1;
- (void)_beginTimeTracking;
- (BOOL)shouldPendAlertItems;
- (BOOL)shouldDisableSiri;
- (BOOL)shouldDisableControlCenter;
- (BOOL)shouldDisableBanners;
- (long long)idleTimerMode;
- (id)newTransientOverlayPresentationTransitionCoordinator;
- (id)newTransientOverlayDismissalTransitionCoordinator;
- (void)powerDownView:(id)arg1 didUpdateSlideWithValue:(double)arg2;
- (void)powerDownViewDidReceiveCancelButtonAction:(id)arg1;
- (void)powerDownViewDidFireIdleTimer:(id)arg1;
- (void)powerDownViewDidCompleteSlide:(id)arg1;
- (void)powerDownViewDidCancelSlide:(id)arg1;
- (void)powerDownViewDidBeginSlide:(id)arg1;
- (void)powerDownViewAnimateOutCompleted:(id)arg1;
- (void)powerDownViewWillAnimateOut:(id)arg1;
- (void)powerDownViewWillAnimateIn:(id)arg1;
- (void)powerDownViewRequestPowerDown:(id)arg1;
- (void)powerDownViewRequestCancel:(id)arg1;
- (BOOL)_canShowWhileLocked;
- (int)_preferredStatusBarVisibility;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;

@end

