//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>

@interface SBPresentationObservationToken : NSObject <BSInvalidatable>
{
    long long _state;
    id /* CDUnknownBlockType */ _willPresentHandler;
    id /* CDUnknownBlockType */ _didPresentHandler;
    id /* CDUnknownBlockType */ _willDismissHandler;
    id /* CDUnknownBlockType */ _didDismissHandler;
}

@property(copy, nonatomic) id /* CDUnknownBlockType */ didDismissHandler; // @synthesize didDismissHandler=_didDismissHandler;
@property(copy, nonatomic) id /* CDUnknownBlockType */ willDismissHandler; // @synthesize willDismissHandler=_willDismissHandler;
@property(copy, nonatomic) id /* CDUnknownBlockType */ didPresentHandler; // @synthesize didPresentHandler=_didPresentHandler;
@property(copy, nonatomic) id /* CDUnknownBlockType */ willPresentHandler; // @synthesize willPresentHandler=_willPresentHandler;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
// - (void).cxx_destruct;
- (void)invalidate;
- (void)didDismiss;
- (void)willDismiss;
- (void)didPresent;
- (void)willPresent;

@end

