//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBUIActiveOrientationObserver-Protocol.h>

@class NSHashTable, NSMutableSet, NSString, SBHardwareDefaults, SpringBoard;
@protocol SBProximitySensorControlling;

@interface SBProximitySensorManager : NSObject <SBUIActiveOrientationObserver>
{
    NSMutableSet *_clientsWantingDetectionEnabled;
    id <SBProximitySensorControlling> _hidInterface;
    SBHardwareDefaults *_hardwareDefaults;
    BOOL _proximityDetectionEnabled;
    BOOL _proximityDetectionPermitted;
    BOOL _objectInProximity;
    int _backboardNotificationToken;
    NSHashTable *_observers;
    SpringBoard *_interfaceOrientationProvider;
}

@property(retain, nonatomic, getter=_interfaceOrientationProvider, setter=_setInterfaceOrientationProvider:) SpringBoard *interfaceOrientationProvider; // @synthesize interfaceOrientationProvider=_interfaceOrientationProvider;
@property(nonatomic, getter=isProximityDetectionPermitted, setter=_setProximityDetectionPermitted:) BOOL proximityDetectionPermitted; // @synthesize proximityDetectionPermitted=_proximityDetectionPermitted;
@property(nonatomic, getter=isProximityDetectionEnabled, setter=_setProximityDetectionEnabled:) BOOL proximityDetectionEnabled; // @synthesize proximityDetectionEnabled=_proximityDetectionEnabled;
@property(nonatomic, getter=isObjectInProximity, setter=_setObjectInProximity:) BOOL objectInProximity; // @synthesize objectInProximity=_objectInProximity;
// - (void).cxx_destruct;
- (void)_proximityDidChange:(id)arg1;
- (void)_updateProxState;
- (BOOL)_clientsWantDetectionEnabled;
- (void)_disableProx;
- (void)_enableProx;
- (void)_reloadDefaults;
- (void)_destroy;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
@property(readonly, copy) NSString *description;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)resetProximityCalibration;
- (void)client:(id)arg1 wantsProximityDetectionEnabled:(BOOL)arg2;
- (id)initWithHIDInterface:(id)arg1 hardwareDefaults:(id)arg2 interfaceOrientationProvider:(id)arg3;
- (id)init;

@end

