//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBAWDMetricData.h>

@class NSArray, NSString, NSUUID;

@interface SBPressSequenceMetricData : SBAWDMetricData
{
    BOOL _didTriggerSOS;
    NSString *_pressName;
    NSArray *_pressSequence;
    NSUInteger _clickMax;
    NSUUID *_sosTriggerUUID;
}

@property(copy, nonatomic) NSUUID *sosTriggerUUID; // @synthesize sosTriggerUUID=_sosTriggerUUID;
@property(nonatomic) NSUInteger clickMax; // @synthesize clickMax=_clickMax;
@property(nonatomic) BOOL didTriggerSOS; // @synthesize didTriggerSOS=_didTriggerSOS;
@property(copy, nonatomic) NSArray *pressSequence; // @synthesize pressSequence=_pressSequence;
@property(copy, nonatomic) NSString *pressName; // @synthesize pressName=_pressName;
// - (void).cxx_destruct;

@end

