//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

@class BSMonotonicReferenceTime, BSTimer, NSArray, NSMutableArray, NSSet;

@interface SBPressGestureRecognizer : UIGestureRecognizer
{
    NSSet *_delayablePressTypes;
    NSSet *_precedencePressTypes;
    long long _internalGestureState;
    NSMutableArray *_delayedPressesInfo;
    double _latestDispatchedPressTimestamp;
    long long _latestDispatchedPressPhase;
    long long _latestDispatchedPressType;
    NSMutableArray *_unbalancedPressBeganTypes;
    BSTimer *_waitingGestureStateExpirationTimer;
    BOOL _isDispatchingPresses;
    BSTimer *_waitingForPreemptionTimer;
    BSMonotonicReferenceTime *_precedencePressesReferenceTime;
    double _waitForPreemptionTimeInterval;
}

// - (void).cxx_destruct;
- (id)gestureStateInfoForUnbalancedPressBeganCount:(long long)arg1 previousCount:(long long)arg2;
- (long long)requiredPressTypesCount;
- (void)setWaitForPreemptionTimeInterval:(double)arg1;
- (double)waitForPreemptionTimeInterval;
- (void)_resetPublishedPressInfo;
- (void)_resetState;
- (BOOL)_isGestureFailedOrCancelled;
- (BOOL)_didGestureBegin;
- (void)_cancelGesture;
- (void)_stopWaitingGestureStateExpiration;
- (void)_waitGestureStateExpirationWithFireInterval:(double)arg1 timerExpiredActionBlock:(id /* CDUnknownBlockType */)arg2;
- (void)_updatePublicPressInfo:(id)arg1;
- (void)_applyGestureStateInfo:(id)arg1;
- (void)_updateUnbalancedPressBeganTypesWithCurrentPressType:(long long)arg1 andPhase:(long long)arg2 result:(long long )arg3;
- (id)_gestureStateInfoForPressInfo:(id)arg1;
- (void)_resetDelayedPresses;
- (long long)_delayedPressesCount;
- (BOOL)_shouldStopDispatching;
- (BOOL)_isDispatchingDelayedPresses;
- (void)_reallyStartDispatchingDelayedPresses;
- (void)_startDispatchingDelayedPresses;
- (void)_addDelayedPress:(id)arg1;
- (void)_processDelayablePresses:(id)arg1;
- (void)_processPrecedencePresses:(id)arg1;
- (void)_processPresses:(id)arg1;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (void)reset;
- (double)latestPressTimestamp;
- (long long)latestPressPhase;
- (long long)latestPressType;
- (id)_allowedPressTypes;
- (void)setAllowedPressTypes:(id)arg1;
@property(retain, nonatomic) NSArray *pressTypesWithPrecedence;
- (id)name;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

