//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SBPressPrecedenceArbiter : NSObject
{
    NSUInteger _volumeAndLockButtonPriority;
    long long _homeButtonType;
    BOOL _isMusicPlayingSomewhere;
    NSArray *_hardwareButtons;
}

@property(retain, nonatomic) NSArray *hardwareButtons; // @synthesize hardwareButtons=_hardwareButtons;
// - (void).cxx_destruct;
- (NSUInteger)_currentButtonPriority;
- (void)_applyButtonPriority:(NSUInteger)arg1;
- (void)_updateButtonPrioritiesForClientIsPlayingNotification:(id)arg1;
- (void)_updateButtonPrioritiesForNotification:(id)arg1;
- (void)_updateButtonPriority;
- (void)_initializeButtonPriorities;
- (BOOL)_shouldArbitrateLockAndVolumeHardwareButtonPriorities;
- (id)initWithHomeButtonType:(long long)arg1;

@end

