//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBFluidSwitcherItemContainer.h>

#import <SpringBoard/SBReusableView-Protocol.h>

@class SBAppLayout;

@interface SBReusableSnapshotItemContainer : SBFluidSwitcherItemContainer <SBReusableView>
{
    SBAppLayout *_snapshotAppLayout;
}

@property(retain, nonatomic) SBAppLayout *snapshotAppLayout; // @synthesize snapshotAppLayout=_snapshotAppLayout;
// - (void).cxx_destruct;
- (id)_snapshotView;
- (void)setContentView:(id)arg1;
- (void)prepareForReuse;

@end

