//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/_UIRemoteViewController.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/SBButtonEventsHandler-Protocol.h>
#import <SpringBoard/SBFIdleTimerBehaviorProviding-Protocol.h>
#import <SpringBoard/SBIdleTimerProviding-Protocol.h>
#import <SpringBoard/SBUIRemoteAlertHostInterface_Internal-Protocol.h>

@class NSMutableSet, NSNumber, NSString, _UILegibilitySettings;
@protocol SBIdleTimerCoordinating, SBRemoteTransientOverlayHostViewControllerDelegate;

@interface SBRemoteTransientOverlayHostViewController : _UIRemoteViewController <SBUIRemoteAlertHostInterface_Internal, BSDescriptionProviding, SBButtonEventsHandler, SBFIdleTimerBehaviorProviding, SBIdleTimerProviding>
{
    BOOL _allowsHomeButtonDismissal;
    double _customIdleExpirationTimeout;
    long long _dismissalAnimationStyle;
    NSMutableSet *_idleTimerDisabledReasons;
    NSNumber *_launchingInterfaceOrientationValue;
    NSUInteger _preferredHardwareButtonEvents;
    int _preferredStatusBarVisibility;
    NSNumber *_preferredStatusBarStyleValue;
    NSNumber *_preferredWhitePointAdaptivityStyleValue;
    long long _requestedBackgroundStyle;
    BOOL _prefersWallpaperTunnelActive;
    BOOL _shouldDisableIdleWarn;
    BOOL _shouldUseLockedIdleTimerDuration;
    long long _swipeDismissalStyle;
    NSNumber *_hasTranslucentContentValue;
    BOOL _activatingForSiri;
    BOOL _allowsStackingOverlayContentAbove;
    BOOL _contentOpaque;
    BOOL _shouldEnableFadeInAnimation;
    BOOL _shouldEnableFadeOutAnimation;
    BOOL _shouldDisableOrientationUpdates;
    BOOL _allowsCustomPresentationDismissalAnimations;
    BOOL _shouldIgnoreContentOverlayInsetUpdates;
    BOOL _shouldInvalidateWhenDeactivated;
    BOOL _isScreenshotMarkup;
    BOOL _switcherEligible;
    BOOL _shouldDisableBanners;
    BOOL _shouldDisableControlCenter;
    BOOL _shouldDisableReachability;
    BOOL _shouldDisableInteractiveScreenshotGesture;
    BOOL _shouldDisableSiri;
    BOOL _shouldPendAlertItems;
    int _preferredStatusBarStyleOverridesToCancel;
    id <SBRemoteTransientOverlayHostViewControllerDelegate> _delegate;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    long long _preferredLockedGestureDismissalStyle;
    long long _preferredUnlockedGestureDismissalStyle;
    long long _preferredBackgroundStyle;
    NSNumber *_preferredSceneDeactivationReasonValue;
}

+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
@property(readonly, nonatomic) BOOL shouldPendAlertItems; // @synthesize shouldPendAlertItems=_shouldPendAlertItems;
@property(readonly, nonatomic) BOOL shouldDisableSiri; // @synthesize shouldDisableSiri=_shouldDisableSiri;
@property(readonly, nonatomic) BOOL shouldDisableInteractiveScreenshotGesture; // @synthesize shouldDisableInteractiveScreenshotGesture=_shouldDisableInteractiveScreenshotGesture;
@property(readonly, nonatomic) BOOL shouldDisableReachability; // @synthesize shouldDisableReachability=_shouldDisableReachability;
@property(readonly, nonatomic) BOOL shouldDisableControlCenter; // @synthesize shouldDisableControlCenter=_shouldDisableControlCenter;
@property(readonly, nonatomic) BOOL shouldDisableBanners; // @synthesize shouldDisableBanners=_shouldDisableBanners;
@property(nonatomic, getter=isSwitcherEligible) BOOL switcherEligible; // @synthesize switcherEligible=_switcherEligible;
@property(nonatomic) BOOL isScreenshotMarkup; // @synthesize isScreenshotMarkup=_isScreenshotMarkup;
@property(readonly, nonatomic) BOOL shouldInvalidateWhenDeactivated; // @synthesize shouldInvalidateWhenDeactivated=_shouldInvalidateWhenDeactivated;
@property(nonatomic) BOOL shouldIgnoreContentOverlayInsetUpdates; // @synthesize shouldIgnoreContentOverlayInsetUpdates=_shouldIgnoreContentOverlayInsetUpdates;
@property(nonatomic) BOOL allowsCustomPresentationDismissalAnimations; // @synthesize allowsCustomPresentationDismissalAnimations=_allowsCustomPresentationDismissalAnimations;
@property(readonly, nonatomic) BOOL shouldDisableOrientationUpdates; // @synthesize shouldDisableOrientationUpdates=_shouldDisableOrientationUpdates;
@property(readonly, nonatomic) int preferredStatusBarStyleOverridesToCancel; // @synthesize preferredStatusBarStyleOverridesToCancel=_preferredStatusBarStyleOverridesToCancel;
@property(readonly, copy, nonatomic) NSNumber *preferredSceneDeactivationReasonValue; // @synthesize preferredSceneDeactivationReasonValue=_preferredSceneDeactivationReasonValue;
@property(readonly, nonatomic) long long preferredBackgroundStyle; // @synthesize preferredBackgroundStyle=_preferredBackgroundStyle;
@property(readonly, nonatomic) long long preferredUnlockedGestureDismissalStyle; // @synthesize preferredUnlockedGestureDismissalStyle=_preferredUnlockedGestureDismissalStyle;
@property(readonly, nonatomic) long long preferredLockedGestureDismissalStyle; // @synthesize preferredLockedGestureDismissalStyle=_preferredLockedGestureDismissalStyle;
@property(nonatomic) BOOL shouldEnableFadeOutAnimation; // @synthesize shouldEnableFadeOutAnimation=_shouldEnableFadeOutAnimation;
@property(nonatomic) BOOL shouldEnableFadeInAnimation; // @synthesize shouldEnableFadeInAnimation=_shouldEnableFadeInAnimation;
@property(nonatomic) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator; // @synthesize idleTimerCoordinator=_idleTimerCoordinator;
@property(readonly, nonatomic, getter=isContentOpaque) BOOL contentOpaque; // @synthesize contentOpaque=_contentOpaque;
@property(readonly, nonatomic) BOOL allowsStackingOverlayContentAbove; // @synthesize allowsStackingOverlayContentAbove=_allowsStackingOverlayContentAbove;
@property(nonatomic, getter=isActivatingForSiri) BOOL activatingForSiri; // @synthesize activatingForSiri=_activatingForSiri;
@property(nonatomic) __weak id <SBRemoteTransientOverlayHostViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)_updatePreferredGestureDismissalStyles;
- (void)_updatePreferredBackgroundStyleWithAnimationSettings:(id)arg1;
- (void)_updateContentOpaqueProperty;
- (BOOL)_performButtonEvents:(NSUInteger)arg1;
- (void)dismissForTransientOverlayAnimated:(BOOL)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)presentForTransientOverlayAnimated:(BOOL)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)restoreInputViewsAnimated:(BOOL)arg1;
- (void)preserveInputViewsAnimated:(BOOL)arg1;
- (void)prepareForActivationWithContext:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (void)handlePictureInPictureDidBegin;
- (void)configureWithContext:(id)arg1 completion:(id /* CDUnknownBlockType */)arg2;
@property(readonly, copy, nonatomic) _UILegibilitySettings *preferredStatusBarLegibilitySettings;
- (int)_preferredStatusBarVisibility;
- (void)_updateContentOverlayInsetsFromParentIfNecessary;
- (void)viewServiceDidTerminateWithError:(id)arg1;
- (BOOL)_canShowWhileLocked;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (long long)preferredWhitePointAdaptivityStyle;
- (long long)preferredInterfaceOrientationForPresentation;
- (long long)preferredStatusBarStyle;
- (BOOL)resignFirstResponder;
- (BOOL)canResignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)_participateInSystemAnimationFence:(id)arg1;
- (void)setSceneDeactivationReason:(id)arg1;
- (void)setReachabilityDisabled:(BOOL)arg1;
- (void)setDesiredIdleTimerSettings:(id)arg1;
- (void)setWhitePointAdaptivityStyle:(long long)arg1;
- (void)setOrientationChangedEventsEnabled:(BOOL)arg1;
- (void)setLaunchingInterfaceOrientation:(long long)arg1;
- (void)setInteractiveScreenshotGestureDisabled:(BOOL)arg1;
- (void)setSupportedInterfaceOrientationOverride:(NSUInteger)arg1;
- (void)setShouldDisableFadeInAnimation:(BOOL)arg1;
- (void)setShouldDismissOnUILock:(BOOL)arg1;
- (void)setStatusBarHidden:(BOOL)arg1 withDuration:(double)arg2;
- (void)setDesiredAutoLockDuration:(double)arg1;
- (void)setIdleTimerDisabled:(BOOL)arg1 forReason:(id)arg2;
- (void)setStyleOverridesToCancel:(int)arg1 animationSettings:(id)arg2;
- (void)setDesiredStatusBarStyleOverrides:(int)arg1;
- (void)setSwipeDismissalStyle:(long long)arg1;
- (void)setDismissalAnimationStyle:(long long)arg1;
- (void)setAllowsAlertStacking:(BOOL)arg1;
- (void)setAllowsMenuButtonDismissal:(BOOL)arg1;
- (void)setWallpaperStyle:(long long)arg1 withDuration:(double)arg2;
- (void)setBackgroundStyle:(long long)arg1 withDuration:(double)arg2;
- (void)setWallpaperTunnelActive:(BOOL)arg1;
- (void)setDesiredHardwareButtonEvents:(NSUInteger)arg1;
- (void)invalidate;
- (void)deactivate;
- (void)dismiss;
- (void)setAllowsSiri:(BOOL)arg1;
- (void)setAllowsControlCenter:(BOOL)arg1;
- (void)setAllowsAlertItems:(BOOL)arg1;
- (void)setAllowsBanners:(BOOL)arg1;
- (id)coordinatorRequestedIdleTimerBehavior:(id)arg1;
@property(readonly, nonatomic) double customIdleExpirationTimeout;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleTimerDuration;
- (void)didInvalidateForRemoteAlert;
- (BOOL)handleDoubleHeightStatusBarTap;
- (BOOL)handleVolumeDownButtonPress;
- (BOOL)handleVolumeUpButtonPress;
- (BOOL)handleHomeButtonPress;
- (BOOL)handleHomeButtonLongPress;
- (BOOL)handleHomeButtonDoublePress;
- (BOOL)handleHeadsetButtonPress:(BOOL)arg1;
- (BOOL)handleLockButtonPress;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

