//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import <SpringBoard/SBSceneLayoutReferenceOrientedView-Protocol.h>

@class NSArray, NSString;

@interface SBSceneLayoutAnimationWrapperView : UIView <SBSceneLayoutReferenceOrientedView>
{
    long long _layoutOrientation;
    long long _referenceOrientation;
}

@property(nonatomic) long long layoutOrientation; // @synthesize layoutOrientation=_layoutOrientation;
@property(nonatomic) long long referenceOrientation; // @synthesize referenceOrientation=_referenceOrientation;
- (void)crossfadeWithCompletion:(id /* CDUnknownBlockType */)arg1;
- (void)invalidate;
- (id)elementWrapperViewForLayoutRole:(long long)arg1;
@property(readonly, nonatomic) NSArray *elementWrapperViews;
@property(readonly, copy) NSString *description;
- (id)initWithFrame:(CGRect)arg1;

@end

