//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBSceneHandle.h>

@interface SBSceneHandle (SceneViewControlling)
- (id)newSceneViewController;
- (id)newScenePlaceholderContentContextWithActivationSettings:(id)arg1;
- (id)newSceneViewWithReferenceSize:(CGSize)arg1 orientation:(long long)arg2 hostRequester:(id)arg3;
- (BOOL)isDeviceApplicationSceneHandle;
@property(readonly, nonatomic, getter=isEffectivelyForeground) BOOL effectivelyForeground;
@end

