//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBHardwareButtonGestureParametersProviderBase.h>

#import <SpringBoard/SBHardwareButtonInteraction-Protocol.h>

@class SiriLongPressButtonSource;
@protocol SiriAssertion;

@interface SBSiriHardwareButtonInteraction : SBHardwareButtonGestureParametersProviderBase <SBHardwareButtonInteraction>
{
    double _initialPressDownTime;
    long long _siriButtonIdentifier;
    SiriLongPressButtonSource *_siriActivationSource;
    double _activationInterval;
    id <SiriAssertion> _siriPreheatAssertion;
    id <SiriAssertion> _siriButtonDownAssertion;
}

+ (BOOL)dismissSiriTransientOverlayOnSinglePressUp:(long long)arg1;
+ (id)hardwareButtonInteractionForLockButton;
+ (id)hardwareButtonInteractionForHomeButton;
@property(retain, nonatomic) id <SiriAssertion> siriButtonDownAssertion; // @synthesize siriButtonDownAssertion=_siriButtonDownAssertion;
@property(retain, nonatomic) id <SiriAssertion> siriPreheatAssertion; // @synthesize siriPreheatAssertion=_siriPreheatAssertion;
@property(nonatomic) double activationInterval; // @synthesize activationInterval=_activationInterval;
@property(retain, nonatomic) SiriLongPressButtonSource *siriActivationSource; // @synthesize siriActivationSource=_siriActivationSource;
@property(nonatomic) long long siriButtonIdentifier; // @synthesize siriButtonIdentifier=_siriButtonIdentifier;
@property(nonatomic) double initialPressDownTime; // @synthesize initialPressDownTime=_initialPressDownTime;
// - (void).cxx_destruct;
- (id)hardwareButtonGestureParameters;
- (BOOL)consumeLongPress;
- (BOOL)consumeSinglePressUp;
- (BOOL)consumeInitialPressDown;
- (void)observeLongPressCanceled;
- (void)observeFinalPressUp;
- (void)_cancelAllSiriActions;
- (void)_cancelPreheating;
- (void)_preheatSiriForPresentationAfterInterval:(double)arg1;
- (void)_siriHomeButtonPrefsDidChange:(id)arg1;
- (id)initWithSiriButton:(long long)arg1;

@end

