//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBPressSequenceRecognizerDelegate-Protocol.h>

@class BSAction, SBPressSequenceObserver, SBPressSequenceRecognizer, SBPressSequenceSettings, SBPressSequenceValidator;
@protocol SBSOSLockGestureObserverDelegate;

@interface SBSOSLockGestureObserver : NSObject <SBPressSequenceRecognizerDelegate>
{
    SBPressSequenceRecognizer *_recognizer;
    SBPressSequenceValidator *_validator;
    SBPressSequenceSettings *_settings;
    BOOL _lastKnownActiveState;
    BSAction *_triggerAction;
    BOOL _gestureLoggingEnabled;
    BOOL _sosEnabled;
    SBPressSequenceObserver *_sosLockPressSequenceObserver;
    id <SBSOSLockGestureObserverDelegate> _delegate;
    long long _configuration;
}

@property(nonatomic, getter=isSOSEnabled, setter=setSOSEnabled:) BOOL sosEnabled; // @synthesize sosEnabled=_sosEnabled;
@property(nonatomic, getter=isGestureLoggingEnabled) BOOL gestureLoggingEnabled; // @synthesize gestureLoggingEnabled=_gestureLoggingEnabled;
@property(readonly, nonatomic) long long configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak id <SBSOSLockGestureObserverDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBPressSequenceObserver *sosLockPressSequenceObserver; // @synthesize sosLockPressSequenceObserver=_sosLockPressSequenceObserver;
// - (void).cxx_destruct;
- (double)_watchdogInterval;
- (double)_intervalThatSucceeds;
- (NSUInteger)_numberOfPressesThatActivate;
- (NSUInteger)_numberOfPressesThatTrigger;
- (id)_validator;
- (void)_setRecognizer:(id)arg1;
- (void)_configureSettings;
- (void)_configure;
- (void)_noteTriggerDidBecomeInactive;
- (void)_noteTriggerDidBecomeActive;
- (void)_noteTriggerActionRecievedResponse;
- (void)pressSequenceRecognizerDidFail:(id)arg1;
- (void)pressSequenceRecognizer:(id)arg1 didBeginPressDownAtIndex:(NSUInteger)arg2;
- (void)pressSequenceRecognizerDidCompleteSequence:(id)arg1;
- (void)noteDidBeginSOSWithUUID:(id)arg1;
- (void)resetWithNewConfiguration:(long long)arg1;
- (void)registerPressUpWithTimestamp:(double)arg1;
- (void)registerPressDownWithTimestamp:(double)arg1;
@property(readonly, nonatomic) long long triggerMechanism;
- (id)initWithConfiguration:(long long)arg1;
- (id)init;

@end

