//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/FBSceneManagerObserver-Protocol.h>
#import <SpringBoard/SBDeviceApplicationSceneStatusBarStateObserver-Protocol.h>
#import <SpringBoard/SBMultiplexedSpotlightDelegate-Protocol.h>
#import <SpringBoard/SBScrollToTopSceneProxyViewDelegate-Protocol.h>

@class SBAppStatusBarSettingsAssertion, SBDeviceApplicationSceneStatusBarStateProvider, SBScrollToTopSceneProxyView, UIGestureRecognizer, UIView, _UILegibilitySettings;
@protocol SPUIRemoteSearchViewDelegate;

@interface SBSpotlightMultiplexingViewController : UIViewController <SBMultiplexedSpotlightDelegate, FBSceneManagerObserver, SBDeviceApplicationSceneStatusBarStateObserver, SBScrollToTopSceneProxyViewDelegate>
{
    BOOL _reachabilityEnabled;
    UIView *_reachabilityContainerView;
    UIGestureRecognizer *_dismissReachabilityGesture;
    SBDeviceApplicationSceneStatusBarStateProvider *_statusBarStateProvider;
    SBAppStatusBarSettingsAssertion *_statusBarAssertion;
    SBScrollToTopSceneProxyView *_scrollToTopView;
    BOOL _activeDelegate;
    _UILegibilitySettings *_legibilitySettings;
    NSUInteger _searchViewPresentationSourceForNextTransition;
    id <SPUIRemoteSearchViewDelegate> _spotlightDelegate;
}

+ (id)sharedRemoteSearchViewController;
@property(nonatomic, getter=isActiveDelegate) BOOL activeDelegate; // @synthesize activeDelegate=_activeDelegate;
@property(nonatomic) __weak id <SPUIRemoteSearchViewDelegate> spotlightDelegate; // @synthesize spotlightDelegate=_spotlightDelegate;
@property(nonatomic) NSUInteger searchViewPresentationSourceForNextTransition; // @synthesize searchViewPresentationSourceForNextTransition=_searchViewPresentationSourceForNextTransition;
@property(copy, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
// - (void).cxx_destruct;
- (NSUInteger)remoteSearchViewPresentationSource;
- (void)_unregisterStatusBarScrollToTopViewWithWindow:(id)arg1;
- (void)_unregisterStatusBarScrollToTopView;
- (void)_registerStatusBarScrollToTopViewWithWindow:(id)arg1;
- (void)_registerStatusBarScrollToTopView;
- (void)_configureStatusBarScrollToTopView;
- (void)_configureStatusBarStateProvider;
- (id)_spotlightSceneIdentifier;
- (void)_invalidateStatusBarAssertionIfNeeded;
- (void)_acquireStatusBarAssertionIfNeeded;
- (id)_currentStatusBarSettings;
- (void)scrollToTopSceneProxyViewWillExitViewHierarchy:(id)arg1 rootedAtWindow:(id)arg2;
- (void)scrollToTopSceneProxyViewDidEnterViewHierarchy:(id)arg1 rootedAtWindow:(id)arg2;
- (double)_effectiveStatusBarAlpha;
- (void)sceneWithIdentifier:(id)arg1 didChangeStatusBarHiddenTo:(BOOL)arg2 withAnimation:(long long)arg3;
- (void)sceneWithIdentifier:(id)arg1 didChangeStatusBarStyleTo:(long long)arg2;
- (void)sceneWithIdentifier:(id)arg1 didChangeStatusBarAlphaTo:(double)arg2;
- (void)sceneManager:(id)arg1 didDestroyScene:(id)arg2;
- (void)sceneManager:(id)arg1 didCreateScene:(id)arg2;
- (void)didResignActiveDelegate;
- (void)didBecomeActiveDelegate;
- (void)dismissSearchView;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
@property(readonly, nonatomic) NSUInteger level;
- (void)dealloc;

@end

