//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBStatusBarStateAggregator;

@protocol SBStatusBarStateAggregatorPosting <NSObject>
- (void)statusBarStateAggregatorDidFinishPost:(SBStatusBarStateAggregator *)arg1 withData:(const CDStruct_0942cde0 )arg2 actions:(int)arg3;
- (void)statusBarStateAggregator:(SBStatusBarStateAggregator *)arg1 didUpdateNonItemData:(const CDStruct_0942cde0 )arg2;
- (void)statusBarStateAggregator:(SBStatusBarStateAggregator *)arg1 didVisitItem:(int)arg2 withUpdates:(BOOL)arg3 toData:(const CDStruct_0942cde0 )arg4;
- (void)statusBarStateAggregatorDidStartPost:(SBStatusBarStateAggregator *)arg1;

@optional
- (void)statusBarStateAggregatorDidStopRequestingImmediateUpdates:(SBStatusBarStateAggregator *)arg1;
- (void)statusBarStateAggregatorDidRequestImmediateUpdates:(SBStatusBarStateAggregator *)arg1;
@end

