//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBInitialRestartState;

@interface SBStartupTransitionFactory : NSObject
{
    SBInitialRestartState *_initialRestartState;
}

// - (void).cxx_destruct;
- (id)_transactionForDestination:(NSUInteger)arg1 context:(id)arg2;
- (id)transitionForContext:(id)arg1 outDestination:(NSUInteger )arg2;
- (id)initWithInitialRestartState:(id)arg1;

@end

