//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class BSServiceConnectionEndpoint, CRCarPlayAppPolicy, FBSDisplayIdentity, SBApplication, UIWindow;

@protocol SBStarkNotificationsConfiguring <NSObject>
@property(readonly, nonatomic) BSServiceConnectionEndpoint *openServiceEndpoint;
@property(readonly, nonatomic, getter=isConnectedWirelessly) BOOL connectedWirelessly;
@property(readonly, nonatomic) FBSDisplayIdentity *displayIdentity;
@property(readonly, nonatomic) UIWindow *focusWindow;
- (CRCarPlayAppPolicy *)policyForApp:(SBApplication *)arg1;
@end

