//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NCNotificationAction, NCNotificationRequest;

@protocol SBStarkNotificationBannerSourceDelegate <NSObject>
- (void)didDismissNotificationRequest:(NCNotificationRequest *)arg1;
- (void)willPresentNotificationRequest:(NCNotificationRequest *)arg1;
- (void)executeAction:(NCNotificationAction *)arg1 forNotificationRequest:(NCNotificationRequest *)arg2;
@end

