//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSystemGestureManager.h>

@interface SBStarkNotificationSystemGestureManager : SBSystemGestureManager
{
}

- (BOOL)_shouldEnableSystemGestureWithType:(NSUInteger)arg1;
- (id)initWithConfiguration:(id)arg1;

@end

