//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBBaseStartupTransition.h>

@class SBApplicationController, SBBulletinWindowController, SBFUserAuthenticationController, SBInitialRestartState, SBLockScreenManager, SBSetupManager;

@interface SBStartupTransitionToSetup : SBBaseStartupTransition
{
    SBBulletinWindowController *_bulletinWindowController;
    SBFUserAuthenticationController *_authController;
    SBApplicationController *_appController;
    SBSetupManager *_setupManager;
    SBLockScreenManager *_lockScreenManager;
    SBInitialRestartState *_initialRestartState;
}

// - (void).cxx_destruct;
- (void)_activateSetupWithCompletion:(id /* CDUnknownBlockType */)arg1 underLock:(BOOL)arg2 fromSnapshot:(BOOL)arg3;
- (void)performTransitionWithCompletionBlock:(id /* CDUnknownBlockType */)arg1;
- (id)initWithDestination:(NSUInteger)arg1 context:(id)arg2;
- (id)initWithDestination:(NSUInteger)arg1 context:(id)arg2 initialRestartState:(id)arg3;

@end

