//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBBestAppSuggestion, SBSwitcherAppSuggestionViewController;

@protocol SBSwitcherAppSuggestionViewControllerDelegate <NSObject>
- (long long)orientationForSuggestionViewController:(SBSwitcherAppSuggestionViewController *)arg1;
- (void)suggestionViewController:(SBSwitcherAppSuggestionViewController *)arg1 activatedSuggestion:(SBBestAppSuggestion *)arg2;
@end

