//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBSwitcherModifierActionSnapshot, SBSwitcherModifierEventSnapshot, SBSwitcherModifierStackSnapshot;

@interface SBSwitcherModifierTimelineEntry : NSObject
{
    SBSwitcherModifierEventSnapshot *_eventSnapshot;
    SBSwitcherModifierStackSnapshot *_postEventStackSnapshot;
    SBSwitcherModifierActionSnapshot *_actionSnapshot;
}

@property(retain, nonatomic) SBSwitcherModifierActionSnapshot *actionSnapshot; // @synthesize actionSnapshot=_actionSnapshot;
@property(retain, nonatomic) SBSwitcherModifierStackSnapshot *postEventStackSnapshot; // @synthesize postEventStackSnapshot=_postEventStackSnapshot;
@property(retain, nonatomic) SBSwitcherModifierEventSnapshot *eventSnapshot; // @synthesize eventSnapshot=_eventSnapshot;
// - (void).cxx_destruct;

@end

