//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>

@class STWifiStatusDomainPublisher;

@interface SBSystemStatusWifiDataProvider : NSObject <BSInvalidatable>
{
    BOOL _wifiActive;
    BOOL _fallingBackToCellular;
    STWifiStatusDomainPublisher *_wifiDataPublisher;
    struct tcp_connection_fallback_watch_s _cellularFallbackWatcher;
}

@property(nonatomic) struct tcp_connection_fallback_watch_s cellularFallbackWatcher; // @synthesize cellularFallbackWatcher=_cellularFallbackWatcher;
@property(nonatomic, getter=isFallingBackToCellular) BOOL fallingBackToCellular; // @synthesize fallingBackToCellular=_fallingBackToCellular;
@property(nonatomic, getter=isWifiActive) BOOL wifiActive; // @synthesize wifiActive=_wifiActive;
@property(readonly, nonatomic) STWifiStatusDomainPublisher *wifiDataPublisher; // @synthesize wifiDataPublisher=_wifiDataPublisher;
// - (void).cxx_destruct;
- (void)_updateWifiActive;
- (void)_updateData;
- (void)_registerForNotifications;
- (void)invalidate;
- (void)dealloc;
- (id)init;

@end

