//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBMainWorkspaceTransaction.h>

#import <SpringBoard/FBSynchronizedTransactionDelegate-Protocol.h>
#import <SpringBoard/SBSceneLayoutWorkspaceTransactionDelegate-Protocol.h>
#import <SpringBoard/SBUIAnimationControllerObserver-Protocol.h>

@class NSCountedSet, NSSet, SBAppRepairTransaction, SBFloatingDockBehaviorAssertion, SBSceneLayoutWorkspaceTransaction, SBUIAnimationController, UIApplicationSceneDeactivationAssertion;

@interface SBToAppsWorkspaceTransaction : SBMainWorkspaceTransaction <SBSceneLayoutWorkspaceTransactionDelegate, FBSynchronizedTransactionDelegate, SBUIAnimationControllerObserver>
{
    id /* CDUnknownBlockType */ _transitionCompletion;
    UIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    id /* CDUnknownBlockType */ _layoutTransitionContinuation;
    SBAppRepairTransaction *_appRepairTransaction;
    SBUIAnimationController *_animationController;
    NSCountedSet *_completionDelayRequesters;
    BOOL _underLockScreenInForeground;
    BOOL _gestureInitiated;
    NSUInteger _preactivationForegroundRunningApplicationCount;
    BOOL _toAndFromApplicationsDiffer;
    BOOL _retriedAfterVoluntaryExit;
    BOOL _applicationStateNeedsCapture;
    BOOL _dismissedOverlays;
    BOOL _shouldDismissOverlays;
    BOOL _touchCancellationDisabled;
    SBSceneLayoutWorkspaceTransaction *_layoutTransaction;
    SBFloatingDockBehaviorAssertion *_floatingDockBehaviorAssertion;
}

+ (BOOL)canInterruptTransaction:(id)arg1 forTransitionRequest:(id)arg2;
@property(retain, nonatomic) SBFloatingDockBehaviorAssertion *floatingDockBehaviorAssertion; // @synthesize floatingDockBehaviorAssertion=_floatingDockBehaviorAssertion;
@property(readonly, nonatomic) SBSceneLayoutWorkspaceTransaction *layoutTransaction; // @synthesize layoutTransaction=_layoutTransaction;
// - (void).cxx_destruct;
- (void)_fireAndClearResultBlockIfNecessaryForFailure:(BOOL)arg1;
- (id)animationController;
- (void)animationControllerDidRevealApplication:(id)arg1;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)animationController:(id)arg1 willBeginAnimation:(BOOL)arg2;
- (void)synchronizedTransaction:(id)arg1 didCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransaction:(id)arg1 willCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransactionReadyToCommit:(id)arg1;
- (BOOL)shouldWatchdog:(id )arg1;
- (double)watchdogTimeout;
- (void)transaction:(id)arg1 didEndLayoutTransitionWithContinuation:(id /* CDUnknownBlockType */)arg2;
- (void)transaction:(id)arg1 performTransitionWithCompletion:(id /* CDUnknownBlockType */)arg2;
- (void)transactionWillBeginLayoutTransition:(id)arg1;
- (id)createSceneEntityForHandle:(id)arg1;
- (id)_customizedDescriptionProperties;
- (void)_didInterruptWithReason:(id)arg1;
- (BOOL)_shouldFailForChildTransaction:(id)arg1;
- (void)_willInterruptWithReason:(id)arg1;
- (void)_willFailWithReason:(id)arg1;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)_didComplete;
- (BOOL)_canBeInterrupted;
- (void)_willBegin;
- (void)_logForInterruptAttemptReason:(id)arg1;
- (void)_captureApplicationState;
- (void)_checkForAnimationCompletion;
- (void)_noteAnimationFinished;
- (void)_clearAnimation;
- (void)_beginAnimationIfNecessary;
- (BOOL)_beginAnimation;
- (void)_configureAnimation;
- (void)_performPostAnimationTasksWithCompletion:(id /* CDUnknownBlockType */)arg1;
- (void)_performPreAnimationTasksWithCompletion:(id /* CDUnknownBlockType */)arg1;
- (BOOL)_hasPostAnimationTasks;
- (BOOL)_hasPreAnimationTasks;
- (void)_animationDidRevealApplication;
- (void)_animationDidFinish;
- (void)_animationWillBegin:(BOOL)arg1;
- (id)_setupAnimation;
- (BOOL)_shouldResignActiveForAnimation;
- (void)_setShouldDismissOverlays:(BOOL)arg1;
- (BOOL)_shouldDismissOverlays;
- (NSUInteger)_serialOverlayPreDismissalOptions;
- (void)_synchronizeWithSceneUpdates;
- (BOOL)_transitionWasCancelled;
- (void)_endTransition;
- (void)_beginTransition;
- (void)_stopDelayingTransitionCompletionForRequester:(id)arg1;
- (void)_delayTransitionCompletionForRequester:(id)arg1;
- (void)_handleApplicationUpdateScenesTransactionFailed:(id)arg1;
- (void)_relinquishResignActiveAssertion;
- (void)_acquireResignActiveAssertion;
- (void)_handleApplicationDidNotChange:(id)arg1;
- (void)_completeCurrentTransition;
- (id)_transitionContext;
- (id)_scenesToBackground;
- (void)activateApplications;
- (BOOL)toAndFromAppsDiffer;
- (BOOL)isGoingToLauncher;
- (void)performToAppStateCleanup;
- (BOOL)shouldAnimateOrientationChangeOnCompletion;
- (BOOL)isGoingToCoverSheet;
- (BOOL)isGoingToMainSwitcher;
- (BOOL)isFromMainSwitcher;
- (BOOL)shouldPlaceOutgoingScenesUnderLockOnCompletion;
- (BOOL)shouldRestoreSpringBoardContentOnCleanup;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
@property(readonly, nonatomic) NSSet *fromApplicationSceneEntities;
@property(readonly, nonatomic) NSSet *toApplicationSceneEntities;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;

@end

