//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/_UISettings.h>

@interface SBUISettings : _UISettings
{
}

- (void)addKeyPathObserverIfPrototyping:(id)arg1;
- (void)addKeyObserverIfPrototyping:(id)arg1;

@end

