//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class NSDictionary, NSString, NSURL, SBAlertItem;
@protocol SBUIActiveOrientationObserver, SBUIIdleTimerHandler;

@protocol SBUIUserAgent <NSObject>
@property(nonatomic) long long softwareUpdatePasscodePolicyType;
- (NSString *)topSuspendedEventsOnlyDisplayID;
- (BOOL)isInternalInstall;
- (struct __CFRunLoop )wifiRunLoopRef;
- (NSString *)folderNameForDisplayID:(NSString *)arg1;
- (void)disableLockScreenBundleNamed:(NSString *)arg1 deactivationContext:(NSDictionary *)arg2;
- (void)enableLockScreenBundleNamed:(NSString *)arg1 activationContext:(NSDictionary *)arg2;
- (BOOL)isNamedRemoteAlertServiceActive:(NSString *)arg1 controllerClassName:(NSString *)arg2;
- (void)activateRemoteAlertService:(NSString *)arg1 options:(NSDictionary *)arg2;
- (void)setMinimumBacklightLevel:(float)arg1 animated:(BOOL)arg2;
- (void)notifyOnNextUserEvent;
- (void)removeActiveInterfaceOrientationObserver:(id <SBUIActiveOrientationObserver>)arg1;
- (void)addActiveInterfaceOrientationObserver:(id <SBUIActiveOrientationObserver>)arg1;
- (void)activateModalBulletinAlert:(SBAlertItem *)arg1;
- (void)setBadgeNumberOrString:(id)arg1 forApplicationWithID:(NSString *)arg2;
- (void)setIdleText:(NSString *)arg1;
- (BOOL)isScreenOn;
- (void)lockAndDimDeviceDisconnectingCallIfNecessary:(BOOL)arg1 andDimScreen:(BOOL)arg2;
- (void)lockAndDimDeviceDisconnectingCallIfNecessary:(BOOL)arg1;
- (void)lockAndDimDevice;
- (void)removeIdleTimerHandler:(id <SBUIIdleTimerHandler>)arg1;
- (void)addIdleTimerHandler:(id <SBUIIdleTimerHandler>)arg1;
- (BOOL)isIdleTimerDisabledForReason:(NSString *)arg1;
- (void)setIdleTimerDisabled:(BOOL)arg1 forReason:(NSString *)arg2;
- (void)undimScreen;
- (BOOL)isApplicationRestrictedOrHidden:(NSString *)arg1;
- (BOOL)launchApplicationFromSource:(int)arg1 withURL:(NSURL *)arg2 options:(NSDictionary *)arg3;
- (BOOL)launchApplicationFromSource:(int)arg1 withDisplayID:(NSString *)arg2 options:(NSDictionary *)arg3;
- (BOOL)canLaunchFromSource:(int)arg1 withURL:(NSURL *)arg2 bundleID:(NSString *)arg3;
- (BOOL)openURL:(NSURL *)arg1 allowUnlock:(BOOL)arg2 animated:(BOOL)arg3;
- (BOOL)springBoardIsActive;
- (int)networkUsageTypeForAppWithDisplayID:(NSString *)arg1;
- (BOOL)lockScreenIsShowing;
- (BOOL)deviceIsTethered;
- (BOOL)deviceIsBlocked;
- (BOOL)deviceIsPasscodeLockedRemotely;
- (BOOL)deviceIsPasscodeLocked;
- (BOOL)deviceIsLocked;
- (BOOL)applicationInstalledForDisplayID:(NSString *)arg1;
- (BOOL)isApplicationForegroundObscured:(NSString *)arg1;
- (NSString *)localizedDisplayNameForDisplayID:(NSString *)arg1;
- (NSString *)foregroundApplicationDisplayID;
- (long long)activeInterfaceOrientation;
- (void)updateInterfaceOrientationIfNecessary;
@end

