//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class BSAnimationSettings, NSNumber, NSString, SBUIRemoteAlertIdleTimerSettings;

@protocol SBUIRemoteAlertHostInterface
- (void)setSceneDeactivationReason:(NSNumber *)arg1;
- (void)setWhitePointAdaptivityStyle:(long long)arg1;
- (void)setOrientationChangedEventsEnabled:(BOOL)arg1;
- (void)setLaunchingInterfaceOrientation:(long long)arg1;
- (void)setSupportedInterfaceOrientationOverride:(NSUInteger)arg1;
- (void)setShouldDisableFadeInAnimation:(BOOL)arg1;
- (void)setShouldDismissOnUILock:(BOOL)arg1;
- (void)setStatusBarHidden:(BOOL)arg1 withDuration:(double)arg2;
- (void)setReachabilityDisabled:(BOOL)arg1;
- (void)setInteractiveScreenshotGestureDisabled:(BOOL)arg1;
- (void)setDesiredIdleTimerSettings:(SBUIRemoteAlertIdleTimerSettings *)arg1;
- (void)setDesiredAutoLockDuration:(double)arg1;
- (void)setIdleTimerDisabled:(BOOL)arg1 forReason:(NSString *)arg2;
- (void)setStyleOverridesToCancel:(int)arg1 animationSettings:(BSAnimationSettings *)arg2;
- (void)setDesiredStatusBarStyleOverrides:(int)arg1;
- (void)setSwipeDismissalStyle:(long long)arg1;
- (void)setDismissalAnimationStyle:(long long)arg1;
- (void)setAllowsAlertStacking:(BOOL)arg1;
- (void)setWallpaperStyle:(long long)arg1 withDuration:(double)arg2;
- (void)setBackgroundStyle:(long long)arg1 withDuration:(double)arg2;
- (void)setWallpaperTunnelActive:(BOOL)arg1;
- (void)setAllowsMenuButtonDismissal:(BOOL)arg1;
- (void)setDesiredHardwareButtonEvents:(NSUInteger)arg1;
- (void)invalidate;
- (void)deactivate;
- (void)dismiss;
- (void)setAllowsSiri:(BOOL)arg1;
- (void)setAllowsControlCenter:(BOOL)arg1;
- (void)setAllowsAlertItems:(BOOL)arg1;
- (void)setAllowsBanners:(BOOL)arg1;
@end

