//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBVoiceDisabledBundles : NSObject
{
}

+ (BOOL)voiceControlDisabledByCurrentlyRunningApp;
+ (void)setAppDisabledVoiceControl:(BOOL)arg1 bundleIdentifier:(id)arg2;

@end

