//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBTransientOverlayViewController.h>

#import <SpringBoard/CSExternalBehaviorProviding-Protocol.h>
#import <SpringBoard/SBVoiceControlViewControllerDelegate-Protocol.h>

@class NSArray, NSString, SBVoiceControlViewController, _UIBackdropView;
@protocol SBVoiceControlTransientOverlayViewControllerDelegate;

@interface SBVoiceControlTransientOverlayViewController : SBTransientOverlayViewController <SBVoiceControlViewControllerDelegate, CSExternalBehaviorProviding>
{
    _UIBackdropView *_backdropView;
    SBVoiceControlViewController *_contentViewController;
    id <SBVoiceControlTransientOverlayViewControllerDelegate> _voiceControlDelegate;
}

@property(nonatomic) __weak id <SBVoiceControlTransientOverlayViewControllerDelegate> voiceControlDelegate; // @synthesize voiceControlDelegate=_voiceControlDelegate;
// - (void).cxx_destruct;
- (void)resetSessionWithSource:(id)arg1;
- (void)handleHeadsetButtonUpFromButtonDownSource:(BOOL)arg1;
@property(nonatomic) BOOL shouldDisableVoiceControlForBluetoothRequests;
@property(nonatomic) BOOL shouldDisableHandlerActions;
@property(nonatomic) BOOL shouldAllowSensitiveActions;
@property(nonatomic, getter=isVoiceControlLoggingEnabled) BOOL voiceControlLoggingEnabled;
@property(copy, nonatomic) NSArray *nextRecognitionAudioInputPaths;
- (void)voiceControlViewControllerRequestsDismissal:(id)arg1;
- (void)voiceControlViewControllerPrefersProximityDetectionEnabledDidChange:(id)arg1;
- (long long)idleWarnMode;
- (long long)idleTimerMode;
- (long long)idleTimerDuration;
@property(readonly, nonatomic) long long proximityDetectionMode;
@property(readonly, nonatomic) NSUInteger restrictedCapabilities;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long scrollingStrategy;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *coverSheetIdentifier;
- (BOOL)shouldDisableOrientationUpdates;
- (void)setContainerOrientation:(long long)arg1;
- (BOOL)prefersProximityDetectionEnabled;
- (long long)preferredUnlockedGestureDismissalStyle;
- (long long)preferredLockedGestureDismissalStyle;
- (id)newTransientOverlayPresentationTransitionCoordinator;
- (id)newTransientOverlayDismissalTransitionCoordinator;
- (BOOL)handleHomeButtonPress;
- (void)endIgnoringAppearanceUpdates;
- (void)beginIgnoringAppearanceUpdates;
- (int)_preferredStatusBarVisibility;
- (BOOL)_canShowWhileLocked;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (id)childViewControllerForScreenEdgesDeferringSystemGestures;
- (id)childViewControllerForHomeIndicatorAutoHidden;
- (NSUInteger)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)resignFirstResponder;
- (long long)preferredWhitePointAdaptivityStyle;
- (long long)preferredStatusBarStyle;
- (long long)preferredInterfaceOrientationForPresentation;
- (BOOL)canResignFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)dealloc;
- (id)initWithSource:(id)arg1;

@end

