//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray;
@protocol SBVoiceControlViewControllerDelegate;

@interface SBVoiceControlViewController : UIViewController
{
    BOOL _prefersProximityDetectionEnabled;
    BOOL _shouldAllowSensitiveActions;
    BOOL _shouldDisableHandlerActions;
    BOOL _shouldDisableVoiceControlForBluetoothRequests;
    BOOL _voiceControlLoggingEnabled;
    NSArray *_nextRecognitionAudioInputPaths;
    id <SBVoiceControlViewControllerDelegate> _voiceControlDelegate;
}

@property(nonatomic) __weak id <SBVoiceControlViewControllerDelegate> voiceControlDelegate; // @synthesize voiceControlDelegate=_voiceControlDelegate;
@property(nonatomic, getter=isVoiceControlLoggingEnabled) BOOL voiceControlLoggingEnabled; // @synthesize voiceControlLoggingEnabled=_voiceControlLoggingEnabled;
@property(nonatomic) BOOL shouldDisableVoiceControlForBluetoothRequests; // @synthesize shouldDisableVoiceControlForBluetoothRequests=_shouldDisableVoiceControlForBluetoothRequests;
@property(nonatomic) BOOL shouldDisableHandlerActions; // @synthesize shouldDisableHandlerActions=_shouldDisableHandlerActions;
@property(nonatomic) BOOL shouldAllowSensitiveActions; // @synthesize shouldAllowSensitiveActions=_shouldAllowSensitiveActions;
@property(readonly, nonatomic) BOOL prefersProximityDetectionEnabled; // @synthesize prefersProximityDetectionEnabled=_prefersProximityDetectionEnabled;
@property(copy, nonatomic) NSArray *nextRecognitionAudioInputPaths; // @synthesize nextRecognitionAudioInputPaths=_nextRecognitionAudioInputPaths;
// - (void).cxx_destruct;
- (void)performPresentationTransitionAnimated:(BOOL)arg1 completionHandler:(id /* CDUnknownBlockType */)arg2;
- (void)performDismissalTransitionAnimated:(BOOL)arg1 completionHandler:(id /* CDUnknownBlockType */)arg2;
- (void)resetSessionWithSource:(id)arg1;
- (BOOL)handleHomeButtonPress;
- (void)handleHeadsetButtonUpFromButtonDownSource:(BOOL)arg1;
- (void)finalizeDismissalTransition;
- (id)initWithSource:(id)arg1;

@end

