//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableDictionary, PKPassLibrary;
@protocol SBUIBiometricResource;

@interface SBWalletPreArmController : NSObject
{
    PKPassLibrary *_passLibrary;
    id <SBUIBiometricResource> _biometricResource;
    long long _triggerSource;
    NSHashTable *_disabledPreArmAssertions;
    NSMutableDictionary *_disabledPreArmAssertionsByType;
}

+ (id)sharedInstance;
// - (void).cxx_destruct;
- (long long)_contactlessInterfaceSourceForTriggerSource:(long long)arg1;
- (long long)_computeTriggerSource;
- (void)presentPreArmInterfaceForTriggerSource:(long long)arg1 completion:(id /* CDUnknownBlockType */)arg2;
- (id)acquireSuppressPreArmAssertionOfType:(long long)arg1 forReason:(id)arg2;
- (id)acquireSuppressPreArmAssertionForReason:(id)arg1;
@property(readonly, nonatomic, getter=isPreArmExternallySuppressed) BOOL preArmExternallySuppressed; // @dynamic preArmExternallySuppressed;
@property(readonly, nonatomic, getter=isPreArmSuppressed) BOOL preArmSuppressed; // @dynamic preArmSuppressed;
@property(readonly, nonatomic, getter=isPreArmTriggeredByHomeButtonDoublePress) BOOL preArmTriggeredByHomeButtonDoublePress; // @dynamic preArmTriggeredByHomeButtonDoublePress;
@property(readonly, nonatomic, getter=isPreArmTriggeredByLockButtonDoublePress) BOOL preArmTriggeredByLockButtonDoublePress; // @dynamic preArmTriggeredByLockButtonDoublePress;
@property(readonly, nonatomic, getter=isPreArmAllowed) BOOL preArmAllowed; // @dynamic preArmAllowed;
@property(readonly, nonatomic, getter=isPreArmAvailable) BOOL preArmAvailable; // @dynamic preArmAvailable;
- (id)initWithPassLibrary:(id)arg1 biometricResource:(id)arg2;
- (id)init;

@end

