//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class SBWalletPrearmRecognizer;

@protocol SBWalletPrearmRecognizerDelegate <NSObject>
- (void)walletPrearmRecognizer:(SBWalletPrearmRecognizer *)arg1 didFailToRecognizeForReason:(NSUInteger)arg2;
- (void)walletPrearmRecognizerDidRecognize:(SBWalletPrearmRecognizer *)arg1;
@end

