//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBWindowHideState : NSObject
{
    BOOL _hidden;
    double _desiredAlpha;
}

@property double desiredAlpha; // @synthesize desiredAlpha=_desiredAlpha;
@property(getter=isHidden) BOOL hidden; // @synthesize hidden=_hidden;
- (id)description;

@end

