//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIScenePresentationContext, UIView, UIWindow;
@protocol UIScenePresentation, UIScenePresenter;

@interface SBWindowSelfHostWrapper : NSObject
{
    UIWindow *_window;
    id <UIScenePresenter> _presenter;
    UIView<UIScenePresentation> *_hostView;
}

+ (id)wrapperForWindow:(id)arg1 orientation:(long long)arg2 hostRequester:(id)arg3 sceneIdentifier:(id)arg4;
+ (id)wrapperForUseInWindow:(id)arg1 hostRequester:(id)arg2 sceneIdentifier:(id)arg3;
@property(readonly, nonatomic) id <UIScenePresenter> presenter; // @synthesize presenter=_presenter;
@property(readonly, nonatomic) UIView<UIScenePresentation> *hostView; // @synthesize hostView=_hostView;
@property(readonly, nonatomic) UIWindow *window; // @synthesize window=_window;
// - (void).cxx_destruct;
- (void)stopHosting;
- (void)modifyPresentationContext:(id /* CDUnknownBlockType */)arg1;
@property(readonly, copy, nonatomic) UIScenePresentationContext *presentationContext;
@property(readonly, copy, nonatomic) NSString *requester;

@end

