//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>

@class BSAnimationSettings, NSMutableArray, NSMutableDictionary, NSSet, NSString, SBWorkspaceTransitionRequest;

@interface SBWorkspaceTransitionContext : NSObject <BSDescriptionProviding>
{
    SBWorkspaceTransitionRequest *_request;
    NSMutableDictionary *_entities;
    NSMutableDictionary *_previousEntities;
    BOOL _animationDisabled;
    BSAnimationSettings *_animationSettings;
    NSMutableArray *_finalizeBlocks;
    BOOL _finalized;
}

+ (id)context;
@property(readonly, nonatomic, getter=isFinalized) BOOL finalized; // @synthesize finalized=_finalized;
@property(retain, nonatomic) BSAnimationSettings *animationSettings; // @synthesize animationSettings=_animationSettings;
@property(nonatomic) BOOL animationDisabled; // @synthesize animationDisabled=_animationDisabled;
@property(nonatomic) __weak SBWorkspaceTransitionRequest *request; // @synthesize request=_request;
// - (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)compactDescriptionBuilderWithMultilinePrefix:(id)arg1;
- (void)finalize;
- (void)addFinalizeBlock:(id /* CDUnknownBlockType */)arg1;
- (id)previousEntityForIdentifier:(id)arg1;
- (id)previousEntityForKey:(id)arg1;
- (void)setPreviousEntity:(id)arg1 forKey:(id)arg2;
@property(readonly, copy, nonatomic) NSSet *previousEntities;
- (id)entityForIdentifier:(id)arg1;
- (id)entityForKey:(id)arg1;
- (void)setEntity:(id)arg1 forKey:(id)arg2;
@property(readonly, copy, nonatomic) NSSet *entities;
@property(readonly, copy) NSString *description;
- (id)init;

@end

