//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 22 2020 01:47:48).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@class TFBetaLaunchHandle;

@protocol TFBetaLaunchHandleActivationDelegate <NSObject>
- (void)betaLaunchHandle:(TFBetaLaunchHandle *)arg1 activateIfNeededEndedWithResult:(BOOL)arg2;
@end

