#!/bin/bash

source $DRAGONBUILD/internal/dragoncolors

echo -e "${PrefixColor}[Dragon]${BoldColor} Compiling TBDump (first time setup) ${NC}"

x = $PWD

cd $DRAGONBUILD/src/tbdump

env $'NINJA_STATUS=\x1b[1;34m[Dragon] \x1b[34m[%f/%t] \x1b[34m(%e)\x1b[0m ' CLICOLOR_FORCE=1 ninja

cp tbdump ../bin/tbdump

echo -e "${PrefixColor}[Dragon]${BoldColor} Done building TBDump ${NC}"

cd $x