#!/usr/bin/env bash

export PrefixColor='\033[1;34m'
export PackageColor='\033[1;32m'
export GenColor='\033[1;33m'
export BoldColor='\033[1;37m'
export NC='\033[0m'

prefix_print()
{
    echo -e "${PrefixColor}[Dragon]${BoldColor} $1${NC}"
}

gen_print()
{
    echo -e "${GenColor}[DragonGen]${BoldColor} $1${NC}"
}

pkg_print()
{
    echo -e "${PackageColor}[Packager]${BoldColor} $1${NC}"
}
