#!/usr/bin/env bash

generate()
{
    echo $DGEN_DEBUG | grep "1" > /dev/null && gen_print "DragonGen Debug Enabled"

    echo $simtarg | grep "1" > /dev/null && gen_print "Targeting Simulator + simject"

    eval $(DGEN_DEBUG=${DGEN_DEBUG} TARG_SIM=${simtarg} python3 -m dragongen.generation)

    export TWEAK_NAME=$package_name
    export INSTALL_CMD=$install_command
}
