#!/usr/bin/env bash

source $DRAGON_ROOT_DIR/internal/data/dragoncolors

set -e
source $DRAGON_ROOT_DIR/state/remoteip
LDIR=$PWD
RDIR=$(python3 -c 'import os;print("~/.dragon/server/" + os.getenv("PWD")')
RPAR="$(dirname "$RDIR")"
ssh ${USERN}@${IPA} "mkdir -p ${RDIR}"
prefix_print "Syncing..."
rsync -aL --exclude '.dragon' --exclude 'packages' --exclude '.idea' ${PWD} ${USERN}@${IPA}:$RPAR
prefix_print "Starting Build"
ssh ${USERN}@${IPA} -t "cd $RDIR; ~/.dragonbuild/dragon $*"
set +e
