#!/usr/bin/env bash

simfail()
{
    echo -e "${PrefixColor}[Dragon]${BoldColor} Simulator Injection Failed."
    echo -e "${PrefixColor}[Dragon]${BoldColor} Please file an issue with project details."
    drexit 1
}

simsetup()
{
    mkdir -p $DRAGON_ROOT_DIR/simulator/load
    hold=$PWD
    cd $DRAGON_ROOT_DIR/src/simject || simfail
    dragon c b
    cd $hold || simfail
}

simstall()
{
    test -f $DRAGON_ROOT_DIR/simulator/resim || simsetup
    echo -e "${PrefixColor}[Dragon]${BoldColor} Installing files to the simulator..."
    cp $DRAGON_DIR/_/Library/MobileSubstrate/DynamicLibraries/* $DRAGON_ROOT_DIR/simulator/load || cleanbuildfail
    echo -e "${PrefixColor}[Dragon]${BoldColor} Respringing..."
    resim
}
