#!/usr/bin/env bash

simfail()
{
    prefix_print "Simulator Injection Failed."
    prefix_print "Please file an issue with project details."
    prefix_print "https://github.com/DragonBuild/dragon"
    drexit 1
}

simsetup()
{
    mkdir -p $DRAGON_ROOT_DIR/simulator/load
    hold=$PWD
    cd $DRAGON_ROOT_DIR/src/simject || simfail
    dragon c b
    cd $hold || simfail
}

simstall()
{
    test -f $DRAGON_ROOT_DIR/simulator/resim || simsetup
    prefix_print "Installing files to the simulator..."
    cp $DRAGON_DIR/_/Library/MobileSubstrate/DynamicLibraries/* $DRAGON_ROOT_DIR/simulator/load || cleanbuildfail
    prefix_print "Respringing..."
    resim
}
