#!/usr/bin/env bash

DPREVERS=$(python3 -c 'from dragon.util import version; print(version())')

python3 -m pip install --upgrade dragon

DPOSTVERS=$(python3 -c 'from dragon.util import version; print(version())')

if [[ $DPOSTVERS == $DPREVERS ]]; then
    prefix_print "Latest version of dragon already installed"
else
    prefix_print "Updated dragon. Updating resources..."
    python3 -m dragon.wizard
fi
