# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - master
      - 'dev/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - master
      - 'dev/**'

jobs:
  tests:
    strategy:
      matrix:
        project-link:
          - https://github.com/KritantaDev/Chapters
          - https://github.com/KritantaDev/Docky
          - https://github.com/KritantaDev/Shakelight
          - https://github.com/KritantaDev/Gravitation
          - https://github.com/KritantaDev/Signe
          - https://github.com/KritantaDev/StatusViz
          - https://github.com/KritantaDev/StopCrashingPls
          - https://github.com/KritantaDev/libCozy
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ninja
        pip install pyyaml
        pip install git+git://github.com/dragonbuild/dragon
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install DragonBuild
      run: |
        dragon
    - name: Cloning Project
      run: |
        git clone ${{ matrix.project-link }}
    - name: Building Project
      run: |
        cd $(dirname $(find . -name DragonMake | xargs))
        dragon b
