# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - master
      - 'dev/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - master
      - 'dev/**'

jobs:
  tests:
    strategy:
      matrix:
        project-link:
          - https://github.com/kritanta-ios-tweaks/Chapters
          - https://github.com/kritanta-ios-tweaks/Pivot
          - https://github.com/kritanta-ios-tweaks/Shakelight
          - https://github.com/kritanta-ios-tweaks/Gravitation
          - https://github.com/kritanta-ios-tweaks/Signe
          - https://github.com/kritanta-ios-tweaks/StatusViz
          - https://github.com/kritanta-ios-tweaks/DeadRinger
    runs-on: macos-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        pip install "git+https://github.com/dragonbuild/dragon"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install DragonBuild
      run: |
        dragon
    - name: Cloning Project
      run: |
        git init .
        git remote add origin ${{ matrix.project-link }}
        git pull origin $(git remote show origin | grep "HEAD branch" | sed 's/.*: //')
    - name: Building Project
      run: |
        dragon b
