# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  tests:
    strategy:
      matrix:
        project-link:
          - https://github.com/kritanta-ios-tweaks/Chapters
          - https://github.com/kritanta-ios-tweaks/Pivot
          - https://github.com/kritanta-ios-tweaks/Shakelight
          - https://github.com/kritanta-ios-tweaks/Gravitation
          - https://github.com/kritanta-ios-tweaks/Signe
          - https://github.com/kritanta-ios-tweaks/StatusViz
          - https://github.com/kritanta-ios-tweaks/DeadRinger

    runs-on: macos-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        # Checkout relevant repo (e.g., main repo branch or fork)
        REPO=${{ github.event.pull_request.head.repo.full_name }}
        REF=${{ github.event.pull_request.head.ref }}

        if [[ -z "$REPO" ]]; then
          REPO=${{ github.repository }}
          REF=${{ github.ref }}
        fi

        python -m pip install --upgrade pip
        pip install "git+https://github.com/$REPO@$REF"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install dragon
      run: |
        dragon

    - name: Clone project
      run: |
        git init .
        git remote add origin ${{ matrix.project-link }}
        git pull origin $(git remote show origin | grep "HEAD branch" | sed 's/.*: //')

    - name: Build project
      run: |
        dragon c b
